---

- name: "Include prep"
  ansible.builtin.include_tasks: prep.yaml
  when: not release_switch_skip_prep

- name: "Include recovery"
  ansible.builtin.include_tasks: recovery.yaml
  when: not release_switch_skip_rec

- name: "Include os"
  ansible.builtin.include_tasks: os.yaml
  when: not release_switch_skip_os

- name: "Include release date"
  ansible.builtin.include_tasks: versioning.yaml
  when: not release_switch_skip_ver
