---

- include_tasks: ../../../common/tasks/setvars.yml
- include_tasks: ../../../common/tasks/clean.yml
- include_tasks: ../../../common/tasks/sync.yml
  when:
    - (override_reset_git == "undef" and reset_git | bool) or (override_reset_git | bool) or (override_sync | bool)

- include_tasks: ../../common/tasks/patch.yml
  when: 
    - (override_reset_git == "undef" and reset_git | bool) or (override_reset_git | bool) or (force_patch is defined and force_patch == "true")

- include_tasks: ../../common/tasks/copy.yml
