---

- name: "Release OS"
  block:

    - name: "Release OS for {{ BDEVICE }}"
      ansible.builtin.shell: |-
        {% if unstable_build | d(False) | bool %}
        scp {{ ZIPDIR }}/{{ item }} {{ groups.downloadserver[0] }}:{{ rempath | regex_replace('(/' + ROM_FLAVOR + ')/.*', '\1-unstable/') }}
        {% else %}
        scp {{ ZIPDIR }}/{{ item }} {{ groups.downloadserver[0] }}:{{ rempath }}
        {% endif %}
      delegate_to: "{{ groups.buildserver[0] }}"
      loop:
        - "{{ ROMFILE.stdout }}"
        - "{{ ROMFILE.stdout }}.sha*sum"
        - "{{ ROMFILE.stdout }}.prop"

    - name: "Correct ZIP timestamp for {{ BDEVICE }} to fix recurring OTA offering"
      ansible.builtin.file:
        path: "{{ rempath }}/{{ ROMFILE.stdout }}"
        modification_time: "{{ '%Y%m%d%H%M.%S' | strftime(build_date_utc.stdout) }}"
        access_time: "{{ '%Y%m%d%H%M.%S' | strftime(build_date_utc.stdout) }}"
        state: touch
      delegate_to: "{{ groups.downloadserver[0] }}"
      when: not unstable_build | d(False) | bool

    - name: "Verify ZIP integrity"
      ansible.builtin.shell: |
          if [ -f {{ ROMFILE.stdout }}.sha512sum ];then
            sha512sum --check {{ ROMFILE.stdout }}.sha512sum
          else
            sha256sum --check {{ ROMFILE.stdout }}.sha256sum
          fi
      args:
        chdir: "{{ rempath }}"
      delegate_to: "{{ groups.downloadserver[0] }}"
      when: not unstable_build | d(False) | bool
  
  when:
    - ROM_FLAVOR != "TWRP"
    - ROM_FLAVOR != "SHRP"
    - ROM_FLAVOR != "MAID"
    - axp_build_recovery_only is undefined or (axp_build_recovery_only is defined and not axp_build_recovery_only)

- name: "Release RECOVERY for {{ BDEVICE }}"
  ansible.builtin.shell: "scp {{ ZIPDIR }}/{{ item }} {{ groups.downloadserver[0] }}:{{ rempath }}"
  delegate_to: "{{ groups.buildserver[0] }}"
  loop:
    - "{{ ROMFILE.stdout }}"
    - "{{ ROMFILE.stdout }}.sha256sum"
  when:
    - ROM_FLAVOR == "TWRP" or ROM_FLAVOR == "SHRP" or (axp_build_recovery_only is defined and axp_build_recovery_only)

- name: "Release AXP.OS recovery"
  block:

    - name: "Prep AXP.OS recovery vars (slim)"
      ansible.builtin.set_fact:
          axp_fastboot_zip: "{{ axp_finalzip_dir }}/fastboot/{{ ROMFILE.stdout | regex_replace('.zip', '-fastboot.zip') }}"
          axp_recovery_name: "{{ axp_finalzip_dir }}/{{ ROMFILE.stdout | regex_replace('-SLIM-', '-SLIM-RECOVERY-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_boot: "{{ axp_finalzip_dir }}/{{ ROMFILE.stdout | regex_replace('-SLIM-', '-SLIM-BOOT-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_vboot: "{{ axp_finalzip_dir }}/{{ ROMFILE.stdout | regex_replace('-SLIM-', '-SLIM-VENDOR_BOOT-') | regex_replace('.zip', '.img') }}"
      when: axp_type == "slim"

    - name: "Prep AXP.OS recovery vars (non-slim)"
      ansible.builtin.set_fact:
          axp_fastboot_zip: "{{ axp_finalzip_dir }}/fastboot/{{ ROMFILE.stdout | regex_replace('.zip', '-fastboot.zip') }}"
          axp_recovery_name: "{{ axp_finalzip_dir }}/{{ ROMFILE.stdout | regex_replace('-dos-', '-RECOVERY-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_boot: "{{ axp_finalzip_dir }}/{{ ROMFILE.stdout | regex_replace('-dos-', '-BOOT-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_vboot: "{{ axp_finalzip_dir }}/{{ ROMFILE.stdout | regex_replace('-dos-', '-VENDOR_BOOT-') | regex_replace('.zip', '.img') }}"
      when: axp_type != "slim"
          
    - name: "Release AXP.OS RECOVERY for {{ BDEVICE }}"
      ansible.builtin.shell: |
          ZIPF=$(zipinfo -1 {{ axp_fastboot_zip }})
          has_recovery=$(echo "$ZIPF"| grep -c recovery)
          has_vendorboot=$(echo "$ZIPF"| grep -c vendor_boot)
          
          if [ $has_recovery -eq 1 ];then
            unzip -p {{ axp_fastboot_zip }} recovery.img > {{ axp_recovery_name }}
            sha256sum {{ axp_recovery_name }} > {{ axp_recovery_name }}.sha256
            scp {{ axp_recovery_name }}* {{ groups.downloadserver[0] }}:{{ rempath }}/recovery/
          elif [ $has_vendorboot -eq 1 ];then
            unzip -p {{ axp_fastboot_zip }} vendor_boot.img > {{ axp_recovery_name_vboot }}
            unzip -p {{ axp_fastboot_zip }} boot.img > {{ axp_recovery_name_boot }}
            sha256sum {{ axp_recovery_name_boot }} > {{ axp_recovery_name_boot }}.sha256
            sha256sum {{ axp_recovery_name_vboot }} > {{ axp_recovery_name_vboot }}.sha256
            scp {{ axp_recovery_name_boot }}* {{ groups.downloadserver[0] }}:{{ rempath }}/recovery/
            scp {{ axp_recovery_name_vboot }}* {{ groups.downloadserver[0] }}:{{ rempath }}/recovery/
          else
            unzip -p {{ axp_fastboot_zip }} boot.img > {{ axp_recovery_name_boot }}
            sha256sum {{ axp_recovery_name_boot }} > {{ axp_recovery_name_boot }}.sha256
            scp {{ axp_recovery_name_boot }}* {{ groups.downloadserver[0] }}:{{ rempath }}/recovery/
          fi
      delegate_to: "{{ groups.buildserver[0] }}"

  when:
    - ROM_FLAVOR == "axp"
    - axp_release_recovery | d(False)
    - not axp_build_recovery_only | d(False)
