---

- name: "Release OS"
  block:

    - name: "Prep folders"
      become: yes
      ansible.builtin.file:
        path: "{{ item }}"
        owner: "{{ release_path_owner }}"
        group: "{{ release_path_group }}"
        mode: "{{ release_path_perms }}"
        state: directory
      loop:
        - "{{ rempath }}/factory"
        - "{{ rempath }}/recovery"
        - "{{ rempath }}/tests"
      delegate_to: "{{ groups.downloadserver[0] }}"
      
    - name: "Release OS for {{ BDEVICE }}"
      ansible.builtin.shell: |-
        {% if axp_build_eng | bool %}
          if [ '{{ item }}' == '{{ ROMFILE.stdout }}.prop' ];then exit;fi
          LOCP="{{ SRCPATH }}/out/target/product/{{ sub_model | d(target_model) }}"
        {% else%}
          LOCP="{{ ZIPDIR }}"
        {% endif %}

        {% if unstable_build | d(False) | bool %}
        {%     if axp_type | d('') == "slim" %}
                  scp $LOCP/{{ item }} {{ hostvars['leechserver'].ansible_host }}:{{ rempath | regex_replace('(/' + ROM_FLAVOR + ')-slim/.*', '\1-unstable/') }}
        {%     else %}
                  scp $LOCP/{{ item }} {{ hostvars['leechserver'].ansible_host }}:{{ rempath | regex_replace('(/' + ROM_FLAVOR + ')/.*', '\1-unstable/') }}
        {%     endif %}
        {% else %}
                scp $LOCP/{{ item }} {{ hostvars['leechserver'].ansible_host }}:{{ rempath }}
        {% endif %}
      delegate_to: "{{ groups.buildserver[0] }}"
      loop:
        - "{{ ROMFILE.stdout }}"
        - "{{ ROMFILE.stdout }}.sha*sum"
        - "{{ ROMFILE.stdout }}.prop"

    - name: "Correct ZIP timestamp for {{ BDEVICE }} to fix recurring OTA offering"
      ansible.builtin.file:
        path: "{{ rempath }}/{{ ROMFILE.stdout }}"
        modification_time: "{{ '%Y%m%d%H%M.%S' | strftime(build_date_utc.stdout) }}"
        access_time: "{{ '%Y%m%d%H%M.%S' | strftime(build_date_utc.stdout) }}"
        state: touch
      delegate_to: "{{ groups.downloadserver[0] }}"
      when: not unstable_build | d(False) | bool

    - name: "Verify ZIP integrity"
      ansible.builtin.shell: |
          if [ -f {{ ROMFILE.stdout }}.sha512sum ];then
            sha512sum --check {{ ROMFILE.stdout }}.sha512sum
          else
            sha256sum --check {{ ROMFILE.stdout }}.sha256sum
          fi
      args:
        chdir: "{{ rempath }}"
      delegate_to: "{{ groups.downloadserver[0] }}"
      when: not unstable_build | d(False) | bool
  
  when:
    - ROM_FLAVOR != "TWRP"
    - ROM_FLAVOR != "SHRP"
    - ROM_FLAVOR != "MAID"
    - axp_build_recovery_only is undefined or (axp_build_recovery_only is defined and not axp_build_recovery_only)

- name: "Release RECOVERY for {{ BDEVICE }}"
  ansible.builtin.shell: "scp {{ ZIPDIR }}/{{ item }} {{ hostvars['leechserver'].ansible_host }}:{{ rempath }}"
  delegate_to: "{{ groups.buildserver[0] }}"
  loop:
    - "{{ ROMFILE.stdout }}"
    - "{{ ROMFILE.stdout }}.sha256sum"
  when:
    - ROM_FLAVOR == "TWRP" or ROM_FLAVOR == "SHRP" or (axp_build_recovery_only is defined and axp_build_recovery_only)

- name: "Release AXP.OS recovery"
  block:

    - name: "Prep AXP.OS recovery vars (slim)"
      ansible.builtin.set_fact:
          axp_fastboot_zip: "{{ ROMFILE.stdout | regex_replace('.zip', '-fastboot.zip') }}"
          axp_recovery_name: "{{ ROMFILE.stdout | regex_replace('-SLIM-', '-SLIM-RECOVERY-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_boot: "{{ ROMFILE.stdout | regex_replace('-SLIM-', '-SLIM-BOOT-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_vboot: "{{ ROMFILE.stdout | regex_replace('-SLIM-', '-SLIM-VENDOR_BOOT-') | regex_replace('.zip', '.img') }}"
      when: axp_type | d('') == "slim"

    - name: "Prep AXP.OS recovery vars (non-slim)"
      ansible.builtin.set_fact:
          axp_fastboot_zip: "{{ ROMFILE.stdout | regex_replace('.zip', '-fastboot.zip') }}"
          axp_recovery_name: "{{ ROMFILE.stdout | regex_replace('-dos-', '-RECOVERY-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_boot: "{{ ROMFILE.stdout | regex_replace('-dos-', '-BOOT-') | regex_replace('.zip', '.img') }}"
          axp_recovery_name_vboot: "{{ ROMFILE.stdout | regex_replace('-dos-', '-VENDOR_BOOT-') | regex_replace('.zip', '.img') }}"
      when: axp_type | d('') != "slim"
          
    - name: "Release AXP.OS RECOVERY for {{ BDEVICE }}"
      ansible.builtin.shell: |
          ZIPF=$(zipinfo -1 {{ axp_finalzip_dir }}/fastboot/{{ axp_fastboot_zip }})
          has_recovery=$(echo "$ZIPF"| grep -c recovery)
          has_vendorboot=$(echo "$ZIPF"| grep -c vendor_boot)

          {% if unstable_build | d(False) | bool %}
          {%     if axp_type | d('') == "slim" %}
                    REMPATH="{{ rempath | regex_replace('(/' + ROM_FLAVOR + ')-slim/.*', '\1-unstable/recovery') }}"
          {%     else %}
                    REMPATH="{{ rempath | regex_replace('(/' + ROM_FLAVOR + ')/.*', '\1-unstable/recovery') }}"
          {%     endif %}
          {% else %}
                  REMPATH="{{ rempath }}"
          {% endif %}
          
          if [ $has_recovery -eq 1 ];then
            unzip -p {{ axp_finalzip_dir }}/fastboot/{{ axp_fastboot_zip }} recovery.img > {{ axp_recovery_name }}
            
            {% if target_model_vendor | lower == "samsung" %}# Prepare an ODIN flashable image
            unzip -p {{ axp_finalzip_dir }}/fastboot/{{ axp_fastboot_zip }} recovery.img > recovery.img
            tar --format=ustar -cvf recovery.tar recovery.img \
              && md5sum -t recovery.tar >> recovery.tar \
              && mv recovery.tar {{ axp_recovery_name }}-ODIN_RENAME-TO_recovery.tar.md5 \
              && echo "Created ODIN flashable recovery file: ({{ axp_recovery_name }}-ODIN_RENAME-TO_recovery.tar.md5)!" | tee -a {{ BUILD_LOG }}
            rm recovery.img
            {% endif %}
            
            sha256sum {{ axp_recovery_name }} > {{ axp_recovery_name }}.sha256
            scp {{ axp_recovery_name }}* {{ hostvars['leechserver'].ansible_host }}:${REMPATH}/
            mv {{ axp_recovery_name }}* {{ axp_finalzip_dir }}/
          elif [ $has_vendorboot -eq 1 ];then
            unzip -p {{ axp_finalzip_dir }}/fastboot/{{ axp_fastboot_zip }} vendor_boot.img > {{ axp_recovery_name_vboot }}
            unzip -p {{ axp_finalzip_dir }}/fastboot/{{ axp_fastboot_zip }} boot.img > {{ axp_recovery_name_boot }}
            sha256sum {{ axp_recovery_name_boot }} > {{ axp_recovery_name_boot }}.sha256
            sha256sum {{ axp_recovery_name_vboot }} > {{ axp_recovery_name_vboot }}.sha256
            scp {{ axp_recovery_name_boot }}* {{ hostvars['leechserver'].ansible_host }}:${REMPATH}/
            scp {{ axp_recovery_name_vboot }}* {{ hostvars['leechserver'].ansible_host }}:${REMPATH}/
            mv {{ axp_recovery_name_boot }}* {{ axp_recovery_name_vboot }}* {{ axp_finalzip_dir }}/
          else
            unzip -p {{ axp_finalzip_dir }}/fastboot/{{ axp_fastboot_zip }} boot.img > {{ axp_recovery_name_boot }}
            sha256sum {{ axp_recovery_name_boot }} > {{ axp_recovery_name_boot }}.sha256
            scp {{ axp_recovery_name_boot }}* {{ hostvars['leechserver'].ansible_host }}:${REMPATH}/
            mv  {{ axp_recovery_name_boot }}* {{ axp_finalzip_dir }}/
          fi
      delegate_to: "{{ groups.buildserver[0] }}"

  when:
    - ROM_FLAVOR == "axp"
    - axp_release_recovery | d(False)
    - not axp_build_recovery_only | d(False)
