---
# yamllint disable rule:comments
#################################################################################################################################
# source: https://github.com/sfX-android/automation_scripts/blob/ansible/roles/axp/common_init_device/vars/copytemplate.yml
# v1.7
#################################################################################################################################
#################################################################################################################################

#################################################################################################################################
## Device info
#

# human readable model name
target_model_vendor: "Sony"
target_model_name: 'Xperia 10'

target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# path to the kernel dir
# e.g. "kernel/oneplus/msm8998"
target_kernel_dir: "kernel/sony/sdm660"

# git repo name of the device common tree
target_model_common_tree: "android_device_sony_nile-common"

# construct specific model device tree automatically
target_model_device_tree: android_device_{{ target_model_vendor | lower() }}_{{ target_model | lower() }}

# the common tree or if there is none the device main makefile,
# usually named device.mk or common.mk. used in e.g. switch_major_release role.
# defaults to "device.mk"
target_model_device_tree_mk: nile.mk

# do NOT upload the recovery image
#axp_release_recovery: false

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: true

# AVB version. Can be: 1|2|0 (if unset this defaults to 2).
axp_avb_version: 0

# boot debugger mount point
extendrom_debug_path_default: "/mnt/vendor/persist"

extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# git push project names related to this device. used for device init, reproducible builds, ci/cd
axp_git_push_device_include: "{{ target_model_device_tree }}|{{ target_model_common_tree }}"

# all used VENDOR paths for this device
axp_git_push_vendor_include: "{{ target_model_device_tree | replace('android_device_', 'vendor_') }}|{{ target_model_common_tree | replace('android_device_', 'vendor_') }}"

#################################################################################################################################
## Website info
#

# COMMON block
hugo_firmware: "manual"

# Is the device an A/B device (legacy or virtual)?
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'yes'

#hugo_xda_link: "" # link to the AXP.OS XDA post for that device
#hugo_kb_link: "" # OPTIONAL: knownissues link, only if there is any

#### SLIM block
android_version_slim: 15
hugo_relockable_slim: 'no'
hugo_encryption_slim: "ICE" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#hugo_axp_bootloader_id_slim: |- # if AVB: the bootloader id string (from build log)
hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
hugo_first_releasedate_slim: "2026-02-10" # first public stable release date (YYYY-MM-DD)
hugo_state_slim: "stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of:
#   "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel"
#hugo_patchlevel_slim: ""
