---

- name: "Grab DOS CVE Checker"
  ansible.builtin.get_url:
    url: "{{ divest_cve_checker_download }}"
    dest: "{{ divest_cve_checker_jar }}"
    mode: 0640
  retries: 10
  delay: 45
  register: fetch
  until: fetch.failed is defined
  changed_when: false
  when: not skip_dl_cve_checker | d(False)
