---

- include_tasks: sync.yml
  when: ktest_sync_dos | bool | d(False)

- include_role:
    name: axp/common
    tasks_from: prep.yml
    
- name: "Identify models"
  connection: local
  ansible.builtin.shell: |
    ls -1 ../roles/{{ kpath_roles_subdir }} | grep -vE "{{ model_exclusions }}"
  register: target_models

#- name: "List identified models"
#  debug:
#    msg: "Models: {{ target_models.stdout_lines }}"

- include_tasks: patch.yml
  vars:
    target_model: "{{ model }}"
  loop: "{{ target_models.stdout_lines }}"
  loop_control:
    loop_var: model
  
