---

- include_tasks: dl_patcher.yml

- name: "Identify models"
  connection: local
  ansible.builtin.shell: |
    ls -1 ../roles/{{ ROM_FLAVOR }} | grep -v common
  register: target_models

- name: "List identified models"
  debug:
    msg: "Models: {{ target_models.stdout_lines }}"

- include_tasks: patch.yml
  vars:
    target_model: "{{ model }}"
  loop: "{{ target_models.stdout_lines }}"
  loop_control:
    loop_var: model
  
