---

- include_tasks: dl_patcher.yml

- name: "Identify models"
  ansible.builtin.shell: |
    ls -1 ../../{{ ROM_FLAVOR }} | grep -v common
  register: target_models

- include_tasks: patch.yml
  vars:
    target_model: "{{ model }}"
  loop: "{{ target_models.items }}"
  loop_control:
    loop_var: model
  
