---

- name: "Sync DOS"
  shell: |
      git fetch --all
      git reset --hard origin/{{ axp_main_branch | d('axp') }}
      git checkout {{ axp_main_branch | d('axp') }}
      sed -i 's|git@gitlab.com:|https://gitlab.com/|' .git/config .gitmodules .git/modules/Patches/Linux/config .git/modules/PrebuiltApps/config
      git submodule update --init --recursive
      git submodule sync --recursive
      git submodule status >> {{ BUILD_LOG }} 2>&1
      git submodule update >> {{ BUILD_LOG }} 2>&1
      git submodule status >> {{ BUILD_LOG }} 2>&1
      git pull
      git lfs pull
      git log -1
  args:
    executable: /bin/bash
    chdir: "{{ DOSPATH }}"
