---

- name: "Disable 3rd party firmware blobs"
  ansible.builtin.replace:
    path: "{{ SRCPATH }}/vendor/{{ target_model_vendor | lower }}/{{ target_model }}/Android.mk"
    regexp: '^(\$\(call add-radio-file.*)'
    replace: '#\1'
