---
# human readable model name
target_model_vendor: "Fairphone"
target_model_name: '4'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# remove disk space reservation (e.g. on product partition)
remove_space_reservation: 'yes'

# android version
android_shortversion: a13

# boot debugger path & config
extendrom_debug_path_default: /metadata
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/fairphone/sm7225

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_fairphone_FP4

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: True

# upload the recovery image
axp_release_recovery: True

# add OpenEUICC
extendrom_package_list: "{{ extendrom_package_list_default }} OpenEUICC_AXP-OS"

# allow creating factory image
custom_build_command: "{{ SH_COMMON_FAIRPHONE_CREATE_FACTORY }}"

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: ''
axp_bootloader_id_slim: '272DE00712A447F3'

# git push
axp_git_push_device_include: "{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_fairphone_FP4"

# website info
hugo_encryption: "FBEv2"
hugo_firmware: "included"
hugo_relockable: "yes"
hugo_state: "stable"
hugo_supportlevel: "community"
hugo_isab: "yes"
hugo_xda_link: "https://xdaforums.com/t/rom-a-13-official-hardened-fp4-axp-os-20-0.4741001/"
hugo_first_releasedate: "2025-05-30"
hugo_kb_link: "fp4"
#hugo_custom_installguide_path: 
#hugo_axp_bootloader_id_pro: |
hugo_axp_bootloader_id_slim: |
    BOOTLOADER minimal ID
        272DE007

    BOOTLOADER full ID:
        272DE00712A447F3
        4AC484EB5E9A1A28
        3217A7174855F2EE
        1A4E16C591592826

hugo_patchlevel_slim: "Platform + Kernel<br/><i>(Firmware until 2025-11)</i>"

#################################################################################################################################
# vendor/firmware info
# source: https://support.fairphone.com/hc/en-us/articles/18896094650513-Install-Fairphone-OS-manually#01HB8ZZ1BMMQNSNMFT3YXDBXA0
vendor_firmware_super_img: True   # factory contains super image

# A13:
vendor_fairphone_factory_version: FP4-TP31-factory
vendor_firmware_download_url: "https://android-builds.fairphone.com/FP4/A13/{{ vendor_fairphone_factory_version }}.zip"
vendor_firmware_download_sha256: "7404233c93f281948134d114247a7dc4cd31466a64ea91f71c76df0f1aad6535"

# A15:
#vendor_fairphone_factory_version: FP4.QREL.15.14.3.20250923075848.user-factory
#vendor_firmware_download_url: "https://android-builds.fairphone.com/FP4/A15/{{ vendor_fairphone_factory_version }}.zip"
#vendor_firmware_download_sha256: "9976328f7994b11ccf0b4bf42f75bcdf68cede11bdedadb8e9f5c17c3498dee3"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though.
vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ vendor_fairphone_factory_version }}.zip"
#################################################################################################################################