---
# yamllint disable rule:comments
#################################################################################################################################
# source: https://github.com/sfX-android/automation_scripts/blob/ansible/roles/axp/common_init_device/vars/copytemplate.yml
# v1.7
#################################################################################################################################
#################################################################################################################################

#################################################################################################################################
## Device info
#

# human readable model name
target_model_vendor: "Fairphone"
target_model_name: '4'

target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# path to the kernel dir
# e.g. "kernel/oneplus/msm8998"
target_kernel_dir: "kernel/fairphone/sm7225"

# git repo name of the device common tree
target_model_common_tree: "android_device_fairphone_FP4"

# construct specific model device tree automatically
target_model_device_tree: android_device_{{ target_model_vendor | lower() }}_{{ target_model | lower() }}

# add OpenEUICC
axp_euicc_capable: true

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: true

# boot debugger mount point
extendrom_debug_path_default: "/metadata"
extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# git push project names related to this device. used for device init, reproducible builds, ci/cd
axp_git_push_device_include: "{{ target_model_device_tree }}|{{ target_model_common_tree }}"

# all used VENDOR paths for this device
axp_git_push_vendor_include: "{{ target_model_device_tree | replace('android_device_', 'vendor_') }}|{{ target_model_common_tree | replace('android_device_', 'vendor_') }}"

# Bootloader ID (first line) for validating build log
#axp_bootloader_id_pro: ''
axp_bootloader_id_slim: '272DE00712A447F3'

# remove any extra disk space reservation (e.g. on product partition)
remove_space_reservation: 'yes'

#################################################################################################################################
## Website info
#

# COMMON block
hugo_firmware: "included"

# Is the device an A/B device (legacy or virtual)?
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'yes'

hugo_xda_link: "https://xdaforums.com/t/rom-a-13-official-hardened-fp4-axp-os-20-0.4741001/"
hugo_kb_link: "fp4" # OPTIONAL: knownissues link, only if there is any
#hugo_custom_installguide_path: "" # OPTIONAL: custom installation guide

#### PRO block
#android_version_pro: 
#hugo_relockable_pro: ''
#hugo_encryption_pro: "" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#hugo_axp_bootloader_id_pro: |- # if AVB: the bootloader id string (from build log)
#hugo_supportlevel_pro: "community"  # i.e.: "team" | "community"
#hugo_first_releasedate_pro: "TBD" # first public stable release date (YYYY-MM-DD)
#hugo_state_pro: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
#hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
#hugo_patchlevel_pro: ""

#### SLIM block
android_version_slim: 13
hugo_relockable_slim: 'yes'
hugo_encryption_slim: "FBEv2" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
hugo_axp_bootloader_id_slim: |-
    BOOTLOADER minimal ID
        272DE007

    BOOTLOADER full ID:
        272DE00712A447F3
        4AC484EB5E9A1A28
        3217A7174855F2EE
        1A4E16C591592826
hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
hugo_first_releasedate_slim: "2025-05-30" # first public stable release date (YYYY-MM-DD)
hugo_state_slim: "stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of:
#   "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel"
#hugo_patchlevel_slim: "Platform + Kernel<br/><i>(Firmware until 2025-11)</i>"


#################################################################################################################################
## FIRMWARE info
#
# source:

# do not use any quotes here:
vendor_firmware_super_img: true

#vendor_firmware_version: "" # filename without zip

# direct download link to the OTA zip of the vendor.
#vendor_firmware_download_url: ""
#vendor_firmware_download_sha512: ""
#vendor_firmware_download_sha256: ""

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
#vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_firmware_version }}.zip"
#################################################################################################################################

#################################################################################################################################
## FACTORY info (only relevant for: Google Pixel, Fairphone)
#
# source: https://support.fairphone.com/hc/en-us/articles/18896094650513-Install-Fairphone-OS-manually#01HB8ZZ1BMMQNSNMFT3YXDBXA0

# A13:
vendor_factory_id: "FP4-TP31"
#https://android-builds.fairphone.com/FP4/A13/FP4-TP31-factory.zip
vendor_factory_version: "{{ vendor_factory_id }}-factory"
vendor_factory_download_url: "https://android-builds.fairphone.com/FP4/A13/{{ vendor_factory_id }}.zip"
vendor_factory_download_sha256: "7404233c93f281948134d114247a7dc4cd31466a64ea91f71c76df0f1aad6535"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_factory_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_factory_version }}.zip"
#################################################################################################################################
