---

- name: "Enable AVB based on supported version"
  ansible.builtin.shell: |
    # credits: DivestOS (https://git.disroot.org/AXP.OS/build/src/commit/25b87d3e9b9c64b3c0b7b47d36e883cf2b80d67a/Scripts/Common/Enable_Verity.sh)
    {{ DOS_INIT }}
    lunch lineage_{{ sub_model | d(target_model) }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 \
      && echo "lunching device ({{ sub_model | d(target_model) }}) succeeded" >> {{ BUILD_LOG }} 2>&1

    umask 0022
    source "$DOS_SCRIPTS_COMMON/Shell.sh"
    cd "$DOS_BUILD_BASE"

    enableVerity() {
      echo "Enabling verity..."
      if [ -d "$DOS_BUILD_BASE/$1" ]; then
        cd "$DOS_BUILD_BASE/$1";
        #TODO: skip if recoveryonly is set?
        sed -i '/\/system/{/verify/!s|wait|wait,verify|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true;
        cd "$DOS_BUILD_BASE";
        echo "Enabled verity for $1";
      fi;
    }; export -f enableVerity

    enableAVB() {
      echo "Enabling AVB..."
      if [ -d "$DOS_BUILD_BASE/$1" ]; then
        cd "$DOS_BUILD_BASE/$1"
        awk -i inplace '!/AVB_MAKE_VBMETA_IMAGE_ARGS \+= --set_hashtree_disabled_flag/' *.mk &>/dev/null || true
        if [[ "$1" == *"xiaomi"* ]]; then #XXX: broken
          sed -i 's/AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3/AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2/' *.mk &>/dev/null || true
          echo "Setting PERMISSIVE AVB for $1"
        else
          awk -i inplace '!/AVB_MAKE_VBMETA_IMAGE_ARGS \+= --flag/' *.mk &>/dev/null || true
          echo "Setting ENFORCING AVB for $1"
        fi
        #Disable chaining
        awk -i inplace '!/BOARD_AVB_VBMETA_SYSTEM/' *.mk &>/dev/null || true
        awk -i inplace '!/BOARD_AVB_VBMETA_VENDOR/' *.mk &>/dev/null || true
        awk -i inplace '!/BOARD_AVB_BOOT/' *.mk &>/dev/null || true
        #awk -i inplace '!/BOARD_AVB_RECOVERY/' *.mk &>/dev/null || true # Must be defined for if non-A/B is supported.
        awk -i inplace '!/vbmeta_system \\/' *.mk &>/dev/null || true
        awk -i inplace '!/vbmeta_vendor \\/' *.mk &>/dev/null || true
        sed -i 's/vbmeta_system//' *.mk &>/dev/null || true
        sed -i 's/vbmeta_vendor//' *.mk &>/dev/null || true
        sed -i '/\/system /{s|avb=vbmeta_system|avb=vbmeta|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/system_ext/{s|avb=vbmeta_system|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/system_ext/{s|avb=vbmeta|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/vendor/{s|avb=vbmeta_system|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/vendor/{s|avb=vbmeta_vendor|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/vendor/{s|avb=vbmeta|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        #sed -i '/\/pvmfw/{s|avb=pvmfw|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        #sed -i '/\/boot/{s|avb=boot|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        #sed -i '/\/init_boot/{s|avb=init_boot|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/product/{s|avb=vbmeta_system|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        sed -i '/\/product/{s|avb=vbmeta|avb|}' *fstab* */*fstab* */*/*fstab* &>/dev/null || true
        #TODO: remove avb_keys=.*?
        echo "Enabled AVB for $1"
        cd "$DOS_BUILD_BASE"
      fi;
    }; export -f enableAVB

    {% if android_version_int | int >= 11 and axp_avb_version < 2 %}
    echo "SKIPPING enabling verity (Android {{ android_version_int }} does not support AVB v1.x anymore!)"
    {% elif axp_avb_version >= 2 %}
    enableAVB "{{target_model_device_tree_path}}" >> {{ BUILD_LOG }} 2>&1
    enableAVB "{{target_model_common_tree_path}}" >> {{ BUILD_LOG }} 2>&1
    {% else %}
    enableVerity "{{target_model_device_tree_path}}" >> {{ BUILD_LOG }} 2>&1
    enableVerity "{{target_model_common_tree_path}}" >> {{ BUILD_LOG }} 2>&1
    # Kernel Changes
    [[ -d kernel/essential/msm8998 ]] && sed -i 's/slotselect/slotselect,verify/' kernel/essential/msm8998/arch/arm64/boot/dts/essential/msm8998-mata-lineage.dtsi &>/dev/null || true #/vendor
    [[ -d kernel/google/marlin ]] && sed -i 's/wait,slotselect/wait,slotselect,verify/' kernel/google/marlin/arch/arm64/boot/dts/htc/msm8996-htc-common.dtsi &>/dev/null || true #/vendor
    [[ -d kernel/moto/shamu ]] && sed -i 's/wait/wait,verify/g' kernel/moto/shamu/arch/arm/boot/dts/qcom/apq8084.dtsi &>/dev/null || true #/system
    [[ -d kernel/oneplus/msm8996 ]] && sed -i 's/wait/wait,verify/g' kernel/oneplus/msm8996/arch/arm/boot/dts/qcom/15801/msm8996-mtp.dtsi &>/dev/null || true #/system
    [[ -d kernel/oneplus/msm8998 ]] && sed -i 's/wait/wait,verify/g' kernel/oneplus/msm8998/arch/arm/boot/dts/qcom/cheeseburger.dtsi &>/dev/null || true #/system and /vendor
    [[ -d kernel/oneplus/msm8998 ]] && sed -i 's/wait/wait,verify/g' kernel/oneplus/msm8998/arch/arm/boot/dts/qcom/dumpling.dtsi &>/dev/null || true #/system and /vendor
    [[ -d kernel/samsung/exynos7870 ]] && sed -i 's/wait/wait,verify/g' kernel/samsung/exynos7870/arch/arm64/boot/dts/exynos7870-j5y17lte_common.dtsi &>/dev/null #/system
    [[ -d kernel/zuk/msm8996 ]] && sed -i 's/wait/wait,verify/g' kernel/zuk/msm8996/arch/arm/boot/dts/qcom/zuk/common.dtsi &>/dev/null || true #/system and /vendor
    sed -i 's/^\treturn VERITY_STATE_DISABLE;//' kernel/*/*/drivers/md/dm-android-verity.c &>/dev/null || true
    #sed -i 's/#if 0/#if 1/' kernel/*/*/drivers/power/reset/msm-poweroff.c &>/dev/null || true #TODO: needs refinement
    {% endif %}
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
