---
# must be explicitly included!

# allow to (manually) set selinux permissive
axp_allow_permissive: False

# extendrom stuff
extendrom_package_list_default: "{{ extendrom_package_list_common }}"
extendrom_preroot_boot: "false"
extendrom_allow_any_call_recording: 'false'

# keys
keysdir: "{{ keys_base_path }}/{{ os_name }}-{{ axp_type }}/{{ target_model }}"
# ensure we use our common apps key used to signed our own apps (e.g. OpenEUICC)
common_apps_keydir: "{{ keys_base_path }}/{{ os_name }}-{{ axp_type }}/common"

# path overrides
rempath: "{{ rempath | regex_replace('/axp/', '/axp-slim/') }}"

device_cl: |-
  ***{{ target_model_full | regex_escape() }}*** ***\({{ target_model | regex_escape() }}\)*** \- ***{{ ROM_FLAVOR | regex_escape() }}\-{{ axp_type }}***

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | regex_escape() }}]({{ leech_server }}/{{ ROM_FLAVOR | regex_escape() }}\-{{ axp_type }}/{{ target_model }})
