---

# set expected results accordingly to the AVB setup
parselogerr:
  - search: 'key .*/testkey.*.pem' # ALWAYS COPY THIS! we NEVER EVER want something signed with a testkey
    expect: ''
  - search: '{{ android_signing_testkey }}' # ALWAYS COPY THIS! we NEVER EVER want something signed with a testkey
    expect: ''
  - search: '{{ android_signing_testkey_verity }}' # ALWAYS COPY THIS! we NEVER EVER want something signed with a testkey
    expect: ''
  - search: 'signed by google test keys' # AVB v1 only: fail if signature test bails
    expect: ''
  - search: "{{ axp_bootloader_id }}" # AVB only: Check the device's bootloader ID (dynamic based on flavor)
    expect_cnt: 1
  - search: "({{ axp_avb_bootparts }}).img: Signature is VALID" # AVB v1 only: boot_signer output
    expect_cnt: "{{ axp_avb_bootparts_count }}"
  - search: '^VERIFIED$' # AVB v1 only: verity_verifier output
    expect_cnt: "{{ axp_avb_dmparts_count }}"
