---

- block:

   - name: "AXP.OS base repo: hard reset"
     ansible.builtin.shell: |
       export HOME="{{ BUILDHOME }}"
       echo "BEFORE reset:" > {{ BUILD_LOG }}
       git log -1 >> {{ BUILD_LOG }} 2>&1
       git status >> {{ BUILD_LOG }} 2>&1
       if [ $? -eq 128 ];then
         echo "No local changes in AXP.OS base repo found!"  >> {{ BUILD_LOG }}
       else
         git am --abort >> {{ BUILD_LOG }} 2>&1
         git rebase --abort >> {{ BUILD_LOG }} 2>&1
         if [ ! -f ".gitignore" ]; then
            wget https://raw.githubusercontent.com/AXP-OS/build/refs/heads/axp/.gitignore
         fi
         git add -A . && git stash save befreset-$(date +%F_%T) >> {{ BUILD_LOG }} 2>&1
       fi
       git reset --hard origin/{{ axp_main_branch | d('axp') }} >> {{ BUILD_LOG }} 2>&1
       git remote set-url origin {{ axp_git_repo }}
       git pull
       git submodule status >> {{ BUILD_LOG }} 2>&1 
       git submodule deinit -f .
       if [ -d Patches/Linux/ ];then rm -rf Patches/Linux/;fi
       git submodule sync
       git submodule update --init --recursive --checkout >> {{ BUILD_LOG }} 2>&1
       git submodule status >> {{ BUILD_LOG }} 2>&1
     args:
       chdir: "{{ DOSPATH }}"
       executable: /bin/bash
       
   - name: "AXP.OS base repo: state"
     ansible.builtin.shell: |
        echo "AFTER reset + sync:" >> {{ BUILD_LOG }}
        git log -1 >> {{ BUILD_LOG }} 2>&1
        git status >> {{ BUILD_LOG }} 2>&1
     args:
       chdir: "{{ DOSPATH }}"

  when:
     - (override_reset_git == "undef" and reset_git | bool) or (override_reset_git | bool) or (override_sync | bool)
     - dosdir.stat.isdir is defined

- name: "Prepare build path"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ SRCPATH }}"

- block:

   - ansible.builtin.include_tasks: ../../../common/tasks/clean.yml
     #vars:
     #  override_reset_git: 'true'
    
   - name: "Specific DOS -basic- cleanup"
     ansible.builtin.file:
       path: "{{ item }}"
       state: absent
     no_log: true
     loop:
       - "{{ SRCPATH }}/out/target/product/{{ target_model }}/rec_tmp"
   
   # DO NOT use ansible.builtin.file here!
   # e.g. kernel paths will break this. it seems it causes a high load on Semaphore site when there are too many kernels to be deleted.
   # in particular within MySQL which (I guess here) likely cannot handle the massive amount of entries -> even when using no_log:true which still
   # causes several lines in the log output (no log enabled bla)
   - name: "Specific paths -full- cleanup"
     ansible.builtin.shell: |
        echo "cleaning: {{ axp_clean_paths | join(' ') }}" >> {{ BUILD_LOG }}
        for WHAT in {{ axp_clean_paths | join(' ') }};do
           rm -rf $WHAT ".repo/projects/${WHAT}.git" ".repo/projects/${WHAT}.git" .repo/project-objects/platform/$WHAT  >> {{ BUILD_LOG }} 2>&1 || true
        done
     when: 
        - (override_reset_git == "undef" and reset_git | bool) or (override_reset_git | bool) or (override_sync | bool)
   
   - name: "Specific AXP.OS -full- cleanup"
     ansible.builtin.shell: |
        if [ -d "{{ item.path }}" ];then find {{ item.path }} {{ item.extra | d('') }} -name {{ item.file }} -delete -print; fi
     args:
       chdir: "{{ SRCPATH }}"
     loop:
       - { path: "vendor/axp", file: "EXTENDROM_PATCHER_DONE" }
       - { path: "vendor/extendrom", file: "EXTENDROM_PATCHER_DONE" }
       - { path: "./", file: ".wg.patched", extra: "-maxdepth 1" }
     when:
        - (override_reset_git == "undef" and reset_git | bool) or (override_reset_git | bool) or (override_sync | bool)

  when: dosdir.stat.isdir is defined

- name: "Reset: kernel sources (>A14 + Google Pixel)"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    cd {{ git_pixel_kernel_source }}
    
    if [ -f .defconf.patched ];then rm -v .defconf.patched;fi
    (git am --abort; git rebase --abort; git add -A; git reset --hard FETCH_HEAD) >> {{ BUILD_LOG }} 2>&1 || true   
  args:
    executable: /bin/bash
  when: pixel_kernel_gki | bool
