---

- include_role:
    name: axp/common_init_device
    tasks_from: setup_vendor_firmware.yml
  vars:
    vendor_firmware_aosp_path: "{{ SRCPATH }}/vendor/firmware"
    build_log_init: "{{ BUILD_LOG }}"
    skip_setup_firmware_fetch: True
    skip_setup_firmware_clean: True
    init_device_remotename: "axp.os-private" # comes from manifest, we have no var atm
