---

- name: "Git commit changes"
  when: not axp_skip_common_tasks
  block:

    - name: "Set a git commit message"
      ansible.builtin.set_fact:
        commit_message: "{{ custom_commit_message | d('AXP.OS: uncatched scripted change') }}"

    # if not all changes are committed the kernel version will be suffixed with "<hash>-dirty"
    # so before a build all changes must have been committed
    - name: "Git commit changes in kernel directory"
      ansible.builtin.shell: |
          if [ -d "{{ item }}" ];then
            export LC_ALL=C
            source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}-{{ android_shortversion }}-{{ axp_type | upper() }}

            echo "[GIT] checking kernel changes in {{ item }}" >> {{ BUILD_LOG }}
            # add unstaged changes
            CMT=0
            git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
            # check for uncommitted changes
            CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
            # commit if any of the above require it
            if [ $CMT -eq 1 -o $CMTL -gt 0 ];then
                git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "{{ commit_message }}"
                echo "[GIT] committed scripted kernel changes for {{ item }}" >> {{ BUILD_LOG }}
            fi
          else
            echo "[GIT] WARN: >{{ item }}< is not an existing directory!"
          fi
      args:
        executable: /bin/bash
      loop:
        - "{{ SRCPATH }}/{{ target_kernel_dir }}"
        - "{{ pixel_kernel_defconfig_basepath | d('undef') }}"
      when: git_commit_kernel

    - name: "Git commit changes in given directory"
      ansible.builtin.shell: |
          if [ -d "{{ git_commit_path }}" ];then
            export LC_ALL=C
            source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}-{{ android_shortversion }}-{{ axp_type | upper() }}

            echo "[GIT] checking changes in {{ git_commit_path }}" >> {{ BUILD_LOG }}
            # add unstaged changes
            CMT=0
            git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
            # check for uncommitted changes
            CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
            # commit if any of the above require it
            if [ $CMT -eq 1 -o $CMTL -gt 0 ];then
                git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "{{ commit_message }}"
                echo "[GIT] committed scripted kernel changes for {{ git_commit_path }}" >> {{ BUILD_LOG }}
            fi
          else
            echo "[GIT] WARN: >{{ git_commit_path }}< is not an existing directory!"
          fi
      args:
        executable: /bin/bash
      when: git_commit_path is defined
