---

- name: "Push any detected change"
  ansible.builtin.shell: |
    export LC_ALL=C
    export PATH="~/.local/bin:$PATH"
    {{ DOS_INIT }}

    # make all functions available for any sub shell
    export -f $(declare -F | awk '{print $3}')
    
    # tag name
    export TAG="{{ build_id }}_{{ sub_model | d(target_model) }}_{{ android_shortversion }}{% if axp_type | d('') == "slim" %}_slim{% endif %}"
    # fallback tag
    export PTAG=${TAG}_$(date +%s)
    
    # reproduce manifest
    export REPRMANIFEST=".repo/local_manifests/axp_cicd.xml.repr"

    # repos using branches on different paths
    check_for_branch_repo() {
      rep="$1"
      declare -A branchrepos=(
          [android_device_qcom_sepolicy]=1
          [android_device_qcom_sepolicy_vndr]=1
          [android_hardware_qcom_audio]=1
          [android_hardware_qcom_audio-ar]=1
          [android_hardware_qcom_display]=1
          [android_hardware_qcom_media]=1
          [android_hardware_qcom_wlan]=1
          [android_vendor_qcom_opensource_agm]=1
          [android_vendor_qcom_opensource_arpal-lx]=1
          [android_vendor_qcom_opensource_data-ipa-cfg-mgr]=1
      )
      if [[ "${branchrepos[$rep]}" ]]; then
        echo 1
      else
        echo 0
      fi
    }
    export -f check_for_branch_repo
    
    # write full manifest
    {{ repo_bin }} manifest -r -o ${REPRMANIFEST} >> {{ BUILD_LOG }} 2>&1
    
    process_repo() {
      #set -e

      local repo="${1}"
      croot
      echo "[GIT] processing $repo"
      reponame_orig=$(echo "$repo" | cut -d ':' -f2)
      reponame=$(echo "$repo" | cut -d ':' -f2 | sed 's#LineageOS/##g;s#/#_#g')
      localpath=$(echo "$repo" | cut -d ':' -f1)

      if [ -z "$TAG" -o -z "$PTAG" ]; then echo "ERROR: $reponame: TAG ($PTAG) or PTAG ($PTAG) is EMPTY!!" && return 3;fi

      # kernel match
      kpcheck=$(echo "$reponame" | grep kernel_ || true)
      if [ ! -z "$kpcheck" ];then
          kcheck=$(echo "$reponame" | grep -Eo "{{ target_kernel_dir | regex_replace('/private/gs-google','') | regex_replace('/','_') }}" || true)
          if [ -z "$kcheck" ];then
              echo "[GIT] skipped $reponame as its not our kernel"
              return
          fi
      fi
      # vendor match
      vpcheck=$(echo "$reponame" | grep -E "$AXP_GIT_PUSH_VENDOR_EXCLUDE" || true)
      if [ ! -z "$vpcheck" ];then
          vcheck=$(echo "$reponame" | grep -Eo "$AXP_GIT_PUSH_VENDOR_INCLUDE" || true)
          if [ -z "$vcheck" ];then
              echo "[GIT] skipped $reponame as its not our vendor"
              return
          fi
      fi
      # device match
      dpcheck=$(echo "$reponame" | grep -E "$AXP_GIT_PUSH_DEVICE_EXCLUDE" || true)
      if [ ! -z "$dpcheck" ];then
          dcheck=$(echo "$reponame" | grep -Eo "$AXP_GIT_PUSH_DEVICE_INCLUDE" || true)
          if [ -z "$dcheck" ];then
              echo "[GIT] skipped $reponame as its not our device"
              return
          fi
      fi
      
      cd $localpath
      echo "[GIT] switched to $localpath"
      
      # commit any leftovers!
      # besides "normal" patches divest also run several patch scripts(!) which by design can not be
      # catched regularly (i.e. they do not use git am, git apply, patch .. but awk, sed etc to modify)
      # to also make these changes available for reproducible builds and transparency we commit them once now:
      CMT=0
      # add unstaged changes
      git add -A || CMT=1
      # check for uncommitted changes
      CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
      # commit if any of the above require it
      if [ $CMT -eq 1 -o $CMTL -gt 0 ];then 
          git commit {{ git_commit_args | d('') }} --author="${DOS_GIT_AUTHOR} <${DOS_GIT_MAIL}>" -m "uncatched DOS scripted change(s)"
          echo "[GIT] committed scripted divest changes for $reponame"
      fi
      
      # check and add new repo if needed only
      CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
      REMHASH=$(git log --pretty=oneline --decorate | grep "m/{{ los_version_gitbranch }}" |cut -d ' ' -f1)

      if [ "$CURHASH" != "$REMHASH" ]; then
        echo -e "\n[GIT] WARNING: changes detected ($CURHASH != $REMHASH) in $localpath ($reponame) which needs to be pushed!\n"
      else
        echo "[GIT] no changes in $localpath, skipping"
        return
      fi

      # generic vendor match
      repoisvendor=$(echo "$reponame" | grep vendor_ | grep -vE "packages|qcom|nxp|lineage" || true)
      
      # create repo if non-existent
      # using a workaround as github cli does not allow to set permission on create
      # see: https://github.com/cli/cli/issues/2241#issuecomment-1402316546
      # requires to auth/login first: 
      # $> gh auth login
        # $> tea login add (see common/defaults/main.yml for details)
      git remote remove up 2>> /dev/null || true
      git fetch --unshallow >> /dev/null 2>&1 || true
      # first check if this is a problematic repo
      prepo=$(echo "{{ git_private_repos | d('undefined') }},${repoisvendor}" | tr ',' '\n' | grep "${reponame}$" || true)

      git remote add up {{ git_axpos_org_private }}/${reponame}.git 2>&1
      echo "[GIT] processing {{ git_axpos_org_private }}/$reponame "
      
      if $(git fetch up >> /dev/null 2>&1);then
        echo "[GIT] repo exists within the org already"
      else
        echo "[GIT] repo does not exist within the org yet! Creating..."
        git remote remove up 2>> /dev/null || true
        git checkout $REMHASH
        tea repos create --login {{ git_axpos_org_private_login }} --name ${reponame} --owner {{ git_axpos_org_name }} --description "forked from: $(git remote -v | head -n1 | cut -f2 | cut -d ' ' -f1)" 2>&1
        echo "[GIT] repo created on remote ({{ git_axpos_org_private_login }})..."

        echo "[GIT] LFS processing on >remote< branch"
        for lf in $(find . -type f -size +2M -name '*.*'| while read file; do f="${file##*.}"; [ ${{ "{" }}{{ "#" }}f} -ge 2 ] && echo "$f" ; done | sort -u);do
          git lfs track \"*.${lf}\" || true
        done
        CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
        if [ $CMTL -gt 0 ];then
          git add -A . >> /dev/null \
            && git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: track files bigger than 2M"  >> /dev/null
        fi

        echo "[GIT] LFS processing on >local< branch"
        export REMHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
        echo "[GIT] overwrite REMHASH->$REMHASH"
        git checkout $CURHASH >> /dev/null
        for lf in $(find . -type f -size +2M -name '*.*'| while read file; do f="${file##*.}"; [ ${{ "{" }}{{ "#" }}f} -ge 2 ] && echo "$f" ; done | sort -u);do
          git lfs track \"*.${lf}\" || true
        done
        CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
        if [ $CMTL -gt 0 ];then
          git add -A .  >> /dev/null \
            && git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: track files bigger than 2M"  >> /dev/null
        fi
        
        export CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
        echo "[GIT] checked out CURHASH=$CURHASH"
        git remote add up {{ git_axpos_org_private }}/${reponame}.git
      fi
      
      # push origin sources first
      # falls back to push in batches to workaround issues when index pack is too big
      rerr=0
      if [ ! -z "$REMHASH" -a "$REMHASH" != "up/HEAD" ];then
          echo "[GIT] REMHASH is set and valid"
          resp=$(git push --force -u up $REMHASH:refs/heads/upstream_{{ android_shortversion }} 2>&1) || rerr=$?
      else
          echo "[GIT] REMHASH is empty or invalid"
          resp=$(git push --force -u up HEAD:refs/heads/upstream_{{ android_shortversion }} 2>&1) || rerr=$?
      fi
      echo "rerr=$rerr"

      if [ "$rerr" -ne 0 ]; then
          # some repos need extra caution as they use the same repo but checking out different branches at different paths
          specialfound=$(check_for_branch_repo "${reponame}")
          if [ "$specialfound" == "0" ];then
            echo "[GIT] REMHASH is $REMHASH"
            found=0
            echo "$resp" | tail -n 20 | grep -q "pack exceeds maximum allowed size" || found=1
            if [ $found -eq 0 ]; then
                echo "[GIT] pack size too big for $reponame, pushing in chunks now.."
                max=$(git log --oneline|wc -l); for i in $(seq  $max -60000 1); do g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done \
                || (echo "[GIT] reducing chunk size to: 10000"; max=$(git log --oneline|wc -l); for i in $(seq  $max -10000 1); do g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done) \
                || (echo "[GIT] reducing chunk size even more to: 1000"; max=$(git log --oneline|wc -l); for i in $(seq  $max -1000 1); do g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); git push --force up $g:refs/heads/upstream_{{ android_shortversion }}; done)
                if [ $? -ne 0 ];then
                    echo "$resp" | tail -n 20
                    exit 3
                fi
                # now the final push should just work
            else
              found=0
              echo "$resp" | tail -n 20 | grep -q "fatal: did not receive expected object" || found=1
              if [ $found -eq 0 ]; then
                obj=$(echo "$resp" | tail -n 20 | grep -o "fatal: did not receive expected object .*" | cut -d ' ' -f 7)
                git push --force -u up ${obj}:refs/heads/upstream_{{ android_shortversion }} 2>&1
              else
                echo "[GIT] error $rerr occured while pushing"
                echo "$resp" | tail -n 20
                exit $rerr
              fi
            fi
            if [ ! -z "$REMHASH" -a "$REMHASH" != "up/HEAD" ];then
                echo "[GIT] Final push"
                git push --force -u up $REMHASH:refs/heads/upstream_{{ android_shortversion }} 2>&1
            else
                echo "[GIT] Final push (fresh)" >> {{ BUILD_LOG }}
                git push --force -u up HEAD:refs/heads/upstream_{{ android_shortversion }} 2>&1
            fi
            echo "[GIT] pushed/updated upstream_{{ android_shortversion }} (check_for_branch_repo result was: $specialfound)"
          else
            echo "[GIT] skipping upstream push as this due to check_for_branch_repo result ($specialfound)"
          fi
          echo "[GIT] pushed/updated upstream_{{ android_shortversion }}"
      fi

      # tag the current patched state and push accordingly
      TE=0
      git tag -a "$TAG" -m "axp.os: tagged on $TAG" || TE=1
      if [ $TE -eq 1 ];then
          echo "[GIT] will force push tag: $TAG"
          git tag -d "$TAG" >> {{ BUILD_LOG }} 2>&1 || true
          git push up --delete "$TAG" || true
          git tag -a "$TAG" -m "axp.os: tagged {{ sub_model | d(target_model) }} on $TAG"
          git push --force --set-upstream up $TAG
          echo "[GIT] FORCE pushed new tag: $TAG"
      else
          git push --set-upstream up $TAG 2>&1
          echo "[GIT] pushed new tag: $TAG"
      fi
          
      # change manifest line to point to AXP.OS org, ensures private org for proprietary
      croot
      if [ -z "$prepo" ];then
        echo "[GIT] setting manifest for $reponame to AXP.OS >{{ git_axpos_org_public_host }}<"
        sed -i -E 's|(name=".*")\s+(path="'$localpath'")\s+remote="([[:graph:]]+)" |name="'$reponame'" \2 remote="axp.os" |g' ${REPRMANIFEST}
      else
        echo "[GIT] setting manifest for $reponame to AXP.OS >{{ git_axpos_org_limited_host }}<"
        sed -i -E 's|(name=".*")\s+(path="'$localpath'")\s+remote="([[:graph:]]+)" |name="'$reponame'" \2 remote="axp.os-private" |g' ${REPRMANIFEST}
      fi
      echo "[GIT] updated manifest for: $reponame"
    }
    export -f process_repo

    # check where we changed origin
    # for repo in $({{ repo_bin }} list | tr -d ' ');do
    #   # ...
    # done
    {{ repo_bin }} list | tr -d ' ' | parallel --halt now,fail=1 -j {{ git_push_max_processes }} process_repo >> {{ BUILD_LOG }} 2>&1

    # push manifest
    croot
    mv ${REPRMANIFEST} .repo/local_manifests/axp.xml
    cd .repo/local_manifests/
    cp -a {{ BUILDHOME }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.sh . || true
    git remote remove up 2>> /dev/null || true
    git remote add up {{ git_axpos_org_private }}/manifest.git
    git add -A || true
    git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "added/changed $TAG"
    git tag -a "$TAG" -m "axp.os: tagged on $TAG" 2>> /dev/null || (git tag -d "$TAG"; git push up --delete "$TAG" 2>> /dev/null || true ; git tag -a "$TAG" -m "axp.os: tagged on $TAG")
    git push --set-upstream up $TAG
    echo "[GIT] pushed manifest tag: $TAG" >> {{ BUILD_LOG }}
    croot
    mv .repo/local_manifests/axp.xml ${REPRMANIFEST}
    echo "[GIT] fully completed!" >> {{ BUILD_LOG }}
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

- name: "Push APP versions"
  ansible.builtin.shell: |
    export LC_ALL=C
    export PATH="~/.local/bin:$PATH"
    {{ DOS_INIT }}
    
    # tag name
    TAG="{{ build_id }}"
    MTAG="{{ build_id }}_{{ sub_model | d(target_model) }}_{{ android_shortversion }}{% if axp_type | d('') == "slim" %}_slim{% endif %}"
    CDIR=$PWD
    LTAG="$TAG"

    cd external/axp_versioning
    git remote add up {{ git_axpos_org_private }}/axp_versioning >> {{ BUILD_LOG }} 2>&1 || true
    git fetch up --tags --force
    git tag | grep "$TAG" || LTAG=$(git tag | tail -n1)
    
    # base on the previous tag (for comparison) or an existing
    git checkout $LTAG >> {{ BUILD_LOG }} 2>&1

    # always get the latest template & readme
    git checkout FETCH_HEAD template.md >> {{ BUILD_LOG }} 2>&1
    git checkout FETCH_HEAD README.md >> {{ BUILD_LOG }} 2>&1
    cd $CDIR
    
    echo "[VERSIONING] create list of APK versions..." >> {{ BUILD_LOG }}
    for erapp in {{ extendrom_package_list | d(extendrom_package_list_default) }}; do
        for app in $(find vendor/extendrom/prebuilt out/target/product/{{ sub_model | d(target_model) }} -type f -name "${erapp}*.apk"); do
            AVER=$(aapt dump badging "${app}" | gawk -F \' '/^package: name/{print $6}')
            ANAME=$(aapt dump badging "${app}" | gawk -F \' '/application-label:/{print $2}')
            echo "|${ANAME}|\`${AVER}\`|"
        done
    done | sort -u | grep -vE "Placeholder|Framework Proxy" > out/allapps.versions
    echo -e "[VERSIONING] List created: \n$(cat out/allapps.versions)" >> {{ BUILD_LOG }}

    echo "[VERSIONING] create version file from template..." >> {{ BUILD_LOG }}
    awk '/\|-\|-\|/ { print; system("cat out/allapps.versions"); next }1' external/axp_versioning/template.md > temp_file && mv temp_file external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md

    # add changelog: AOSmium
    sed -i -E 's#(AOSmium)#[\1](https://code.binbash.rocks/AXP.OS/app_aosmium/commits/branch/main)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: Aurora Store
    sed -i -E 's#(Aurora Store)#[\1](https://gitlab.com/AuroraOSS/AuroraStore/blob/HEAD/CHANGELOG)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: Etar
    sed -i -E 's#(Etar)#[\1](https://github.com/Etar-Group/Etar-Calendar/releases)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: F-Droid
    sed -i -E 's#(F-Droid)#[\1](https://gitlab.com/fdroid/fdroidclient/-/blob/HEAD/CHANGELOG.md)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: Fossify Gallery
    sed -i -E 's#(Gallery)#[\1](https://github.com/FossifyOrg/Gallery/blob/master/CHANGELOG.md)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: Google Play Store
    sed -i -E 's#(Google Play Store)#[\1](https://codeberg.org/AXP-OS/packages_apps_phonesky/releases/)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: Magisk
    sed -i -E 's#(Magisk)#[\1](https://github.com/topjohnwu/Magisk/releases)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: Neo Launcher
    sed -i -E 's#(Neo Launcher)#[\1](https://github.com/NeoApplications/Neo-Launcher/releases)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: microG
    sed -i -E 's#(microG Services)#[\1](https://github.com/microg/GmsCore/releases)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    # add changelog: OpenEUICC
    sed -i -E 's#(OpenEUICC)#[\1](https://gitea.angry.im/PeterCxy/OpenEUICC/commits/branch/master)#g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md

    # set device name
    sed -i 's/%%DEVICE%%/{{ target_model_full }}/g' external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md

    # set release date
    sed -i "s/%%RELDATE%%/$(date +%F) - or later/g" external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
    
    # set manifest
    sed -i "s#%%MANIFEST%%#https://{{ git_repo_local_manifests | regex_replace('.*git@','') | regex_replace(':','/') }}/src/tag/$MTAG#g" external/axp_versioning/{{ sub_model | d(target_model) }}_{% if axp_type | d('') == "slim" %}slim{% else %}pro{% endif %}.md
  
    echo "[VERSIONING] prepare version repo..." >> {{ BUILD_LOG }}
    cd external/axp_versioning || exit 44
    if [ -f template.md ]; then rm template.md; fi
    git add -A .  >> /dev/null 2>> {{ BUILD_LOG }} || echo "nothing to add" >> {{ BUILD_LOG }}
    git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "add app versions for {{ build_id }}"  >> /dev/null 2>> {{ BUILD_LOG }} || echo "nothing to commit" >> {{ BUILD_LOG }}

    TE=0
    git tag -a "$TAG" -m "axp.os: tagged on $TAG" >> {{ BUILD_LOG }} 2>&1 || TE=1 
    if [ $TE -eq 0 ];then
      echo "[VERSIONING] [GIT] will push else new tag: $TAG" >> {{ BUILD_LOG }}
      git push --set-upstream up $TAG >> {{ BUILD_LOG }} 2>&1
      echo "[VERSIONING] [GIT] pushed new tag: $TAG" >> {{ BUILD_LOG }}
    else
      echo "[VERSIONING] [GIT] will force push a new tag: $TAG" >> {{ BUILD_LOG }}
      git tag -d "$TAG" >> {{ BUILD_LOG }} 2>&1 || true
      git push up --delete "$TAG" >> {{ BUILD_LOG }} 2>&1 || true
      git tag -a "$TAG" -m "axp.os: tagged {{ sub_model | d(target_model) }} on $TAG" >> {{ BUILD_LOG }} 2>&1
      git push --force --set-upstream up $TAG >> {{ BUILD_LOG }} 2>&1
      echo "[VERSIONING] [GIT] FORCE pushed new tag: $TAG" >> {{ BUILD_LOG }}
    fi
    echo "[VERSIONING] All DONE!"  
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
