---

- name: "Check AXP.OS state"
  ansible.builtin.stat:
    path: "{{ DOSPATH }}/.git"
  register: dosdir

- block:
      
    - name: "AXP.OS: initial Sync!"
      ansible.builtin.shell: |
          git init -b {{ axp_main_branch }}
          git remote add origin {{ axp_git_repo }} >> {{ BUILD_LOG }} 2>&1
          git fetch --all >> {{ BUILD_LOG }} 2>&1
          git pull >> {{ BUILD_LOG }} 2>&1
          git checkout "axp_main_branch | d('HEAD') }}" -f >> {{ BUILD_LOG }} 2>&1
          #git branch --set-upstream-to origin/{{ axp_main_branch | d('HEAD') }}
          
          sed -i 's|git@gitlab.com:|https://gitlab.com/|' .git/config .gitmodules .git/modules/Patches/Linux/config .git/modules/PrebuiltApps/config
          git submodule update --init --recursive
          git submodule status >> {{ BUILD_LOG }} 2>&1
          git submodule update >> {{ BUILD_LOG }} 2>&1
          git submodule status >> {{ BUILD_LOG }} 2>&1
          git pull >> {{ BUILD_LOG }} 2>&1
          git log -1 >> {{ BUILD_LOG }} 2>&1
      args:
        executable: /bin/bash
        chdir: "{{ DOSPATH }}"

  when: dosdir.stat.isdir is undefined
