---

- name: "Check AXP.OS state"
  ansible.builtin.stat:
    path: "{{ DOSPATH }}/.git"
  register: dosdir

- block:

    - name: "AXP.OS: Initial Sync!"
      ansible.builtin.shell: |
          [[ -n "$(echo "{{ axp_git_org }}" | grep -ve '^https\?://')" ]] \
              && ssh -o StrictHostKeyChecking=accept-new "{{ axp_git_org | regex_replace(':.*$', '') }}" >> {{ BUILD_LOG }} 2>&1
          git init -b {{ axp_main_branch }} >> {{ BUILD_LOG }} 2>&1
          git remote add origin {{ axp_git_repo }} >> {{ BUILD_LOG }} 2>&1
          git fetch --all >> {{ BUILD_LOG }} 2>&1
          git checkout -b "{{ axp_main_branch }}" --track "origin/{{ axp_main_branch }}" >> {{ BUILD_LOG }} 2>&1
          git clean -ffd >> {{ BUILD_LOG }} 2>&1
          git pull >> {{ BUILD_LOG }} 2>&1
          test -d .git/modules && rm -rf .git/modules # legacy DOS leftovers
          grep -q submodule .git/config && (echo "ERROR: pls remove ANY submodule config from $PWD/.git/config manually!" | tee -a {{ BUILD_LOG }}; exit 4)
          git clean -ffd >> {{ BUILD_LOG }} 2>&1
          git log -1 >> {{ BUILD_LOG }} 2>&1
      args:
        executable: /bin/bash
        chdir: "{{ DOSPATH }}"

  when: dosdir.stat.isdir is undefined
