---

- include_vars: axp-slim.vars.yml
  #no_log: true
  when: (axp_type | d(ROM_FLAVOR)) == "slim"

- include_vars: axp_lowend_device.vars.yml
  when: axp_lowend_device

- include_tasks: prep.yml
- include_vars: "../../{{ target_model }}/vars/main.yml"
- include_tasks: set_env_vars.yml
- include_tasks: init.yml

- name: "Just push-to-git selected!"
  block:
      - name: "Get local manifests (if set)"
        git:
          repo: "{{ git_repo_local_manifests }}"
          dest: "{{ SRCPATH }}/.repo/local_manifests"
          version: "{{ git_repo_local_manifests_branch }}"
          force: true
        timeout: 180
        when: git_repo_local_manifests is defined
    
      - include_tasks: git_push.yml
      - debug:
          msg: Stopping here as just_git_push=true
      - meta: end_play

  when:
    - just_git_push
    - not early_push | d(False)
  
- include_tasks: clean.yml
  when: axp_skip_common_tasks is undefined

# download latest firmware, taken from vendor/firmware/*/0SOURCE
- include_tasks: firmware_update.yml
  when: update_vendor_firmware

- block:

      - include_tasks: sync.yml
      - include_tasks: adjust_DOS_options.yml

      # download latest firmware, taken from vendor/firmware/*/0SOURCE
      - include_tasks: firmware_update.yml
        when: update_vendor_firmware

      # apply ASB patches if needed
      # currently LOS supports ASB patches up to and including: Android 13
      #- include_tasks: single_secpatch.yml
      - include_tasks: ../../common/tasks/secpatch.yml
        when: 
          - (android_version_int | int < 13) or sec_patch_unmerged
          
      # AXP.OS patches
      - include_tasks: patch.yml

      #- fail:
      #    msg: YEEEEEEeeeeeeeeeeeeeHa..
          
      # special deblob workarounds
      - include_tasks: patch_device_gs201.yml
        when: 
          - target_model == "cheetah"
          - android_version_int | int < 15

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")

- include_tasks: commit_kernel.yml
  when: axp_skip_common_tasks is undefined

- block:

      - name: "Early git push to AXP.OS org"
        include_tasks: git_push.yml

  when:
    - commit_push | bool
    - early_push | d(False)
          
