---

- name: "Include: axp-slim.vars.yml"
  ansible.builtin.include_vars: axp-slim.vars.yml
  when: (axp_type | d(ROM_FLAVOR)) == "slim"

- name: "Include: prep.yml"
  ansible.builtin.include_tasks: prep.yml
  when: not axp_skip_common_tasks

- name: "Include: target_model vars"
  ansible.builtin.include_vars: "../../{{ target_model }}/vars/main.yml"

- name: "Include: axp_lowend_device.vars.yml"
  ansible.builtin.include_vars: axp_lowend_device.vars.yml
  when: axp_lowend_device

- name: "Include: axp_avb1_device.vars.yml"
  ansible.builtin.include_vars: axp_avb1_device.vars.yml
  when: axp_avb_version == 1

- name: "Include: axp_avb0_device.vars.yml"
  ansible.builtin.include_vars: axp_avb0_device.vars.yml
  when: axp_avb_version == 0

- name: "Include: set_env_vars.yml"
  ansible.builtin.include_tasks: set_env_vars.yml
- name: "Include: init.yml"
  ansible.builtin.include_tasks: init.yml

- name: "Just push-to-git selected!"
  when:
    - just_git_push
    - not early_push | d(False)
  block:
    - name: "Get local manifests (if set)"
      ansible.builtin.git:
        repo: "{{ git_repo_local_manifests }}"
        dest: "{{ SRCPATH }}/.repo/local_manifests"
        version: "{{ git_repo_local_manifests_branch }}"
        force: true
      timeout: 180
      when: git_repo_local_manifests is defined

    - name: "Include git push"
      ansible.builtin.include_tasks: git_push.yml

    - name: "Debug"
      ansible.builtin.debug:
        msg: Stopping here as just_git_push=true

    - name: "END PLAY"
      ansible.builtin.meta: end_play

- name: "Cleanup"
  ansible.builtin.include_tasks: clean.yml
  when: not axp_skip_common_tasks

- name: "Get patch level based on axp_type"
  ansible.builtin.set_fact:
    axp_sec_patch_level_dyn: "{{ lookup('vars', 'hugo_patchlevel_' + axp_type | lower()) }}"

- name: "Set patch level based on axp_type"
  ansible.builtin.set_fact:
    sec_patch_level: >-
        {% if axp_sec_patch_level_dyn == "Platform + Kernel + Firmware" %}05{% elif axp_sec_patch_level_dyn == "Platform + Kernel" %}03{% else %}01{% endif %}

- name: "Sync & adjust"
  when:
    - (override_reset_git == "undef" and reset_git | bool) or (override_reset_git | bool) or (override_sync | bool)
  block:

    - name: "Include: sync.yml"
      ansible.builtin.include_tasks: sync.yml

    - name: "Include: adjust_DOS_options.yml"
      ansible.builtin.include_tasks: adjust_DOS_options.yml

    # download latest firmware, taken from vendor/firmware/*/0SOURCE
    - name: "Include: firmware_update.yml"
      ansible.builtin.include_tasks: firmware_update.yml
      when: update_vendor_firmware | bool or download_fairphone_firmware | bool

    # apply ASB patches if needed
    # currently LOS supports ASB patches up to and including: Android 14
    # - include_tasks: single_secpatch.yml

    - name: "Include: secpatch.yml"
      ansible.builtin.include_tasks: ../../common/tasks/secpatch.yml
      when:
        - (android_version_int | int < 14) or sec_patch_unmerged

    # AXP.OS patches
    - name: "Include: patch.yml"
      ansible.builtin.include_tasks: patch.yml
    - name: "Include: avb.yml"
      ansible.builtin.include_tasks: avb.yml

    - name: "Generate verity tools"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        lunch lineage_{{ sub_model | d(target_model) }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1
        mka generate_verity_key >> {{ BUILD_LOG }} 2>&1 || mka generate_verity_key >> {{ BUILD_LOG }} 2>&1
      changed_when: true
      args:
        chdir: "{{ SRCPATH }}"
        executable: /bin/bash

    # - fail:
    #    msg: YEEEEEEeeeeeeeeeeeeeHa..

    # special deblob workarounds
    # FIXME: can be removed once all gs201 device have been ported to A15
    - name: "Include: patch_device_gs201.yml"
      ansible.builtin.include_tasks: patch_device_gs201.yml
      when:
        - target_model == "cheetah"
        - android_version_int | int < 15

- name: "Include: commit_kernel.yml"
  ansible.builtin.include_tasks: commit_kernel.yml
  when: not axp_skip_common_tasks

- name: "Early git push to AXP.OS org"
  ansible.builtin.include_tasks: git_push.yml
  when:
    - commit_push | bool
    - early_push | d(False)
