---

- name: "Disable GPG verify if dirty build"
  ansible.builtin.lineinfile:
    path: "{{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/Functions.sh"
    line: '#verifyAllPlatformTag'
    regexp: '\s+verifyAllPlatformTags\;'
  when:
    - clean_out != "true" or (override_clean_out != "true") or (skip_gpg_verify | bool)

- name: "Disable wireguard handling by vendor/axp"
  ansible.builtin.file:
    path: "{{ SRCPATH }}/{{ target_kernel_dir }}/.wg.patched"
    state: touch
  when: skip_wireguard is defined and skip_wireguard | bool

- name: "Prepare kernel patchers"
  include_tasks: prep_kernel_patchers.yml

# part of patchWorkspace():
#
#- name: "apply DOS kernel patches (unsupported DOS devices)"
#  shell: |
#    {{ DOS_INIT }}
#    bash {{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/CVE_Patchers/android_{{ target_kernel_dir | regex_replace('/','_') }}.sh >> {{ BUILD_LOG }} 2>&1
#  args:
#    executable: /bin/bash
#  when:
#    - divest_unsupported_device
#    - unsupported_device_kernel_patch | bool

- name: "Apply DOS patches"
  ansible.builtin.shell: |
    # tensor need additional fixups
    if [ -f "{{ DOSPATH }}/Patches/LineageOS-{{ los_version }}/android/0001-tensor.patch" ];then
      cd {{ SRCPATH }}/.repo/manifests && git am {{ DOSPATH }}/Patches/LineageOS-{{ los_version }}/android/0001-tensor.patch; cd {{ SRCPATH }}
      PIXELDIRS=$(grep -o "name=.*" .repo/manifests/snippets/pixel.xml |cut -d '"' -f2 | tr '\n' ' ')
      {{ repo_bin }} sync --jobs-checkout={{ max_processes }} --jobs-network={{ max_processes_sync }} {{ repo_sync_args }} $PIXELDIRS
    fi
    # start CVE patcher
    {{ DOS_INIT }}
    patchWorkspaceReal >> {{ BUILD_LOG }} 2>&1
    resetEnv
    awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk
  register: patchout
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

# overlay does not work on A11, wt.. ?!
- name: "Logo: overlay workaround"
  ansible.builtin.shell: |
    cp vendor/axp/overlays/packages/apps/SetupWizard/res/drawable/logo.xml packages/apps/SetupWizard/res/drawable/logo.xml
  args:
    chdir: "{{ SRCPATH }}"

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "Apply AXP.OS adjustments"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    
    {% if sub_model is defined %}
    lunch lineage_{{ sub_model }}${brf_suffix}-user && echo lunch success
    {% else %}
    lunch lineage_{{ target_model }}${brf_suffix}-user && echo lunch success
    {% endif %}

    export AXP_DEVICE="{{ common_target_model | d(target_model) }}"
    export AXP_DEVICEVENDOR="{{ target_model_vendor | lower }}"
    export AXP_LOW_STORAGE="{{ remove_space_reservation | d('no') }}"
    
    vendor/axp/axp.sh
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

- name: "Apply AXP.OS patches (common)"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      resetEnv
      # apply
      {{ SRCPATH }}/vendor/extendrom/tools/apply_patches.sh {{ SRCPATH }}/vendor/axp/patches/common/{{ android_shortversion }}
      [ $? -ne 0 ] && exit 6
      # commit
      CHANGED=$(find -L vendor/axp/patches/common/{{ android_shortversion }} -type f -name '*.patch' -exec grep -H project {} \; | tr ' ' '#' | cut -d '#' -f2 | sort -u | tr '\n' ' ')
      {{ repo_bin }} forall -j{{ max_processes }} ${CHANGED} -c "git add -A && git commit --author='${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>' -m 'axp.os: applied vendor patches\n\nhttps://github.com/AXP-OS/vendor_axp/tree/main/patches/common/{{ android_shortversion }}'" >> {{ BUILD_LOG }} 2>&1
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
