---

- name: "Disable GPG verify if dirty build"
  ansible.builtin.lineinfile:
    path: "{{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/Functions.sh"
    line: '#verifyAllPlatformTag'
    regexp: '\s+verifyAllPlatformTags\;'
  when:
    - clean_out != "true" or (override_clean_out != "true") or (skip_gpg_verify | bool)

- name: "Prepare kernel patchers"
  include_tasks: prep_kernel_patchers.yml
  
- name: "Apply Wireguard patch"
  ansible.builtin.shell: |
      # patch kernel source to build wireguard module
      # (see: https://www.wireguard.com/compilation/#building-directly-in-tree)

      CPWD="{{ SRCPATH }}"

      {% if git_pixel_kernel_manifest_branch is defined and target_model_vendor == "Google" %}
      AXP_KERNEL_PATH="{{ git_pixel_kernel_source }}"
      {% else %}
      AXP_KERNEL_PATH="{{ target_kernel_dir }}"
      {% endif %}
      
      if [ ! -f "$AXP_KERNEL_PATH/.wg.patched" ];then
          cd $AXP_KERNEL_PATH
          if [ -d "net/wireguard" ];then rm -rf net/wireguard ;fi
          mkdir -p net/wireguard/compat
          if [ -f $CPWD/kernel/wireguard-linux-compat/kernel-tree-scripts/create-patch.sh ];then
              $CPWD/kernel/wireguard-linux-compat/kernel-tree-scripts/create-patch.sh | patch -p1 --no-backup-if-mismatch
              git add -A && git commit --author="Jason A. Donenfeld <Jason@zx2c4.com>" -m "apply wireguard-linux-compat"
              echo "[AXP] .. patched kernel sources for wireguard"
          else
              echo "[AXP] ERROR patching kernel sources for wireguard (missing compat patcher)!"
              exit 3
          fi
          cd $CPWD
          touch $AXP_KERNEL_PATH/.wg.patched
      else
          echo "[AXP] .. kernel is already patched for wireguard (patch indicator exists)"
      fi
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  when: skip_wireguard is undefined or not skip_wireguard | bool

- name: "Apply AXP.OS patches (common, >= A15)"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      resetEnv >> {{ BUILD_LOG }} 2>&1
      #FIXME: unclear atm why this causes an issue at all - while nowhere else in the world
      sed  '/var external_ndk_androidmks/a \        "system/qcom/softap/sdk/",' build/soong/ui/build/androidmk_denylist.go -i >> {{ BUILD_LOG }} 2>&1
      # fix: unrecognized property "product_variables.device_has_arm_mte.cflags"
      sed -i '/device_has_arm_mte[: ]*{/,/},/d' external/hardened_malloc/Android.bp >> {{ BUILD_LOG }} 2>&1
      # fix: build error due to removed lineage bloatware when making blueprint tools (also part of patchWorkspace but we need it earlier)
      awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk >> {{ BUILD_LOG }} 2>&1
      # fix: build errors due to removed system bloatware:
      # error: build/make/target/product/generic/Android.bp:1037:1: "aosp_shared_system_image" depends on undefined module "XXXX".
      for r in $(grep -r remove .repo/local_manifests/axp.xml | cut -d '"' -f2 |grep -v android_ ; echo PrintRecommendationService);do
        sed -E "s# (\"${r/*\/}\")# //\1#g" build/make/target/product/generic/Android.bp -i >> {{ BUILD_LOG }} 2>&1
      done
      # add AXP.OS BoardConfig globally!
      # FIXME: this makes common device tree includes obsolete!
      sed -i '/^INSTALLED_MISC_INFO_TARGET := $(PRODUCT_OUT)\/misc_info.txt$/a \
      \n# we need to encorce-include AXPs own BoardConfig here now.\n# while using the device tree'"'"'s BoardConfig worked fine up to A13 this\n# does not work in all cases with A15 anymore.\ninclude vendor/axp/BoardConfigVendor.mk' \
      build/core/Makefile
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  when: android_version_int | int > 14

- name: "Disable 3rd party firmware blobs"
  ansible.builtin.replace:
    path: "{{ SRCPATH }}/vendor/{{ target_model_vendor | lower }}/{{ target_model }}/Android.mk"
    regexp: '^(\$\(call add-radio-file.*)'
    replace: '#\1'
  when: android_version_int | int > 13

- name: "Apply DOS patches"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    #do not resetEnv
    # tensor need additional fixups
    if [ -f "{{ DOSPATH }}/Patches/LineageOS-{{ los_version }}/android/0001-tensor.patch" ];then
      cd {{ SRCPATH }}/.repo/manifests && git am {{ DOSPATH }}/Patches/LineageOS-{{ los_version }}/android/0001-tensor.patch; cd {{ SRCPATH }}
      PIXELDIRS=$(grep -o "name=.*" .repo/manifests/snippets/pixel.xml |cut -d '"' -f2 | tr '\n' ' ')
      {{ repo_bin }} sync --jobs-checkout={{ max_processes }} --jobs-network={{ max_processes_sync }} {{ repo_sync_args }} $PIXELDIRS >> {{ BUILD_LOG }} 2>&1
    fi
    
    # start DOS+AOS patching process
    {{ DOS_INIT }}

    lunch lineage_arm64${brf_suffix}-userdebug >> {{ BUILD_LOG }} 2>&1 && echo "lunching lineage bptarget succeeded" >> {{ BUILD_LOG }} 2>&1

    {% if android_version_int | int >= 15 %}
    # FIXME: this is a dirty hack!
    if [ -d /tmp/hardened_malloc ];then rm -rf /tmp/hardened_malloc; fi
    mv -v external/hardened_malloc /tmp >> {{ BUILD_LOG }} 2>&1
    mka blueprint_tools >> {{ BUILD_LOG }} 2>&1
    mv -v /tmp/hardened_malloc external/ >> {{ BUILD_LOG }} 2>&1
    {% endif %}

    lunch lineage_{{ sub_model | d(target_model) }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo "lunching real device ({{ sub_model | d(target_model) }}) succeeded" >> {{ BUILD_LOG }} 2>&1
    
    patchWorkspaceReal >> {{ BUILD_LOG }} 2>&1
    resetEnv >> {{ BUILD_LOG }} 2>&1
    awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk >> {{ BUILD_LOG }} 2>&1
  register: patchout
  environment:
    KERNEL_PATH_CVE: "{{ target_kernel_dir | regex_replace('/','_') }}"
    TERM: linux
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

# overlay does not work on A11, wt.. ?!
- name: "Logo: overlay workaround"
  ansible.builtin.shell: |
    cp vendor/axp/overlays/packages/apps/SetupWizard/res/drawable/logo.xml packages/apps/SetupWizard/res/drawable/logo.xml
  args:
    chdir: "{{ SRCPATH }}"

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "Apply AXP.OS adjustments"
  ansible.builtin.shell: |
    {{ DOS_INIT }}

    CPWD="{{ SRCPATH }}"
    export AXP_KERNEL_PATH="{{ target_kernel_dir }}"

    {% if sub_model is defined %}
    lunch lineage_{{ sub_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
    {% else %}
    lunch lineage_{{ target_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
    {% endif %}

    export AXP_DEVICE="{{ common_target_model | d(target_model) }}"
    export AXP_DEVICEVENDOR="{{ target_model_vendor | lower }}"
    export AXP_LOW_STORAGE="{{ remove_space_reservation | d('no') }}"
    export AXP_TARGET_VERSION={{ android_version_int }}

    {% if pixel_kernel_defconfig is defined and pixel_kernel_gki %}
    export AXP_KERNEL_CONF="{{ pixel_kernel_defconfig }}"
    {% else %}
    # get build vars (requires a lunch before!)
    export AXP_TARGET_ARCH=$(build/soong/soong_ui.bash --dumpvar-mode TARGET_ARCH  2>/dev/null)
    export AXP_KERNEL_CONF_FILE=$(build/soong/soong_ui.bash --dumpvar-mode TARGET_KERNEL_CONFIG 2>/dev/null | cut -d " " -f 1)
    export AXP_KERNEL_CONF="$AXP_KERNEL_PATH/arch/$AXP_TARGET_ARCH/configs/$AXP_KERNEL_CONF_FILE"
    {% endif %}
    
    # FIXME: legacy handling, should be merged here
    vendor/axp/axp.sh >> {{ BUILD_LOG }} 2>&1

    {% if not pixel_kernel_gki %}
      # patch kernel defconfig
      if [ ! -f "$AXP_KERNEL_PATH/.defconf.patched" ];then
          for cf in $AXP_DEFCONFIG_GLOBALS; do
            grep -q "^$cf=y" $AXP_KERNEL_CONF || echo -e "\n$cf=y" >> $AXP_KERNEL_CONF
            echo "[AXP] .. kernel globals defconfig $cf has been set" >> {{ BUILD_LOG }}
          done
          for cfd in $AXP_DEFCONFIG_DEVICE; do
            grep -q "^$cfd" $AXP_KERNEL_CONF || echo -e "\n$cfd" >> $AXP_KERNEL_CONF
            echo "[AXP] .. kernel device specific defconfig $cfd has been set" >> {{ BUILD_LOG }}
          done
          touch $AXP_KERNEL_PATH/.defconf.patched
          
          {% if pixel_kernel_defconfig is defined %}
          cp -v $AXP_KERNEL_CONF {{ target_model_common_tree_path }}/ >> {{ BUILD_LOG }} 2>&1
          cd {{ target_model_common_tree_path }}/
          {% else %}
          cd $AXP_KERNEL_PATH
          {% endif %}

          git add -A && git commit --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "defconfig: applied:
      
      $AXP_KERNEL_CONF $AXP_DEFCONFIG_DEVICE"
      
      else
          echo "[AXP] .. kernel defconfig is already patched (patch indicator exists)" >> {{ BUILD_LOG }}
      fi
    {% endif %}
    
    cd $CPWD
    # set displayed build id shown in About phone info
    sed -i "s/ro\.lineage\.version=\$(LINEAGE_VERSION)/ro.lineage.version={{ build_id }}-{{ axp_type | upper() }}/g" vendor/lineage
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

- name: "Apply AXP.OS patches (common, < A14)"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      resetEnv >> {{ BUILD_LOG }} 2>&1
      # apply
      {{ SRCPATH }}/vendor/extendrom/tools/apply_patches.sh {{ SRCPATH }}/vendor/axp/patches/common/{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1
      [ $? -ne 0 ] && exit 6
      # commit
      CHANGED=$(find -L vendor/axp/patches/common/{{ android_shortversion }} -type f -name '*.patch' -exec grep -H project {} \; | tr ' ' '#' | cut -d '#' -f2 | sort -u | tr '\n' ' ')
      if [ ! -z "$CHANGED" ];then
        {{ repo_bin }} forall -j{{ max_processes }} ${CHANGED} -c "git add -A && git commit {{ git_commit_args | d('') }} --author='${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>' -m 'axp.os: applied vendor patches
      
      https://github.com/AXP-OS/vendor_axp/tree/main/patches/common/{{ android_shortversion }}'" >> {{ BUILD_LOG }} 2>&1
      else
        echo "ERROR: no changes found! Seems the patches haven't applied properly"
        exit 3
      fi
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  when: android_version_int | int < 14

- name: "Fix release process on AVB 0 on A14 and later"
  ansible.builtin.replace:
    path: "{{ SRCPATH }}/build/make/tools/releasetools/sign_target_files_apks.py"
    regexp: "misc_info\\['avb_avbtool'\\]"
    replace: "'avbtool'"
  when: 
      - android_version_int | int > 13
      - axp_avb_version == 0
