---

- name: "Disable GPG verify if dirty build"
  ansible.builtin.lineinfile:
    path: "{{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/Functions.sh"
    line: '#verifyAllPlatformTag'
    regexp: '\s+verifyAllPlatformTags\;'
  when:
    - clean_out != "true" or (override_clean_out != "true") or (skip_gpg_verify | bool)

- name: "Disable wireguard handling by vendor/axp"
  ansible.builtin.file:
    path: "{{ SRCPATH }}/{{ target_kernel_dir }}/.wg.patched"
    state: touch
  when: skip_wireguard is defined and skip_wireguard | bool

- name: "Prepare kernel patchers"
  include_tasks: prep_kernel_patchers.yml

- name: "Apply AXP.OS patches (common, >= A15)"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      resetEnv >> {{ BUILD_LOG }} 2>&1
      #FIXME: unclear atm why this causes an issue at all - while nowhere else in the world
      sed  '/var external_ndk_androidmks/a \        "system/qcom/softap/sdk/",' build/soong/ui/build/androidmk_denylist.go -i >> {{ BUILD_LOG }} 2>&1
      # fix: unrecognized property "product_variables.device_has_arm_mte.cflags"
      sed -i '/device_has_arm_mte[: ]*{/,/},/d' external/hardened_malloc/Android.bp >> {{ BUILD_LOG }} 2>&1
      # fix: build error due to removed lineage bloatware when making blueprint tools (also part of patchWorkspace but we need it earlier)
      awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk >> {{ BUILD_LOG }} 2>&1
      # fix: build errors due to removed system bloatware:
      # error: build/make/target/product/generic/Android.bp:1037:1: "aosp_shared_system_image" depends on undefined module "XXXX".
      for r in $(grep -r remove .repo/local_manifests/axp.xml | cut -d '"' -f2 |grep -v android_ ; echo PrintRecommendationService);do
        sed -E "s# (\"${r/*\/}\")# //\1#g" build/make/target/product/generic/Android.bp -i >> {{ BUILD_LOG }} 2>&1
      done
      # add AXP.OS BoardConfig globally!
      # FIXME: this makes common device tree includes obsolete!
      sed -i '/^INSTALLED_MISC_INFO_TARGET := $(PRODUCT_OUT)\/misc_info.txt$/a \
      \n# we need to encorce-include AXPs own BoardConfig here now.\n# while using the device tree'"'"'s BoardConfig worked fine up to A13 this\n# does not work in all cases with A15 anymore.\ninclude vendor/axp/BoardConfigVendor.mk' \
      build/core/Makefile
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  when: android_version_int | int > 14

- name: "Disable 3rd party firmware blobs"
  ansible.builtin.replace:
    path: "{{ SRCPATH }}/vendor/{{ target_model_vendor | lower }}/{{ target_model }}/Android.mk"
    regexp: '^(\$\(call add-radio-file.*)'
    replace: '#\1'
  when: android_version_int | int > 13

- name: "Apply DOS patches"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    #do not resetEnv
    # tensor need additional fixups
    if [ -f "{{ DOSPATH }}/Patches/LineageOS-{{ los_version }}/android/0001-tensor.patch" ];then
      cd {{ SRCPATH }}/.repo/manifests && git am {{ DOSPATH }}/Patches/LineageOS-{{ los_version }}/android/0001-tensor.patch; cd {{ SRCPATH }}
      PIXELDIRS=$(grep -o "name=.*" .repo/manifests/snippets/pixel.xml |cut -d '"' -f2 | tr '\n' ' ')
      {{ repo_bin }} sync --jobs-checkout={{ max_processes }} --jobs-network={{ max_processes_sync }} {{ repo_sync_args }} $PIXELDIRS >> {{ BUILD_LOG }} 2>&1
    fi
    
    # start DOS+AOS patching process
    {{ DOS_INIT }}
    
    {% if sub_model is defined %}
    lunch lineage_{{ sub_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
    {% else %}
    lunch lineage_{{ target_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
    {% endif %}
    {% if android_version_int | int >= 15 %}mka blueprint_tools >> {{ BUILD_LOG }} 2>&1{% endif %}
    
    patchWorkspaceReal >> {{ BUILD_LOG }} 2>&1
    resetEnv >> {{ BUILD_LOG }} 2>&1
    awk -i inplace '!/enforce-product-packages-exist-internal/' vendor/lineage/config/common.mk >> {{ BUILD_LOG }} 2>&1
  register: patchout
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

# overlay does not work on A11, wt.. ?!
- name: "Logo: overlay workaround"
  ansible.builtin.shell: |
    cp vendor/axp/overlays/packages/apps/SetupWizard/res/drawable/logo.xml packages/apps/SetupWizard/res/drawable/logo.xml
  args:
    chdir: "{{ SRCPATH }}"

# AXP.OS adjustments (e.g wireguard, OTA,..)
- name: "Apply AXP.OS adjustments"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    
    {% if sub_model is defined %}
    lunch lineage_{{ sub_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
    {% else %}
    lunch lineage_{{ target_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1 && echo lunch success >> {{ BUILD_LOG }} 2>&1
    {% endif %}

    export AXP_DEVICE="{{ common_target_model | d(target_model) }}"
    export AXP_DEVICEVENDOR="{{ target_model_vendor | lower }}"
    export AXP_LOW_STORAGE="{{ remove_space_reservation | d('no') }}"
    
    vendor/axp/axp.sh >> {{ BUILD_LOG }} 2>&1
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"

- name: "Apply AXP.OS patches (common, < A14)"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      resetEnv >> {{ BUILD_LOG }} 2>&1
      # apply
      {{ SRCPATH }}/vendor/extendrom/tools/apply_patches.sh {{ SRCPATH }}/vendor/axp/patches/common/{{ android_shortversion }} >> {{ BUILD_LOG }} 2>&1
      [ $? -ne 0 ] && exit 6
      # commit
      CHANGED=$(find -L vendor/axp/patches/common/{{ android_shortversion }} -type f -name '*.patch' -exec grep -H project {} \; | tr ' ' '#' | cut -d '#' -f2 | sort -u | tr '\n' ' ')
      if [ ! -z "$CHANGED" ];then
        {{ repo_bin }} forall -j{{ max_processes }} ${CHANGED} -c "git add -A && git commit {{ git_commit_args | d('') }} --author='${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>' -m 'axp.os: applied vendor patches
      
      https://github.com/AXP-OS/vendor_axp/tree/main/patches/common/{{ android_shortversion }}'" >> {{ BUILD_LOG }} 2>&1
      else
        echo "ERROR: no changes found! Seems the patches haven't applied properly"
        exit 3
      fi
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  when: android_version_int | int < 14
