---

- block:

    - name: "Ensure the defined sources paths exist"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ SRCPATH }}"
        - "{{ DOSPATH }}"
        - "{{ persistent_dir }}"
        - "~/.local/gh"
        - "~/.local/tea"

    - name: Copy DOS renamer
      ansible.builtin.copy:
        src: rename
        dest: "{{ SRCPATH }}/"
        mode: "0755"

  when: ROM_FLAVOR != "kernel_patches_tester"

- name: "Grab CVE Checker"
  ansible.builtin.get_url:
    url: "{{ divest_cve_checker_download }}"
    dest: "{{ divest_cve_checker_jar }}"
    mode: "0640"
    timeout: 90
  register: fetch
  # until: fetch.failed is defined
  retries: 4
  delay: 30
  # changed_when: false
  when: not skip_dl_cve_checker | d(True) | bool

- name: "Prep helper"
  when:
      - commit_push | bool
      - not skip_dl_git_cli_tools | d(True) | bool
  block:

      - name: "Prep Github CLI"
        ansible.builtin.unarchive:
            remote_src: yes
            src: "{{ github_cli_download_uri }}"
            dest: "~/.local/gh"
            
      - name: "Setup Github CLI"
        ansible.builtin.copy:
            remote_src: yes
            src: "~/.local/gh/gh_{{ github_cli_version }}_linux_amd64/bin/gh"
            dest: "~/.local/bin/gh"
            mode: 0755

      - name: "Prep Gitea CLI"
        ansible.builtin.get_url:
            url: "{{ gitea_cli_download_uri }}"
            dest: "~/.local/tea"

      - name: "Setup Gitea CLI"
        ansible.builtin.copy:
            remote_src: yes
            src: "~/.local/tea/tea-{{ gitea_cli_version }}-linux-amd64"
            dest: "~/.local/bin/tea"
            mode: 0755

      - name: "Test Github CLI login state"
        ansible.builtin.shell: |
              export PATH="~/.local/bin:$PATH"
              gh auth status || (echo -e "ERROR: Missing API login! Please run:\ngh auth login --hostname {{ github_cli_main_host }}"; exit 4)
        args:
            executable: /bin/bash

      - name: "Test Gitea/Codeberg CLI login state"
        ansible.builtin.shell: |
              export PATH="~/.local/bin:$PATH"
              tea login ls --output json | jq -r .[].name | grep -E "{{ git_axpos_org_private_login }}$" \
                  || (echo -e "ERROR: Missing API login! Please run:\ntea login add --name {{ git_axpos_org_private_login }} --url {{ git_axpos_org_private_host }}"; exit 4)
              {% if git_axpos_org_public_login is defined %}
              tea login ls --output yaml | jq -r .[].name | grep "{{ git_axpos_org_public_login }}" \
                  || (echo -e "ERROR: Missing API login! Please run:\ntea login add --name {{ git_axpos_org_public_login }} --url {{ git_axpos_org_public_host }}"; exit 4)
              {% endif %}
        args:
            executable: /bin/bash

- name: "Detect support level"
  set_fact:
    detected_support_level: "{{ vars['hugo_supportlevel_' ~ (axp_type | lower)] | d(hugo_supportlevel) }}"

- name: debug
  debug:
    var: detected_support_level
- fail:
    msg: boo

- name: "Community device check"
  when: detected_support_level == 'community'
  block:

    - name: "Check for a community test issue"
      ansible.builtin.uri:
        url: "{{ axp_community_tracker_fetchlabel_uri }}"
        method: GET
        headers:
          Accept: application/json
        return_content: true
      register: api_response

    - name: "Set axp_community_tracker_id if there is a matching label"
      ansible.builtin.set_fact:
        axp_community_tracker_id: >-
          {{
            (
              (api_response.json | default([]) | length == 1) and
              (
                (api_response.json | first).labels
                | selectattr('name', 'equalto', 'build/' ~ build_id)
                | list
                | length == 1
              )
            )
            | ternary((api_response.json | first).number, '')
          }}
