---

- name: "Set CVE tag"
  ansible.builtin.set_fact:
    cve_tag_auto: "{{ sec_patch_date_last | int - 1 }}"

- name: "Setup CVE kernel patcher"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    CROOT="{{ SRCPATH }}"
    set +e
    cd $CROOT

    echo "DOS_BINARY_PATCHER: $DOS_BINARY_PATCHER" | tee -a {{ BUILD_LOG }}
    echo "DOS_PATCHES_LINUX_CVES: $DOS_PATCHES_LINUX_CVES" | tee -a {{ BUILD_LOG }}
    echo "DOS_PATCHER_LOOSE_VERSIONS: $DOS_PATCHER_LOOSE_VERSIONS" | tee -a {{ BUILD_LOG }}
    echo "DOS_PATCHER_LOOSE_VERSIONS_EXTREME: $DOS_PATCHER_LOOSE_VERSIONS_EXTREME" | tee -a {{ BUILD_LOG }}

    # checkout sec patch date - if avail
    cd $DOS_PATCHES_LINUX_CVES
    git fetch --tags >> {{ BUILD_LOG }} 2>&1
    git checkout {{ cve_tag | d(cve_tag_auto) | regex_replace('(^.{4})(.{2})','\1-\2-AOS') }} >> {{ BUILD_LOG }} 2>&1 || true 
    git status >> {{ BUILD_LOG }} 2>&1
    cd $CROOT
    
    startPatcher {{ target_kernel_dir | regex_replace('/','_') }} >> {{ BUILD_LOG }} 2>&1    
  args:
    executable: /bin/bash

- name: "Setup CVE kernel patcher: reset (<A14)"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    {{ repo_bin }} forall -j{{ max_processes }} {{ target_kernel_dir }} -c "git am --abort; git rebase --abort; git add -A; git reset --hard FETCH_HEAD" >> {{ BUILD_LOG }} 2>&1 
  args:
    executable: /bin/bash
  when:
    - android_version_int | int < 14

- name: "Setup CVE kernel patcher: reset (>A14)"
  ansible.builtin.shell: |
    {{ DOS_INIT }}

    {% if pixel_kernel_gki | bool %}
    cd {{ git_pixel_kernel_source }}
    {% else %}
    cd {{ target_kernel_dir }}
    {% endif %}
    
    if [ -f .defconf.patched ];then rm -v .defconf.patched;fi
    (git am --abort; git rebase --abort; git add -A; git reset --hard FETCH_HEAD) >> {{ BUILD_LOG }} 2>&1 || true   
  args:
    executable: /bin/bash
  when:
    - android_version_int | int > 14

# fixes:
# Symbols missing from the ksymtab:
#  mctrl_gpio_disable_ms
- name: "g201 fixup (mctrl_gpio_disable_ms)"
  ansible.builtin.lineinfile:
    path: "{{ git_pixel_kernel_source }}/android/abi_gki_aarch64_imx"
    regexp: '^\s+mctrl_gpio_disable_ms$'
    state: absent
  when: pixel_kernel_gki | bool

- name: "new CVE exclusion approach"
  when: target_kernel_dir == "kernel/google/gs201/private/gs-google" or target_model == "blueline"
  block:

    - name: "Clean CVE exclusion lists"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ BUILDHOME }}/.cve_excludes.{{ target_model }}"
        - "{{ BUILDHOME }}/.cve_excludes.common"

    - name: "Setup CVE exclusion list (device)"
      ansible.builtin.template:
        src: "cve_excludes/{{ target_kernel_dir | regex_replace('/','_') }}.j2"
        dest: "{{ BUILDHOME }}/.cve_excludes.{{ target_model }}"

    - name: "Setup CVE exclusion list (common)"
      ansible.builtin.template:
        src: "cve_excludes/common.j2"
        dest: "{{ BUILDHOME }}/.cve_excludes.common"

- name: "Setup CVE kernel patcher: fixups"
  ansible.builtin.shell: |
    {{ DOS_INIT }}

    if [ -f "{{ BUILDHOME }}/.cve_excludes.{{ target_model }}" ];then
      echo "ANSIBLE CVE excludes!" | tee -a {{ BUILD_LOG }} 
      cd {{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/CVE_Patchers \
        && source {{ BUILDHOME }}/.cve_excludes.common >> {{ BUILD_LOG }} 2>&1 \
        && commentPatchesFromFile {{ BUILDHOME }}/.cve_excludes.{{ target_model }} android_{{ target_kernel_dir | regex_replace('/','_') }}.sh >> {{ BUILD_LOG }} 2>&1
    else
      echo "LEGACY CVE excludes" | tee -a {{ BUILD_LOG }}
      cd {{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/CVE_Patchers \
        && bash {{ DOSPATH }}/Scripts/Common/Fix_CVE_Patchers.sh >> {{ BUILD_LOG }} 2>&1
    fi

    echo "Setup CVE kernel patcher FINISHED" >> {{ BUILD_LOG }}
    
  args:
    executable: /bin/bash
  
