---

- name: "Set CVE tag"
  ansible.builtin.set_fact:
    cve_tag: "{{ sec_patch_date_last | int - 1 }}"

- name: "Setup CVE kernel patcher"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    CROOT="{{ SRCPATH }}"
    set +e
    cd $CROOT

    echo "DOS_BINARY_PATCHER: $DOS_BINARY_PATCHER" | tee -a {{ BUILD_LOG }}
    echo "DOS_PATCHES_LINUX_CVES: $DOS_PATCHES_LINUX_CVES" | tee -a {{ BUILD_LOG }}
    echo "DOS_PATCHER_LOOSE_VERSIONS: $DOS_PATCHER_LOOSE_VERSIONS" | tee -a {{ BUILD_LOG }}
    echo "DOS_PATCHER_LOOSE_VERSIONS_EXTREME: $DOS_PATCHER_LOOSE_VERSIONS_EXTREME" | tee -a {{ BUILD_LOG }}

    # checkout sec patch date - if avail
    cd $DOS_PATCHES_LINUX_CVES
    git fetch --tags >> {{ BUILD_LOG }} 2>&1
    git checkout {{ cve_tag | regex_replace('(^.{4})(.{2})','\1-\2-AOS') }} >> {{ BUILD_LOG }} 2>&1 || true 
    git status >> {{ BUILD_LOG }} 2>&1
    cd $CROOT
    
    startPatcher {{ target_kernel_dir | regex_replace('/','_') }} >> {{ BUILD_LOG }} 2>&1    
  args:
    executable: /bin/bash

- name: "Setup CVE kernel patcher: reset (<A14)"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    {{ repo_bin }} forall -j{{ max_processes }} {{ target_kernel_dir }} -c "git am --abort; git rebase --abort; git add -A; git reset --hard FETCH_HEAD" >> {{ BUILD_LOG }} 2>&1 
  args:
    executable: /bin/bash
  when:
    - android_version_int | int < 14

- name: "Setup CVE kernel patcher: reset (>A14)"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    cd {{ git_pixel_kernel_source | d(target_kernel_dir) }}
    (git am --abort; git rebase --abort; git add -A; git reset --hard FETCH_HEAD) >> {{ BUILD_LOG }} 2>&1 || true   
  args:
    executable: /bin/bash
  when:
    - android_version_int | int > 14

# fixes:
# Symbols missing from the ksymtab:
#  mctrl_gpio_disable_ms
- name: "g201 fixup (mctrl_gpio_disable_ms)"
  ansible.builtin.lineinfile:
    path: "{{ git_pixel_kernel_source }}/android/abi_gki_aarch64_imx"
    regexp: '^\s+mctrl_gpio_disable_ms$'
    state: absent
  when:
    - git_pixel_kernel_manifest_branch is defined
    - target_model_vendor == "Google"
    - android_version_int | int > 14

- name: "Setup CVE kernel patcher: fixups"
  ansible.builtin.shell: |
    {{ DOS_INIT }}

    cd {{ DOSPATH }}/Scripts/LineageOS-{{ los_version }}/CVE_Patchers \
      && bash {{ DOSPATH }}/Scripts/Common/Fix_CVE_Patchers.sh >> {{ BUILD_LOG }} 2>&1

    echo "Setup CVE kernel patcher FINISHED" >> {{ BUILD_LOG }}
    
  args:
    executable: /bin/bash
  
