---

- name: "Ensure the defined sources paths exist"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ SRCPATH }}"
    - "{{ DOSPATH }}"

- name: Copy DOS renamer
  copy:
    src: rename
    dest: "{{ SRCPATH }}/"
    mode: 0755

- block:

    - name: "grab DOS CVE Checker"
      ansible.builtin.get_url:
        url: "{{ divest_cve_checker_download }}"
        dest: "{{ divest_cve_checker_jar }}"
        mode: 0640
    
    - name: "Upload extend-DOS patches"
      copy:
        src: "extend_dos/{{ item }}"
        dest: "{{ item }}"
        mode: 0640
      loop:
        - cve_fixup.patch
        - getDefconfig.patch

  when: divest_unsupported_device
