---

# we do not use .divested.vars anymore as this causes trouble when
# dev the same time at the same system
- name: "Add device vars"
  ansible.builtin.template:
    src: "axp.vars.j2"
    dest: "{{ BUILDHOME }}/.divested.vars.{{ target_model }}-{{ android_shortversion }}-{{ axp_type | upper() }}"

- name: "Set device vars link (sub_model)"
  ansible.builtin.file:
    src: "{{ BUILDHOME }}/.divested.vars.{{ target_model }}"
    dest: "{{ BUILDHOME }}/.divested.vars.{{ sub_model }}-{{ android_shortversion }}-{{ axp_type | upper() }}"
    force: true
    state: link
  when: sub_model is defined and sub_model != ""

- block:
    - name: "Add global override vars (slim)"
      ansible.builtin.template:
        src: "axpslim.vars.j2"
        dest: "{{ BUILDHOME }}/.divested.vars.slim"

    - name: "Include slim vars overrides"
      ansible.builtin.lineinfile:
        path: "{{ BUILDHOME }}/.divested.vars.{{ target_model }}-{{ android_shortversion }}-{{ axp_type | upper() }}"
        line: "source {{ BUILDHOME }}/.divested.vars.slim"
        insertafter: EOF
        state: present

  when:
    - axp_type | d('') == "slim"

- name: "Set remote path (recovery only)"
  set_fact:
    rempath: "{{ rempath + '/recovery' }}"
  when: axp_build_recovery_only is defined and axp_build_recovery_only
