---

- name: "Apply Sync fixup (17.1)"
  when: android_version_int | int == 10
  block:

    - name: "Revert repopick move"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        cd {{ SRCPATH }}/vendor/lineage
        git revert e85694867b50377d7cfc82edd7417dde0b5ac386 04553ee1e0865dab7cd0df0368f99cb0497447e7 # we remove lineage/scripts, so this breaks repopick

    - name: "Fix syntax issue in repopick"
      ansible.builtin.lineinfile:
        path: "{{ SRCPATH }}/vendor/lineage/build/tools/repopick.py"
        regexp: '(\s+local_branches = re.split\()(.*)'
        line: '\1r\2'
        backrefs: yes

- name: "Revert repopick move (18.1)"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      cd {{ SRCPATH }}/vendor/lineage
      git revert 9acedc7d0e3866d90911a0112074fc312ca11ed5 3bea2ad4b3bf583840226eff100d77ebf2b674b3 # we remove lineage/scripts, so this breaks repopick
  when: android_version_int | int == 11
