---

- block:

    - name: "Google Pixel: prepare kernel manifest"
      ansible.builtin.file:
          path: "{{ item }}"
          state: directory
      loop:
          - "{{ git_pixel_kernel_dir }}"
          - "{{ SRCPATH }}/{{ target_kernel_dir }}"

    - name: "Google Pixel: sync kernel manifest"
      ansible.builtin.shell: |
        # add unstaged changes
        cd {{ git_pixel_kernel_source }}
        CMT=0
        git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
        # check for uncommitted changes
        CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
        # stash anything if required
        if [ $CMT -eq 1 -o $CMTL -gt 0 ];then
            stashtag=$(date +%F_%s)
            git stash save before-sync-${stashtag} >> {{ BUILD_LOG }} 2>&1
            echo "[GIT] stashed DOS repo changes before-sync-${stashtag}" >> {{ BUILD_LOG }}
        fi
        cd {{ git_pixel_kernel_dir }}
        set -e

        {{ repo_bin }} init --repo-url="{{ repo_bin }}" {{ git_pixel_kernel_manifest }} -b {{ git_pixel_kernel_manifest_branch }} --submodules >> {{ BUILD_LOG }} 2>&1
        {{ repo_bin }} sync --jobs-checkout={{ max_processes }} --jobs-network={{ max_processes_sync }} {{ repo_sync_args }} --fetch-submodules >> {{ BUILD_LOG }} 2>&1
      args:
        chdir: "{{ git_pixel_kernel_dir }}"
        executable: /bin/bash

    - name: "Google Pixel: setup symlink to common kernel source"
      ansible.builtin.file:
          src: "{{ git_pixel_kernel_source }}"
          dest: "{{ SRCPATH }}/{{ target_kernel_dir }}"
          force: true
          state: link
  when:
    - git_pixel_kernel_manifest_branch is defined
    - git_pixel_kernel_source is defined
    - target_model_vendor == "Google"
    - android_version_int | int > 14

- name: "Sync AXP.OS main"
  ansible.builtin.shell: |
      git fetch --all
      # add unstaged changes
      CMT=0
      git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
      # check for uncommitted changes
      CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
      # stash anything if required
      if [ $CMT -eq 1 -o $CMTL -gt 0 ];then
          stashtag=$(date +%F_%s)
          git stash save before-sync-${stashtag} >> {{ BUILD_LOG }} 2>&1
          echo "[GIT] stashed DOS repo changes before-sync-${stashtag}" >> {{ BUILD_LOG }}
      fi
      git checkout {{ axp_main_branch | d('axp') }}
      git pull
      git lfs pull
      git log -1
  args:
    executable: /bin/bash
    chdir: "{{ DOSPATH }}"
#  no_log: "{{ debug_off | d(true) }}"

- name: "AXP.OS: Sync LineageOS base & local manifests"
  include_tasks: ../../../common/tasks/sync.yml

- name: "Google Pixel: Setup GrapheneOS link"
  ansible.builtin.shell: |
      KERN_REL_DIR=$(grep string_value "{{ SRCPATH }}/build/release/flag_values/{{ android_target_release }}/RELEASE_KERNEL_{{ target_model | upper() }}_DIR.textproto" | cut -d '"' -f2 | tr -d " " | tail -n1)
      echo "KERN_REL_DIR: >{{ SRCPATH }}/$KERN_REL_DIR<" >> {{ BUILD_LOG }}
      ln -vsf grapheneos "{{ SRCPATH }}/$KERN_REL_DIR"

      #FIXME: dirty hack as GOS does not contain a boot.img
      if [ ! -f "{{ SRCPATH }}/$KERN_REL_DIR/boot.img" ];then
          touch "{{ SRCPATH }}/$KERN_REL_DIR/boot.img"
      fi
  when:
    - git_pixel_kernel_manifest_branch is defined
    - kleaf_kernel_build | bool
    - pixel_kernel_gos | d(False) | bool

- name: "activate special recovery manifest if needed"
  ansible.builtin.shell: |
    mv -v {{ SRCPATH }}/.repo/local_manifests/recovery.xml.disabled {{ SRCPATH }}/.repo/local_manifests/recovery.xml
    {{ repo_bin }} sync --jobs-checkout={{ max_processes }} --jobs-network={{ max_processes_sync }} {{ repo_sync_args }} {{ target_kernel_dir }}
  args:
    chdir: "{{ SRCPATH }}"
  when:
    - axp_build_recovery_only is defined and axp_build_recovery_only
    - target_model == "j5y17lte"

