---

- name: "Remove AudioFX app"
  ansible.builtin.shell: >
    awk -i inplace '!/AudioFX/' vendor/lineage/config/*.mk
  args:
    chdir: "{{ SRCPATH }}"

- name: "Fix missing import VisibleForTesting"
  ansible.builtin.shell: |
    PREQ=0
    grep -q 'import androidx.annotation.VisibleForTesting' src/com/android/settings/accounts/AccountTypePreferenceLoader.java || PREQ=1
    if [ $PREQ -eq 1 ];then
        echo "adding import androidx.annotation.VisibleForTesting"
        awk '
        /import / { last = NR; lines[NR] = $0 }
        { lines[NR] = $0 }
        END {
            for (i = 1; i <= NR; i++) {
                print lines[i]
                if (i == last) {
                    print "import androidx.annotation.VisibleForTesting;"
                }
            }
        }' src/com/android/settings/accounts/AccountTypePreferenceLoader.java > src/com/android/settings/accounts/AccountTypePreferenceLoader.java.temp \
          && mv src/com/android/settings/accounts/AccountTypePreferenceLoader.java.temp src/com/android/settings/accounts/AccountTypePreferenceLoader.java
        git add src/com/android/settings/accounts/AccountTypePreferenceLoader.java
        git commit {{ git_commit_args | d('') }} -m "fix missing import VisibleForTesting"
    fi
  args:
    chdir: "{{ SRCPATH }}/packages/apps/Settings"
    executable: /bin/bash
