---

- name: "Remove AudioFX app"
  ansible.builtin.shell: >
    awk -i inplace '!/AudioFX/' vendor/lineage/config/*.mk
  args:
    chdir: "{{ SRCPATH }}"

- name: "Apply vendor_axp patches"
  ansible.builtin.shell: |
      {{ DOS_INIT }}
      cd {{ item.path }} && patch -r - --no-backup-if-mismatch --forward --ignore-whitespace --verbose -p1 < {{ item.patch }}
  args:
    executable: /bin/bash
    chdir: "{{ SRCPATH }}"
  loop:
    - path: packages/apps/Settings
      patch: "{{ SRCPATH }}/vendor/axp/patches/common/a10/0002_packages_apps_Settings_src_com_android_settings_accounts_AccountTypePreferenceLoader_java.patch"
