---

- name: "Get signatures"
  ansible.builtin.git:
    repo: "{{ hypatia_uri_amnestytech }}"
    dest: "{{ hypatia_signatures_path }}/amnestytech"
    force: true
  timeout: 180

- name: "Parse signatures"
  ansible.builtin.shell: |
    for sha in $(find . -type f -name sha256.txt);do
       cat $sha >> {{ hypatia_signatures_path }}/raw/amnestytech.sha256
       echo >> {{ hypatia_signatures_path }}/raw/amnestytech.sha256
    done
    for hsb in $(find . -type f -name sha256.csv);do
       sed 's/,/:0:/g' $hsb | grep -vi sha256 >> {{ hypatia_signatures_path }}/raw/amnestytech.hsb
       echo >> {{ hypatia_signatures_path }}/raw/amnestytech.hsb
    done
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}/amnestytech"
