---

- name: "Delete any old tmp"
  ansible.builtin.file:
    path: "{{ hypatia_clam_tmp }}"
    state: absent

- name: "Create tmp"
  ansible.builtin.file:
    path: "{{ hypatia_clam_tmp }}"
    state: directory

- name: "Copy clam db to tmp"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ hypatia_path_clamav }}/{{ item }}"
    dest: "{{ hypatia_clam_tmp }}/"
  loop:
    - main.c*d
    - daily.c*d
