---

- name: "Delete any old tmp"
  ansible.builtin.file:
    path: "{{ hypatia_clam_tmp }}"
    state: absent

- name: "Create tmp"
  ansible.builtin.file:
    path: "{{ hypatia_clam_tmp }}"
    state: directory

- name: "Copy clam db to tmp"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ hypatia_path_clamav }}/{{ item }}"
    dest: "{{ hypatia_clam_tmp }}/"
  loop:
    - main.c*d
    - daily.c*d

- name: "Sign database"
  debug:
    msg: tbd

- name: "Copy to raw"
  ansible.builtin.shell: |
    mv {{ hypatia_clam_tmp }}/*.fp* "$origDir/exclusions/"
    mv {{ hypatia_clam_tmp }}/*.hsb "$origDir/raw/"
    mv {{ hypatia_clam_tmp }}/*.hdb "$origDir/raw/"
    mv {{ hypatia_clam_tmp }}/*.hdu "$origDir/raw/"
    mv {{ hypatia_clam_tmp }}/*.hsu "$origDir/raw/"
    
