---

- name: "Get & parse signatures"
  ansible.builtin.shell: |
    wget "https://api.cybercure.ai/feed/get_hash?type=csv" -O - | sed 's/,/\n/g' >> {{ hypatia_signatures_path }}/raw/cybercure.md5
    sort -u -o {{ hypatia_signatures_path }}/raw/cybercure.md5 {{ hypatia_signatures_path }}/raw/cybercure.md5
  args:
    chdir: "{{ hypatia_signatures_path }}"
