---

- name: "Get signatures"
  ansible.builtin.git:
    repo: "{{ hypatia_uri_eset }}"
    dest: "{{ hypatia_signatures_path }}/eset"
    force: true
  timeout: 180

- name: "Parse signatures"
  ansible.builtin.shell: |
    processHashes() {
        local name=$(basename $1)
        if [ -f $1/samples.$2 ]; then
                dos2unix $1/samples.$2
                while IFS= read -r line; do
                    echo "$line" >> {{ hypatia_signatures_path }}/raw/eset.$2
                done < "$1/samples.$2"
        fi
    }
    export -f processHashes
    find . -maxdepth 2 -mindepth 1 -type d -exec bash -c 'processHashes "{}" md5 hdb' \;
    find . -maxdepth 2 -mindepth 1 -type d -exec bash -c 'processHashes "{}" sha1 hsb' \;
    find . -maxdepth 2 -mindepth 1 -type d -exec bash -c 'processHashes "{}" sha256 hsb' \;
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}/eset"
