---

- name: "Prep sig path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/malicious-hash"
    state: directory
    mode: 0700

- name: "Get signatures"
  ansible.builtin.get_url:
    url: "{{ hypatia_uri_malicioushash_base }}{{ item }}-aa.txt"
    dest: "{{ hypatia_signatures_path }}/raw/malicious-hash.{{ item }}"
    mode: 0400
  loop:
    - md5
    - sha1
    - sha256
  
