---

- name: "Clean db raw path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/raw"
    state: absent
    
- name: "Prep db path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}"
    state: directory
    mode: 0700

- name: "Prep work paths"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ hypatia_www_user }}"
  loop:
    - raw
    - production
    - exclusions
