---

- name: "Prep sig path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/threatfox"
    state: directory
    mode: 0700

- name: "Get signatures"
  ansible.builtin.shell: |
    wget "{{ hypatia_uri_threatfox }}" -O archive.zip  
  args:
    chdir: "{{ hypatia_signatures_path }}/threatfox"

- name: "Parse signatures"
  ansible.builtin.shell: |
    unzip archive.zip
    tail -n +10 full_sha256.csv | awk '{ print $4 } ' | sed 's/^"//' | sed 's/",$//' > {{ hypatia_signatures_path }}/raw/threatfox.sha256
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}/threatfox"
