---

- name: "Prep sig path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/threatfox"
    state: directory
    mode: 0700

- name: "Get signatures"
  ansible.builtin.shell: |
    wget -q "{{ hypatia_uri_threatfox }}" -O archive.zip  2>> /dev/null
  args:
    chdir: "{{ hypatia_signatures_path }}/threatfox"

- name: "Parse signatures"
  ansible.builtin.shell: |
    unzip -o archive.zip
    tail -n +10 full_sha256.csv | grep -v entries: | awk '{ print $4 } ' | sed 's/^"//' | sed 's/",$//' > {{ hypatia_signatures_path }}/threatfox/threatfox.sha256
#    grep -v entries: {{ hypatia_signatures_path }}/threatfox/threatfox.sha256 > {{ hypatia_signatures_path }}/raw/threatfox.sha256
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}/threatfox"
