---

- name: "Get signatures"
  ansible.builtin.get_url:
    url: "{{ hypatia_uri_virusshare_base }}{{ item}}"
    dest: "{{ hypatia_signatures_path }}/virusshare_subset/virusshare_{{ item }}.md5"
    mode: 0400
  loop: "{{ range(465, 488) | list }}"

- name: "Parse signatures"
  ansible.builtin.shell: |
    echo
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}/"
