---

- name: "Get signatures"
  ansible.builtin.git:
    repo: "{{ hypatia_uri_zimperium }}"
    dest: "{{ hypatia_signatures_path }}/zimperium"
    force: true
  timeout: 180

- name: "Parse signatures"
  ansible.builtin.shell: |
    find . -type f -name 
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}/zimperium"
