---

- name: "Switch kernel to new Major Release"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    upstream_branch="{{ axp_switchMR_upstream_branch }}"
    axp_release="{{ axp_switchMR_target_branch }}"
    reponame=android_{{ target_kernel_dir | regex_replace('/','_') }} 
    push_req=0
    create_req=0

    if [ -d /tmp/kernel ]; then rm -r /tmp/kernel; fi
    git clone {{ axp_git_org }}/$reponame /tmp/kernel || create_req=1

    if [ $create_req -eq 1 ];then
      echo "[GIT] repo does not exist within the org yet! Creating $reponame ..." >> {{ BUILD_LOG }}
      git clone --mirror https://github.com/LineageOS/$reponame /tmp/kernel
      cd /tmp/kernel
      gh repo create AXP-OS/${reponame} --public --source=. --remote=up --disable-issues --disable-wiki --team bots --description "forked from: https://github.com/LineageOS/$reponame"
      gh api -X PUT "/orgs/AXP-OS/teams/bots/repos/AXP-OS/${reponame}" -f 'permission=maintain'
      git remote set-url origin {{ axp_git_org }}/$reponame.git
      git push --mirror
    else
      cd /tmp/kernel
      git remote add los https://github.com/LineageOS/$reponame
    fi

    if [ ! -f .github/workflows/sync.yml ];then
      mkdir -p .github/workflows/ || true

      git fetch los $upstream_branch
      git checkout los/$upstream_branch
      git checkout origin/$axp_release || git checkout -b $axp_release
      
    {% raw %}
      cat <<EOSYNC > .github/workflows/sync.yml
      name: "Sync"

      on:
        workflow_dispatch:
        schedule:
          - cron: "$(( RANDOM % 60 )) $(( RANDOM % 24 )) * * *"

      # Sets permissions of the GITHUB_TOKEN to allow pushing via github token
      permissions:
        contents: write

      jobs:
        sync-upstream:
          name: "Sync with upstream"
          uses: AXP-OS/.github/.github/workflows/sync_upstream.yml@main
          with:
              remote-repo: LineageOS/\${{ github.event.repository.name }}
              remote-branch: $upstream_branch
              local-repo: \${{ github.repository_owner }}/\${{ github.event.repository.name }}
              local-branch: "$(git branch --no-color --show-current)"
              dryrun: false
          secrets: inherit
    EOSYNC
    {% endraw %}
      CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
      if [ $CMTL -gt 0 ];then
          git add -f .github/ >> {{ BUILD_LOG }} 2>&1 || CMT=1
          git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "ci: enable upstream sync"
          push_req=$(( push_req + 1))
      fi
    else
      echo "Skipped adding CI/CD sync to device tree!"
    fi

    if [ "$push_req" -gt 0 ];then
      git push origin $axp_release
    else
      echo "Skipped pushing (no changes were made)."
    fi

    rm -r /tmp/kernel
  args:
    executable: /bin/bash
