---

- name: "Switch kernel to new Major Release"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    upstream_branch="{{ axp_switchMR_upstream_branch }}"
    axp_release="{{ axp_switchMR_target_branch }}"

    if [ -d /tmp/kernel ]; then rm -r /tmp/kernel; fi
    git clone {{ axp_git_org }}/android_{{ target_kernel_dir }} /tmp/kernel

    cd /tmp/kernel

    if [ ! -f .github/workflows/sync.yml ];then
      mkdir -p .github/workflows/ || true

      git remote add los https://github.com/LineageOS/android_kernel_google_msm-4.14
      git fetch los $upstream_branch
      git checkout los/$upstream_branch
      git checkout -b $axp_release
      
      {% raw %}
      cat <<EOSYNC > .github/workflows/sync.yml
      name: "Sync"

      on:
        workflow_dispatch:
        schedule:
          - cron: "$(( RANDOM % 60 )) $(( RANDOM % 24 )) * * *"

      # Sets permissions of the GITHUB_TOKEN to allow pushing via github token
      permissions:
        contents: write

      jobs:
        sync-upstream:
          name: "Sync with upstream"
          uses: AXP-OS/.github/.github/workflows/sync_upstream.yml@main
          with:
              remote-repo: LineageOS/\${{ github.event.repository.name }}
              remote-branch: $upstream_branch
              local-repo: \${{ github.repository_owner }}/\${{ github.event.repository.name }}
              local-branch: "$(git branch --no-color --show-current)"
              dryrun: false
          secrets: inherit
    EOSYNC
    {% endraw %}
      git add -f .github/
      git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "ci: enable upstream sync"
    else
      echo "Skipped adding CI/CD sync to device tree!"
    fi

    git push origin $axp_release

    rm -r /tmp/kernel
  args:
    executable: /bin/bash
