---

- name: "Switch device tree to new Major Release"
  ansible.builtin.shell: |
    {{ DOS_INIT }}
    upstream_branch="{{ axp_switchMR_upstream_branch }}"
    axp_release="{{ axp_switchMR_target_branch }}"
    push_req=0
    create_req=0

    if [ -d /tmp/cdevice ]; then rm -r /tmp/cdevice; fi

    if [[ "{{ device_tree }}" == *vendor_* ]]; then
        GHORG=TheMuppets
        reponame=proprietary_{{ device_tree }}
        private=1
    else
        GHORG=LineageOS
        reponame=android_{{ device_tree }}
        private=0
    fi
    
    git clone {{ axp_git_org }}/$reponame /tmp/cdevice >> {{ BUILD_LOG }} 2>&1 || create_req=1
    
    if [ $create_req -eq 1 ];then
      echo "[GIT] repo does not exist within the org yet! Creating $reponame ..." >> {{ BUILD_LOG }}
      if [ $private -eq 1 ];then
          git remote add up https://github.com/$GHORG/$reponame >> {{ BUILD_LOG }} 2>&1 && git fetch up && git checkout up/$upstream_branch >> {{ BUILD_LOG }} 2>&1)

          tea repos create --name ${reponame} --owner {{ git_axpos_org_name }} --description "forked from: $(git remote -v | head -n1 | cut -f2 | cut -d ' ' -f1)" --login {{ gitea_login_name }} >> {{ BUILD_LOG }} 2>&1
          echo "[GIT] repo created..." >> {{ BUILD_LOG }}
          for lf in $(find . -type f -size +2M -name '*.*'| while read file; do f="${file##*.}"; [ ${{ "{" }}{{ "#" }}f} -ge 2 ] && echo "$f" ; done | sort -u);do
            git lfs track \"*.${lf}\"
          done
          cat .gitattributes >> {{ BUILD_LOG }} || true
          git add -A .  >> /dev/null 2>> {{ BUILD_LOG }}
          git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: track files bigger than 2M"  >> /dev/null 2>> {{ BUILD_LOG }}
          git checkout $CURHASH >> /dev/null 2>> {{ BUILD_LOG }}
          for lf in $(find . -type f -size +2M -name '*.*'| while read file; do f="${file##*.}"; [ ${{ "{" }}{{ "#" }}f} -ge 2 ] && echo "$f" ; done | sort -u);do
            git lfs track \"*.${lf}\"
          done
          (git add -A .  >> /dev/null 2>> {{ BUILD_LOG }} &&
            git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: track files bigger than 2M"  >> /dev/null 2>> {{ BUILD_LOG }}) || true)
      else
          gh repo fork $GHORG/$reponame --org AXP-OS --clone=false >> {{ BUILD_LOG }} 2>&1
          # even though the command will wait until the fork is fully created give some extra time
          sleep 5

          # Set description, public, disable issues and wiki
          gh repo edit AXP-OS/${reponame} \
           --description "forked from: https://github.com/LineageOS/$reponame" \
           --accept-visibility-change-consequences \
           --visibility public >> {{ BUILD_LOG }} 2>&1
      
          # Assign team with push permission
          gh api -X PUT -H "Accept: application/vnd.github+json" \
           /orgs/AXP-OS/teams/bots/repos/AXP-OS/${reponame} \
           -f permission=maintain >> {{ BUILD_LOG }} 2>&1
      fi

      # finally clone the forked repo locally
      git clone {{ axp_git_org }}/$reponame /tmp/cdevice >> {{ BUILD_LOG }} 2>&1
      
      push_req=1
    fi

    cd /tmp/cdevice
    git checkout origin/$upstream_branch  >> {{ BUILD_LOG }} 2>&1 || (git remote add up https://github.com/$GHORG/$reponame >> {{ BUILD_LOG }} 2>&1 && git fetch up && git checkout up/$upstream_branch  >> {{ BUILD_LOG }} 2>&1)

    git remote add up https://github.com/$GHORG/android_{{ device_tree }} >> {{ BUILD_LOG }} 2>/dev/null || true
    git fetch up $upstream_branch >> {{ BUILD_LOG }} 2>&1
    git checkout up/$upstream_branch >> {{ BUILD_LOG }} 2>&1
    git checkout origin/$axp_release 2>/dev/null || git checkout -b $axp_release >> {{ BUILD_LOG }} 2>&1

    if [ "{{ target_model_common_tree }}" == "{{ device_tree }}" ];then
      grep -q "vendor/axp/config/common.mk" {{ target_model_device_tree_mk }} \
        || echo -e '\n# enable AXP.OS vendor\n$(call inherit-product, vendor/axp/config/common.mk)' >> {{ target_model_device_tree_mk }}
    
      grep -q "vendor/axp/BoardConfigVendor.mk" {{ target_model_device_tree_boardmk }} \
        || echo -e '\n# even though we include vendor/axp/config/common.mk we need to include AXPs own BoardConfig\n# (after the above definitions & includes), too so we we can make use of the conditions within\ninclude vendor/axp/BoardConfigVendor.mk' >> {{ target_model_device_tree_boardmk }}
    fi
    
    CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
    if [ $CMTL -gt 0 ];then
        git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
        git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "board/device: enable AXP.OS" >> {{ BUILD_LOG }} 2>&1
        push_req=$(( push_req + 1))
    fi

    if [ ! -f .github/workflows/sync.yml ];then
      mkdir -p .github/workflows/ 2>/dev/null || true
    {% raw %}
      cat <<EOSYNC > .github/workflows/sync.yml
      name: "Sync"

      on:
        workflow_dispatch:
        schedule:
          - cron: "$(( RANDOM % 60 )) $(( RANDOM % 24 )) * * *"

      # Sets permissions of the GITHUB_TOKEN to allow pushing via github token
      permissions:
        contents: write

      jobs:
        sync-upstream:
          name: "Sync with upstream"
          uses: AXP-OS/.github/.github/workflows/sync_upstream.yml@main
          with:
              remote-repo: $GHORG/\${{ github.event.repository.name }}
              remote-branch: $upstream_branch
              local-repo: \${{ github.repository_owner }}/\${{ github.event.repository.name }}
              local-branch: "$(git branch --no-color --show-current)"
              dryrun: false
          secrets: inherit
    EOSYNC
    {% endraw %}
      git add -f .github/ >> {{ BUILD_LOG }} 2>&1 || CMT=1
      CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
      if [ $CMTL -gt 0 ];then
          git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "ci: enable upstream sync" >> {{ BUILD_LOG }} 2>&1
          push_req=$(( push_req + 1))
      fi
    else
      echo "Skipped adding CI/CD sync to device tree!" >> {{ BUILD_LOG }} 2>&1
    fi

    if [ "$push_req" -gt 0 ];then
      git push origin $axp_release >> {{ BUILD_LOG }} 2>&1
      echo "[GIT] Pushed $reponame!" >> {{ BUILD_LOG }} 2>&1
      sleep 10
      gh repo edit AXP-OS/${reponame} --default-branch $axp_release >> {{ BUILD_LOG }} 2>&1
    else
      echo "Skipped pushing $reponame (no changes were made)."  >> {{ BUILD_LOG }} 2>&1
    fi
    
    rm -r /tmp/cdevice
  args:
    executable: /bin/bash
