---
# yamllint disable rule:comments
#################################################################################################################################
# source: https://github.com/sfX-android/automation_scripts/blob/ansible/roles/axp/common_init_device/vars/copytemplate.yml
# v2.1
#################################################################################################################################
#################################################################################################################################

#################################################################################################################################
## Device info
#

# human readable model name
target_model_vendor: "Google"
target_model_name: 'Pixel 7a'

# path to the kernel dir
# e.g. "kernel/oneplus/msm8998"
target_kernel_dir: "kernel/google/gs201/private/gs-google"

# git repo name of the device common tree
target_model_common_tree: "android_device_google_gs201"

# add OpenEUICC
axp_euicc_capable: true

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: true

# construct full model info
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# Pixel devices: KLEAF based kernel build
pixel_kernel_codename: raviole
git_pixel_kernel_manifest_branch: "15-qpr2"
pixel_kernel_buildresult: "device/google/{{ pixel_kernel_codename }}-kernels/6.1"

# construct specific model device tree automatically
target_model_device_tree: android_device_{{ target_model_vendor | lower() }}_{{ target_model | lower() }}

# boot debugger mount point
extendrom_debug_path_default: "/mnt/vendor/persist"

extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# git push project names related to this device. used for device init, reproducible builds, ci/cd
axp_git_push_device_include: "{{ target_model_device_tree }}|{{ target_model_common_tree }}"

# all used VENDOR paths for this device
axp_git_push_vendor_include: "{{ target_model_device_tree | replace('android_device_', 'proprietary_vendor_') }}"

# Bootloader ID (first line) for validating build log
axp_bootloader_id_pro: '45000208280357DD'
#axp_bootloader_id_slim: ''

#################################################################################################################################
## Website info
#

# COMMON block
hugo_firmware: "included"

# Is the device an A/B device (legacy or virtual)?
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'yes'

#hugo_xda_link: "" # link to the AXP.OS XDA post for that device
#hugo_kb_link: "" # OPTIONAL: knownissues link, only if there is any
#hugo_custom_installguide_path: "" # OPTIONAL: custom installation guide
hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=78"


#### PRO block ####
android_version_pro: 15
hugo_relockable_pro: 'yes'
hugo_encryption_pro: "FBEv2" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
hugo_axp_bootloader_id_pro: |-
    BOOTLOADER minimal ID
        45000208

    BOOTLOADER full ID:
        45000208280357DD
        B6431F978E828EF2
        2375BB6C69FB7342
        3E0D2082C239DA85
hugo_supportlevel_pro: "team"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "2024-06-20 (A13)<br/>TBD (A15)" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
#hugo_patchlevel_pro: ""

#### SLIM block ####
#android_version_slim: 
#hugo_relockable_slim: ''
#hugo_encryption_slim: "" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#hugo_axp_bootloader_id_slim: |- # if AVB: the bootloader id string (from build log)
#hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
#hugo_first_releasedate_slim: "TBD" # first public stable release date (YYYY-MM-DD)
#hugo_state_slim: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
#hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of:
#   "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel"
#hugo_patchlevel_slim: ""

#################################################################################################################################
## FIRMWARE info
#
# source: https://developers.google.com/android/ota#lynx

vendor_firmware_version: "lynx-ota-bp1a.250505.005.b1-db24813f" # filename without zip

# direct download link to the OTA zip of the vendor.
vendor_firmware_download_url: "https://dl.google.com/dl/android/aosp/{{ vendor_firmware_version }}.zip"
vendor_firmware_download_sha256: "db24813f3c561f792a19c4015dabe2220e8ee2497ee435f8e6ace7a0a229f815"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_firmware_version }}.zip"
#################################################################################################################################

#################################################################################################################################
## FACTORY info (only relevant for: Google Pixel, Fairphone)
#
# source: https://developers.google.com/android/images#lynx

vendor_factory_id: "bp1a.250505.005.b1"  # e.g. tq3a.230805.001.s1
vendor_factory_hash: "45a1393f"  # e.g. 82902ea9
vendor_factory_download_sha256: "45a1393fe222246fd7b2918e072b52c6e34a4048fcf3f6b8c840632b1acd128b"

vendor_factory_version: "{{ target_model }}-{{ vendor_factory_id }}-factory-{{ vendor_factory_hash }}"
vendor_factory_download_url: "https://dl.google.com/dl/android/aosp/{{ vendor_factory_version }}.zip"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_factory_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_factory_version }}.zip"
#################################################################################################################################
