---

- name: "hagezi: get blocklists"
  ansible.builtin.get_url:
    url: "{{ item.uri }}"
    dest: "{{ hypatia_signatures_path }}/blocklist-various/{{ item.dest }}"
  timeout: 180
  loop:
    - uri: "{{ hypatia_uri_hagezi_fakes }}"
      dest: blocklist-hagezi-fakes.txt
    - uri: "{{ hypatia_uri_hagezi_threats }}"
      dest: blocklist-hagezi-threats.txt
    - uri: "{{ hypatia_uri_hagezi_multipro }}"
      dest: blocklist-hagezi-multipro.txt

