---

- name: "Prep html files"
  ansible.builtin.template:
    src: "{{ item.tmpl }}"
    dest: "{{ item.target }}"
    mode: 0400
    owner: "{{ hypatia_www_user }}"
  loop:
    - tmpl: index.j2
      target: "{{ hypatia_index_html }}"
    - tmpl: extended.j2
      target: "{{ hypatia_extended_html }}"

- name: "Convert databases"
  ansible.builtin.shell: |
    # malicious links
    cat {{ hypatia_signatures_path }}/blocklist-various/blocklist-*.txt > {{ hypatia_signatures_path }}/blocklist-various/blocklists.txt
    hagezi_fakes_file="{{ hypatia_signatures_path }}/blocklist-various/blocklist-hagezi-fakes.txt"
    hagezi_threats_file="{{ hypatia_signatures_path }}/blocklist-various/blocklist-hagezi-threats.txt"
    sed -i "s/%%HAGEZI_FAKES%%/$(wc -l $hagezi_fakes_file | cut -d ' ' -f1)/g" {{ hypatia_index_html }}
    sed -i "s/%%HAGEZI_THREATS%%/$(wc -l $hagezi_threats_file | cut -d ' ' -f1)/g" {{ hypatia_index_html }}

    # regular db
    echo "<pre>" >> {{ hypatia_index_html }}
    sed -i "s/%%DATE%%/$(date -u)/g" {{ hypatia_index_html }}
    java -jar {{ hypatia_path_converter }} raw/ {{ hypatia_signatures_path }}/blocklist-various/blocklists.txt >> {{ hypatia_index_html }}
    echo "</pre>" >> {{ hypatia_index_html }}
    mv raw/hypatia-*-bloom.bin production/
    
    # extended db
    echo "<pre>" >> {{ hypatia_extended_html }}
    sed -i "s/%%DATE%%/$(date -u)/g" {{ hypatia_extended_html }}
    java -jar {{ hypatia_path_converter }} raw-extended/ -extended >> {{ hypatia_extended_html }}
    echo "</pre>" >> {{ hypatia_extended_html }}
    cat {{ hypatia_extended_html }} >> {{ hypatia_index_html }}
    cd raw-extended/
    for db in $(find -type f -name 'hypatia-*-bloom.bin');do
      mv $db ../production/${db/bloom/extended\-bloom}
    done
    cd ..

    sed -s 'N;/md5: 0, sha1: 0, sha256: 0/!P;D' -i {{ hypatia_index_html }}
    
    # add virustotal links
    sed -E 's#(Skipping excluded hash: )(.*)#\1<a href="https://www.virustotal.com/gui/file/\2" target="_blank" rel="nofollow noopener noreferrer">\2</a>#g' -i {{ hypatia_index_html }}
  args:
    chdir: "{{ hypatia_signatures_path }}"
