---

- name: "Exclusions: F-Droid"
  ansible.builtin.get_url:
    url: "{{ hypatia_uri_exclude_fdroid }}"
    dest: "{{ hypatia_signatures_path }}/exclusions/fdroid.xml"
    mode: 0400
  register: get_exclude_fdroid

- name: "Exclusions: Parse F-Droid hashes"
  ansible.builtin.shell: |
    grep sha256 {{ hypatia_signatures_path }}/exclusions/fdroid.xml | sed -e 's/.*<hash type="sha256">//' -e 's/<\/hash>//' > fdroid- | sort -u  > {{ hypatia_signatures_path }}/exclusions/fdroid-sha256.hashes
  args:
    chdir: "{{ hypatia_signatures_path }}"
  when: hash_stat_dict.fdroid.isreg is not defined or get_exclude_fdroid.changed
