---

# sign databases
- include_tasks: sign.yml

- include_tasks: prep.yml

# static sources
# (rarely updated or not updated at all)
- include_tasks: avast.yml
- include_tasks: malware_hunter.yml
- include_tasks: targetedthreats.yml
- include_tasks: umair9747.yml

# dynamic sources
- include_tasks: amnestytech.yml
- include_tasks: clamav.yml
- include_tasks: cybercure.yml
- include_tasks: eset.yml
- include_tasks: malicious_hash.yml
- include_tasks: malware_bazaar.yml
- include_tasks: threatfox.yml
- include_tasks: threatview.yml
- include_tasks: sanesecurity.yml
- include_tasks: stalkerware.yml
- include_tasks: virusshare_subset.yml
#- include_tasks: zimperium.yml

# extended sources
#- include_tasks: virusshare_mantaray.yml

# blocklist sources
- include_tasks: blocklists.yml

# convert to common format
- include_tasks: convert.yml

# sign databases
- include_tasks: sign.yml
