---

- name: "Set default buildresult"
  ansible.builtin.shell: "false"
  register: buildresult
  ignore_errors: true
  changed_when: buildresult.rc == 1

- include_tasks: prep.yml

# static sources
# (rarely updated or not updated at all)
- include_tasks: selftest.yml
- include_tasks: hypatia_import.yml
- include_tasks: avast.yml
- include_tasks: malware_hunter.yml
- include_tasks: targetedthreats.yml
- include_tasks: umair9747.yml
# extended sources
#- include_tasks: virusshare_mantaray.yml

# dynamic sources
- include_tasks: amnestytech.yml
- include_tasks: clamav.yml
- include_tasks: cybercure.yml
- include_tasks: eset.yml
- include_tasks: malicious_hash.yml
- include_tasks: malshare.yml

# TEMP DEBUG
- include_tasks: convert.yml
- include_tasks: sign.yml
- include_tasks: activate.yml
- meta: end_play

- include_tasks: malware_bazaar.yml
- include_tasks: threatfox.yml
- include_tasks: threatview.yml
- include_tasks: sanesecurity.yml
- include_tasks: signaturebase.yml
- include_tasks: stalkerware.yml
- include_tasks: virusshare_subset.yml
- include_tasks: zimperium.yml

# blocklist sources
- include_tasks: blocklists.yml

# convert to common format
- include_tasks: convert.yml

# sign databases
- include_tasks: sign.yml

# activate new db
- include_tasks: activate.yml

- name: "Set buildresult"
  ansible.builtin.shell: "true"
  register: buildresult
  
