---

#- name: "Prep: clean db raw path"
#  ansible.builtin.file:
#    path: "{{ hypatia_signatures_path }}/raw"
#    state: absent
    
- name: "Prep: db path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}"
    state: directory
    mode: 0700

- name: "Prep: work paths"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ hypatia_www_user }}"
  loop:
    - raw
    - production
    - exclusions

- name: "Prep: download latest DB converter"
  ansible.builtin.get_url:
    url: "{{ hypatia_uri_converter }}"
    dest: "{{ hypatia_path_converter }}"
    mode: 0750
  retries: 10
  delay: 60

- name: "Prep: check static hash files"
  ansible.builtin.stat:
    path: "{{ item.file }}"
  loop:
    - { name: "avast", file: "{{ hypatia_signatures_path }}/raw/avast-covid19.sha256" }
    - { name: "umair", file: "{{ hypatia_signatures_path }}/raw/umair9747.md5" }
    - { name: "malwarehunt", file: "{{ hypatia_signatures_path }}/raw/malware-hunter.sha256" }
    - { name: "tthreads_hdb", file: "{{ hypatia_signatures_path }}/raw/targetedthreats.hdb" }
    - { name: "tthreads_hsb", file: "{{ hypatia_signatures_path }}/raw/targetedthreats.hsb" }
    - { name: "zimperium_md5", file: "{{ hypatia_signatures_path }}/raw/zimperium.md5" }
    - { name: "zimperium_sha256", file: "{{ hypatia_signatures_path }}/raw/zimperium.sha256" }
  register: hash_stat

- name: "Prep: build mapping of hash stats by name"    # requires Ansible 2.12
  ansible.builtin.set_fact:
    hash_stat_dict: >-
      {{
        hash_stat.results
        | items2dict(key_name='item.name', value_name='stat')
      }}
