---

- block:

   - name: Ensure gpg is installed
     ansible.builtin.package:
       name: gnupg
       state: present

   - name: "Sign all *.bin files in {{ sigdb_bin_path }}"
     ansible.builtin.shell: |
        export GPG_TTY=$(tty)
        find {{ sigdb_bin_path }} -type f -name '*.bin' -exec gpg --armor --detach-sig --output {}.sig --sign {} \;
     become: yes
     args:
       stdin: "{{ vault_lovelace_gpg_pass }}"
       executable: /bin/bash
     #loop: "{{ lookup('fileglob', sigdb_bin_path + '*.bin') }}"
 #gpg --armor --detach-sig --output {{ item }}.sig --sign {{ item }}

   - name: "Verify all signed *.bin files"
     ansible.builtin.shell: |
       gpg --verify {{ item }}.sig {{ item }}
     loop: "{{ lookup('fileglob', sigdb_bin_path + '*.bin') }}"
     become: yes
   
  delegate_to: lovelacedb
