---

- block:

   - name: Ensure gpg is installed
     ansible.builtin.package:
       name: gnupg
       state: present

   - name: "Sign all *.bin files in {{ sigdb_bin_path }}"
     ansible.builtin.shell: |
        #export GPG_TTY=$(tty)
        for db in $(find {{ sigdb_bin_path }} -type f -name '*.bin');do
            echo "signing $db"
            test -f ${db}.sig && rm ${db}.sig
            echo '{{ vault_lovelace_gpg_pass }}' | gpg --batch --pinentry-mode loopback --passphrase-fd 0 --detach-sig --output ${db}.sig --sign $db
         done
     become: yes
     no_log: true
     args:
       executable: /bin/bash

   - name: "Verify all signed *.bin files"
     ansible.builtin.shell: |
       for db in $(find {{ sigdb_bin_path }} -type f -name '*.bin');do
            echo "verifying $db"
            gpg --verify ${db}.sig $db
       done
     become: yes
     args:
       executable: /bin/bash
   
  delegate_to: lovelacedb
