---

- name: "VirusShare-Subset: Prep sig path"
  ansible.builtin.file:
    path: "{{ hypatia_signatures_path }}/virusshare_subset"
    state: directory
    mode: 0700

- name: "VirusShare-Subset: Check existence"
  ansible.builtin.stat:
    path: "{{ hypatia_signatures_path }}/virusshare_subset/virusshare_{{ item }}.md5"
  register: vs
  loop: "{{ virusshare_hash_range }}"
  
- name: "VirusShare-Subset: Get signatures"
  ansible.builtin.get_url:
    url: "{{ hypatia_uri_virusshare_base }}{{ item.item }}.md5"
    dest: "{{ hypatia_signatures_path }}/virusshare_subset/virusshare_{{ item.item }}.md5"
    mode: 0400
  loop: "{{ vs.results }}"
  when: not item.stat.exists

- name: "VirusShare-Subset: Copy signatures"
  ansible.builtin.shell: |
     cat {{ hypatia_signatures_path }}/virusshare_subset/virusshare_*.md5 > {{ hypatia_signatures_path }}/raw/virusshare.md5
  args:
    executable: /bin/bash
    chdir: "{{ hypatia_signatures_path }}"
