---
# misc common vars used for all tasks
# never overwrite anything here - use either semaphore to set an override
# or override a var in a specific device vars/main.yml

# fallback / legacy var
REPOBRANCH: undefined

# semaphore working/tmp dir
semaphore_work_dir: /opt/scs-work
semaphore_home_dir: "{{ semaphore_work_dir }}"
semaphore_lock_dir: "{{ semaphore_work_dir }}/run"
# ansible home dir / must match ansible.cfg
# overwrite in semaphore env/inventory if needed
ansible_home_dir: "{{ semaphore_work_dir }}"

# ensure we have a normalized & clean version tag (e.g. removing slashes from a git tag etc)
parsed_target_version: "{{ git_repo_main_branch | regex_replace('.*/','') | regex_replace('^v','') }}"
normalized_target_version: "{{ parsed_target_version | regex_replace('(\\d+)\\.(\\d+)(.*)','\\1.\\2') }}"
# just the integer of the given android version
android_version_int: "{{ android_shortversion | replace('a','') | replace('A','') }}"

# construct LOS version/git branch based on android version
los_version: "{{ android_shortversion | replace('a15','22.0') | replace('a14','21.0') | replace('a13','20.0') | replace('a12','19.1') | replace('a11','18.1') | replace('a10','17.1') | replace('a9','16.0') }}"
los_version_gitbranch: "lineage-{{ los_version }}"
android_version_letter: "{{ android_shortversion | replace('a15','V') | replace('a14','U') | replace('a13','T') | replace('a12','S') | replace('a11','R') | replace('a10','Q') | replace('a9','P') }}"

# normalize current date (used in several places later
current_year: "{{ ansible_date_time.year }}"
current_month: "{{ ansible_date_time.month }}"
current_day: "{{ ansible_date_time.day }}"

# build identifier used in e.g. the filename later
BUILDIDENT: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
sm_build_id: >-
    {% if semaphore_vars.task_details.target_version is undefined %}
    {{ semaphore_vars.task_details.incoming_version | d('0000') }}
    {% else %}
    {{ semaphore_vars.task_details.target_version }}
    {% endif %}
build_id: "{{ sm_build_id | regex_replace(' ','') }}"

# sync stuff
# full path to the repo binary
repo_bin: /home/androidsource/bin/repo
# number of threads used e.g. with repo binary etc
max_processes: 40
max_processes_sync: 6    # will set --jobs-network={{ max_processes_sync }} for repo sync, beware you can easily get throttled by Google or/and github/lab
# default args for the (rest of the) repo sync command
# can be overwritten e.g with a semaphore var
repo_sync_args: "--force-sync --force-remove-dirty --no-clone-bundle -c --fail-fast"

# ssh port where the release server is reachable (coming from the build server)
RELEASESVR_port: 22

# backwards compatible var specifying the build device (e.g. hotdog etc)
# should not be changed
BDEVICE: "{{ target_model }}"

# ccache defaults
USE_CCACHE: 1
CCACHE_EXEC: /usr/bin/ccache
CCACHE_COMPRESS: 1
CCACHE_DIR: "/ssd/ccache/jenkins/{{ android_shortversion }}"

# base url where the user can download released builds
leech_server: "https://leech.binbash.rocks:8008"
release_path_owner: www-data     # username which should be set on the remote download server path
release_path_group: www-data     # group name which should be set on the remote download server path
release_path_perms: 0755         # permissions to set on the release folder(s) on the remote download server

# notification icons
ICON_GOOD: 🎉
ICON_BAD: ☠️

# disable telegram notifications by default
telegram_notifications: false

# using a custom release script after build succeeded
custom_release_script: false

# build vars
BUILDHOME: /home/jenkins
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ android_shortversion }}/{{ target_model }}/"
zipdir_mntp: "/home/androidsource/ZIPs"
ZIPDIR: "{{ zipdir_mntp }}/{{ ROM_FLAVOR }}/zips/{{ target_model }}"
SRCPATH: "/home/aosp/{{ ROM_FLAVOR }}"
post_cleanup_product_dir: "{{ SRCPATH }}/out/target/product/{{ target_model }}"
#SEPARATE_OUT_DIR: "/ssd/{{ target_model }}/{{ ROM_FLAVOR }}-{{ android_shortversion }}/out"
manifest_paths_file: "/tmp/manifest_paths.{{ ROM_FLAVOR }}"
rempath_unstable: >-
    {{ rempath | regex_replace('(/' + ROM_FLAVOR + ')/.*', '\1-unstable/') }}
# will never delete anything within the following dir
# used e.g. for downloaded google's factory images
persistent_dir: "{{ zipdir_mntp }}/{{ ROM_FLAVOR }}/persistent/{{ target_model }}"
android_shortversion: NA

# AXP.OS only:
# if set to true (in your env or anywhere else) an -eng build will be created instead of a -user one
axp_build_eng: false

# build logging
build_log_name: "build_{{ target_model }}_{{ ROM_FLAVOR }}_{{ build_id }}.log"
build_log_name_noid: "build_{{ target_model }}_{{ ROM_FLAVOR }}"
BUILD_LOG: "{{ BUILDHOME }}/{{ build_log_name }}"
build_log_name_latest: "build_{{ target_model }}_{{ ROM_FLAVOR }}_latest.log"
BUILD_LOG_LATEST: "{{ BUILDHOME }}/{{ build_log_name_latest }}"
keep_build_logs: True    # if you override this in your env with >False< ANY previous build log will be deleted before building

# build signing
sign_build: true
# main base path for all key files (i.e. without model or OS flavor)
keys_base_path: /home/aosp/KEYS
keysdir: '{{ keys_base_path }}/{{ ROM_FLAVOR }}-{{ android_shortversion }}_{{ target_model }}'
SRC_KEYSDIR: user-keys    # the directory name in the TOP dir of the android sources expected by the build system
KEYS_CN: "{{ ROM_FLAVOR }}"
KEYS_USER: "sfX-bot"
KEYS_SIZE: 4096
KEYS_HASHTYPE: sha256

# skip generating a ZIP checksum
skip_gen_checksum: false

# set build defaults
debug_build: 'true'      # all build notifications will be send to a specified private channel (if notifications are enabled)
clean_basic: 'true'      # will delete the {{ZIPDIR}} content
clean_out: 'true'        # will delete the complete out/ directory, build props and images get deleted always! (see: roles/common/tasks/clean.yml)
clean_incompat: 'false'  # deletes cross-version incompatible REPO paths defined in {{incompat_cross_version_paths}}
reset_git: 'true'        # the whole android sources will be hard reset and re-synced
release_build: 'true'    # releases will be pushed to a specified OTA server
unstable_build: 'true'   # changes the scp target path (when {{release_build}} is true)
nolog_gitreset: 'true'   # disable the verbose logging for the git reset tasks
commit_push: False       # will push all source changes to specified git server
post_cleanup: 'false'    # will delete the output directory after a successful build if set to true

# set override defaults
override_clean_basic: 'undef'
override_clean_out: 'undef'
override_reset_git: 'undef'
override_release_build: 'undef'
override_sync: 'undef'
override_clean_incompat: 'undef'

# cross build: problematic repos paths
prob_repo_paths:
  - "barbet-sepolicy"
  - bootable_recovery

# cross build: problematic source paths
incompat_cross_version_paths:
    - bootable/recovery
    - device

# kernel patcher
divest_cve_checker_download: "https://codeberg.org/AXP-OS/cve_checker/releases/download/latest/cve_checker.jar"
divest_cve_checker_jar: "{{ BUILDHOME }}/cve_checker.jar"
skip_dl_cve_checker: False

# !LEGACY! security patch handling (and for PIE only)
# see next paragraph for the new method!
# ref: https://review.lineageos.org/q/topic:P_asb_2024-10
SECPATCH_DATE_PIE: "2024-12" # HAS TO be always the last available one!
sec_patch_topics_pie:
      - topic:P_asb_2022-05
      - topic:P_asb_2022-06
      - topic:P_asb_2022-07
      - topic:P_asb_2022-08
      - topic:P_asb_2022-09
      - topic:P_asb_2022-10
      - topic:P_asb_2022-11
      - topic:P_asb_2022-12
      - topic:P_asb_2023-01
      - topic:P_asb_2023-02
      - topic:P_asb_2023-03
      - topic:P_asb_2023-04
      - topic:P_asb_2023-05
      - topic:P_asb_2023-06
      - topic:P_asb_2023-07
      - topic:P_asb_2023-08
      - topic:P_asb_2023-09
      - topic:P_asb_2023-10
      - topic:P_asb_2023-11
      - topic:P_asb_2023-12
      - topic:P_asb_2024-01
      - topic:P_asb_2024-02
      - topic:P_asb_2024-03
      - topic:P_asb_2024-04
      - topic:P_asb_2024-05
      - topic:P_asb_2024-06
      - topic:P_asb_2024-07
      - topic:P_asb_2024-08
      - topic:P_asb_2024-09
      - topic:P_asb_2024-10
      - topic:P_asb_2024-11
      - topic:P_asb_{{ SECPATCH_DATE_PIE }}

##############################################################################################
##############################################################################################
# Android Security Bulletin (ASB) patching AREA - START
##############################################################################################
##############################################################################################
# new generic security patch handling based on LOS's gerrit topics
# it will use the Lineage OS branch which has been configured during an Ansible/Semaphore run
# and goes through the list of topics based on year and month.
# it will also use the right topic letter based on the same LineageOS branch configured
# so the only thing needed to be adjusted is the range of patches for your specific needs.

# manifest-requirement:
#     <!-- build tools -->
#     <project path="external/buildtools" name="sfX-Android/android_buildtools" remote="github" revision="main" />
#
# exclusion list:
#   338357: A9: manifest change
#   342095: A9: manifest change
#   324039: build conflict (eOS)
#   324040: build conflict (eOS)
#   324041: build conflict (eOS)
#   366137: affects Trebuchet (eOS)
#   377775: affects Trebuchet (eOS)
#   414554: A13: manifest change
#   359421: Traceur
#secpatch_common_exclusions: '-"Manifest change" -"Track our own fork" -"Bump Security String"'
secpatch_common_exclusions: '-"Bump Security String"'
#secpatch_los_exclusions: '338357|342095|414554'               # includes secpatch_common_exclusions
secpatch_los_exclusions: '359421'
secpatch_eos_exclusions: '324039|324040|324041|366137|377775' # includes secpatch_common_exclusions + secpatch_los_exclusions

# define known relation chains
secpatch_static_dependencies:Add commentMore actions
    - id: "365453"
      dep: "378097 365453"

# usually you should never need to change this! See above how it is generated:
sec_patch_pick_branch: "{{ los_version_gitbranch }}"

# to identify a start for the ranges check:
#     https://github.com/LineageOS/android_build/blob/lineage-17.1/core/version_defaults.mk
# (change it to your used Lineage OS branch!)
# search for 'PLATFORM_SECURITY_PATCH :=' and use the next one

# the last patch topic available
# ranges will not include the last match so must be 1 higher
# (to include December it must end with "13" in order to match the 12th month as well)
# overwrite this in the Semaphore environment or pass as extra var during the Ansible run
# format: "YYYYMM" and NOT(!) as a string
# ensure we always get a 2 digit month and plus 1 it for range()
#sec_month: "{{ '%02d' | format((current_month | int) + 1) }}"
# set dynamic sec_patch_date_last:
#sec_patch_date_last: "{{ current_year }}{{ sec_month }}"
sec_patch_date_last: 202506

# either 01 or 05 according to if you patch the KERNEL as well (e.g. by roles/kernel_patcher)
# see https://source.android.com/docs/security/bulletin/2025-01-01#Common-questions-and-answers
sec_patch_level: '01'

# as start and end of security patches is something you MIGHT need to decide depending on the used
# custom OS and/or version you should copy the whole next part into your OS role and adjust as needed.

##############################################################################################
# Note:
# ranges will not include the last match so it must be increased by 1
# e.g.:
# range(202205, 202212) will catch from May to November(!) 2022
# range(202205, 202213) will catch from May to December(!) 2022
##############################################################################################

##############################################################################################
# ASB patches for: Android 9 / P
# Last merged upstream (LOS): https://review.lineageos.org/q/topic:P_asb_2022-04
##############################################################################################
sec_patch_date_last_a9: "{{ sec_patch_date_last }}"
sec_patch_topics_a9:
    - "{{ range(202205, 202213) }}"
    - "{{ range(202301, 202313) }}"
    - "{{ range(202401, 202413) }}"
    - "{{ range(202501, sec_patch_date_last | int) }}"

##############################################################################################
# ASB patches for: Android 10 / Q
# Last merged upstream (LOS): https://review.lineageos.org/q/topic:Q_asb_2023-02
##############################################################################################
sec_patch_date_last_a10: "{{ sec_patch_date_last }}"
sec_patch_topics_a10:
    - "{{ range(202303, 202313) }}"
    - "{{ range(202401, 202413) }}"
    - "{{ range(202501, sec_patch_date_last | int) }}"

##############################################################################################
# ASB patches for: Android 11 / R
# Last merged upstream (LOS): https://review.lineageos.org/q/topic:R_asb_2024-02
##############################################################################################
sec_patch_date_last_a11: "{{ sec_patch_date_last }}"
sec_patch_topics_a11:
    - "{{ range(202403, 202413) }}"
    - "{{ range(202501, sec_patch_date_last | int) }}"

##############################################################################################
# ASB patches for: Android 12 / S
# Last merged upstream (LOS): https://review.lineageos.org/q/topic:S_asb_2025-03
##############################################################################################
sec_patch_date_last_a12: "{{ sec_patch_date_last }}"
sec_patch_topics_a12:
    - "{{ range(202504, sec_patch_date_last | int) }}"

##############################################################################################
# ASB patches for: Android 13 / T
# Last merged upstream (LOS): still supported (https://review.lineageos.org/q/topic:T_asb_2025-XX)
#
# A13 and later are still supported by LOS so when being being patient you get them
# automatically without doing anything once they are merged.
# if you can't wait, set sec_patch_unmerged: True (default now)
##############################################################################################
sec_patch_date_last_a13: "{{ sec_patch_date_last }}"
sec_patch_date_last_a14: "{{ sec_patch_date_last }}"
sec_patch_date_last_a15: "{{ sec_patch_date_last }}"
#sec_patch_date_last_a16: "{{ sec_patch_date_last }}"

##############################################################################################
# NOT-YET-MERGED ASB patches for any Android version
##############################################################################################
# sometimes merging patches upstream takes an unreasonable amount of time and so "hanging"
# in gerrit even though they are MAYBE(!) working just fine.
# By default we will ignore these "pending" patches for supported Android versions so you get
# them when MERGED only.
# This is the recommended behavior and should be changed only (e.g. in semaphore or vars)
# when you are totally aware of the risks and potential BREAKAGE which can occur then.
#
# That being said: for all Android versions NOT supported by LOS anymore
# you HAVE TO set this to True to get patches and the reason why this is the default here.
sec_patch_unmerged: True  # set to False in semaphore for not fetching unmerged patch topics

##############################################################################################
##############################################################################################
# Android Security Bulletin (ASB) patching AREA - END
##############################################################################################
##############################################################################################
