---

#################################################################################################################################
## Device info

# human readable model name
target_model_vendor: "Google" # e.g. OnePlus
target_model_name: 'Pixel 4a' # e.g. '5T', always ensure single quotes here

target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# path to the kernel dir
# e.g. "kernel/oneplus/msm8998"
target_kernel_dir: "kernel/google/msm-4.14"

pixel_kernel_gki: False

# path to the common tree, if none exists then the device tree.
# used e.g. for git, vendor/axp, release handling etc
target_model_common_tree: "device_google_sunfish" # e.g. device_oneplus_msm8998-common

target_model_device_tree: device_{{ target_model_vendor | lower() }}_{{ target_model_name | lower() }}

# the BoardConfig file within a device tree, required e.g. for switch_major_release
# usually is one of: BoardConfigCommon, BoardConfig, BoardConfigLineage.
# defaults to BoardConfigCommon
target_model_device_tree_boardmk: BoardConfigLineage.mk

# does the device support eSIMs (check e.g. here: https://esim.sm/en/compatible-devices)?
# If YES, then enable the following line:
extendrom_package_list: "{{ extendrom_package_list_default }} OpenEUICC_AXP-OS"

# boot debugger mount point
# path for boot_debug, must be identified within the device / common tree fstab:
# - must be a writable partition
# - must be a mountable partition (ext2, ext4, f2fs, ..)
# usually one of: /mnt/vendor/persist, /metadata or /cache
extendrom_debug_path_default: "/mnt/vendor/persist"

extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# git push project names related to this device. used for device init, reproducible builds, ci/cd
axp_git_push_device_include: "{{ target_model_device_tree }}|{{ target_model_common_tree }}"

# all used VENDOR paths for this device, e.g. "vendor_google_crosshatch|vendor_google_blueline"
axp_git_push_vendor_include: "vendor_google_sunfish"

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: '2357DB9EBF8090F9'
axp_bootloader_id_slim: 'B49112D3DD534A21'

#################################################################################################################################
## Website info

# COMMON block
# do we include vendor firmware?
# 1. open https://code.binbash.rocks/AXP.OS/vendor_firmware
# 2. select the correct `branch` _(must match the AXP.OS Android version, e.g. "axp-a15")_
# 3. click the folder with the `codename` for your device
# 4. If there is a folder with the device's codename (e.g. `enchilada`):
#   - check the file `AndroidBoardVendor.mk`: It should contain several `$(call add-radio-file.....` lines
# If steps 1-4 were successful set "included" otherwise "manual"
hugo_firmware: "included"

# Is the device an A/B device (legacy or virtual)?
# A/B? -> https://source.android.com/docs/core/ota/virtual_ab
# How to identify:
# - https://www.xda-developers.com/list-android-devices-seamless-updates/
# - General Rules:
#   Android 13+: (Virtual) A/B
#   Android 11+: A/B
#   Google Pixel: Every Google Pixel device ever released uses A/B partitions.
#   Samsung: not before 2024 and even then need to be verified
# - Manual Verification Method
#   adb shell getprop ro.boot.slot_suffix
#   -> if it returns _a or _b, it is an A/B device.
#   -> if it returns nothing, it is an A-only device.
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'yes'

hugo_xda_link: "https://xdaforums.com/t/rom-a13-official-microg-hardened-sunfish-axp-os-20.4651368/"
#hugo_kb_link:
#hugo_custom_installguide_path: "" # OPTIONAL: custom installation guide

# PRO block
android_version_pro: 15 # usually identical to android_shortversion at the top. just the number though: 9,10,11,13,15
# bootloader re-lock supported?
# if the device was supported by DivestOS you can check "Verified Boot" at https://divestos-archive.codeberg.page/page/devices.html
# can be: 'yes' or 'no', single quotes required
hugo_relockable_pro: 'yes'
hugo_encryption_pro: "FBEv1" # device encryption supported: no|FDE|FBEv1|FBEv2
hugo_axp_bootloader_id_pro: |-
  BOOTLOADER minimal ID
        2357DB9E

  BOOTLOADER full ID:
        2357DB9EBF8090F9
        908E9BBC0B353CC9
        CA11015AC588001D
        0AB9A80BD8AA5906
hugo_supportlevel_pro: "team"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "2024-01-16 (A13)<br/>TBD (A15)" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: "stable (A13)<br/>stable (A15)" # "stable" | "!! ALPHA !!" | "BETA"
#hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of:
#   "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel"
#hugo_patchlevel_pro: ""

# SLIM block
android_version_slim: 15 # usually identical to android_shortversion at the top. just the number though: 9,10,11,13,15
# bootloader re-lock supported?
# if the device was supported by DivestOS you can check "Verified Boot" at https://divestos-archive.codeberg.page/page/devices.html
# can be: 'yes' or 'no', single quotes required
hugo_relockable_slim: 'yes'
hugo_encryption_slim: "FBEv1" # device encryption supported: no|FDE|FBEv1|FBEv2
hugo_axp_bootloader_id_slim: |-
  BOOTLOADER minimal ID
          B49112D3
  
  BOOTLOADER full ID:
          B49112D3DD534A21
          AD3FC088B8977377
          4004899D7B181996
          15E6F074099EA3E0
hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
hugo_first_releasedate_slim: "2025-02-05 (A13)<br/>TBD (A15)" # first public stable release date (YYYY-MM-DD)
hugo_state_slim: "stable (A13)<br/>stable (A15)" # "stable" | "!! ALPHA !!" | "BETA"
#hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel" 
#hugo_patchlevel_slim: ""

#################################################################################################################################
## FIRMWARE info
##
# source: https://archive.org/details/sunfish-tq3a.230805.001.s1

vendor_firmware_version: "sunfish-ota-tq3a.230805.001.s1-965296b1" # filename without zip

# direct download link to the OTA/factory zip of the vendor.
vendor_firmware_download_url: "https://archive.org/download/sunfish-tq3a.230805.001.s1/sunfish-ota-tq3a.230805.001.s1-965296b1.zip"
vendor_firmware_download_sha512: "cbdf1aff26ede80276876a791e7e129b763835474ba835472ec84af5791e2316dd154d3c19d06aa64b86fdb0e0b0af8c8c573877be348e2c90d5bcd8a2807819"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_firmware_version }}.zip"

#################################################################################################################################
## FACTORY info (only relevant for: Google Pixel, Fairphone)
##
# source: https://archive.org/details/sunfish-tq3a.230805.001.s1

vendor_factory_id: tq3a.230805.001.s1
vendor_factory_hash: 82902ea9

vendor_factory_version: "{{ target_model }}-{{ vendor_factory_id }}-factory-{{ vendor_factory_hash }}"

# direct download link to the OTA/factory zip of the vendor.
vendor_factory_download_url: "https://archive.org/download/sunfish-tq3a.230805.001.s1/sunfish-tq3a.230805.001.s1-factory-82902ea9.zip"
vendor_factory_download_sha512: "767d05453ee5da220e1ac12ecf1705d1cb8938d6a280b1c6fe09243122394d25a1fac7f579a9797873c2881d92c126a7c73356288aa66d7608a967dc63386dbf"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_factory_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_factory_version }}.zip"
#################################################################################################################################
