---
# human readable model name
target_model_vendor: "Google"
target_model_name: 'Pixel 4a'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a15

# boot debugger path & config
extendrom_debug_path_default: /mnt/vendor/persist
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/google/msm-4.14

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_google_sunfish

# the common tree main makefile, usually named device.mk or common.mk
# used in e.g. switch_major_release role.
# defaults to "device.mk"
#target_model_common_tree_mk: common.mk

# the BoardConfig file within a device tree, required e.g. for switch_major_release
# usually is one of: BoardConfigCommon, BoardConfig, BoardConfigLineage.
# defaults to BoardConfigCommon
target_model_device_tree_boardmk: BoardConfigLineage.mk

# add OpenEUICC
extendrom_package_list: "{{ extendrom_package_list_default }} OpenEUICC_AXP-OS"

# allow creating factory image
custom_build_command: "{{ SH_COMMON_PIXEL_CREATE_FACTORY }}"

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: '2357DB9EBF8090F9'
axp_bootloader_id_slim: 'B49112D3DD534A21'

# git push
axp_git_push_device_include: "{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_google_sunfish"

# website info
hugo_encryption: "FBEv1"
hugo_firmware: "included"
hugo_relockable: "yes"
hugo_state: "stable"
hugo_supportlevel: "team"
hugo_isab: "yes"
hugo_xda_link: "https://xdaforums.com/t/rom-a13-official-microg-hardened-sunfish-axp-os-20.4651368/"
hugo_first_releasedate: "2024-01-16"
#hugo_kb_link: ""
#hugo_custom_installguide_path: 
hugo_axp_bootloader_id_pro: |
  BOOTLOADER minimal ID
        2357DB9E

  BOOTLOADER full ID:
        2357DB9EBF8090F9
        908E9BBC0B353CC9
        CA11015AC588001D
        0AB9A80BD8AA5906
hugo_axp_bootloader_id_slim: |
  BOOTLOADER minimal ID
          B49112D3
  
  BOOTLOADER full ID:
          B49112D3DD534A21
          AD3FC088B8977377
          4004899D7B181996
          15E6F074099EA3E0

# vendor/firmware info
# download source: https://archive.org/details/sunfish-tq3a.230805.001.s1
vendor_firmware_download_url: "https://archive.org/download/sunfish-tq3a.230805.001.s1/sunfish-ota-tq3a.230805.001.s1-965296b1.zip"
vendor_firmware_download_sha512: "cbdf1aff26ede80276876a791e7e129b763835474ba835472ec84af5791e2316dd154d3c19d06aa64b86fdb0e0b0af8c8c573877be348e2c90d5bcd8a2807819"
# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though.
vendor_firmware_persistent_path: "{{ persistent_dir }}/sunfish-ota-tq3a.230805.001.s1-965296b1.zip"
