---
# human readable model name
target_model_vendor: LGE
target_model_name: 'G4'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }} ({{ sub_model | d('') }})"

# boot debugger path & config
extendrom_debug_path_default: /persist
extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# special G4 manifest branch
git_repo_local_manifests_branch: "{{ ROM_FLAVOR }}-{{ android_shortversion }}_g4"

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/lge/msm8992

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_lge_g4-common

# common defaults override:
rempath: "/home/nightlies/roms/{{ ROM_FLAVOR }}/{{ sub_model }}/"
post_cleanup_product_override: "{{ SEPARATE_OUT_DIR }}/target/product/{{ sub_model }}"

# disable AVB
axp_avb_version: 0

# git push
axp_git_push_device_include: "device_lge_g4|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_lge"

# enable kernel patching
# this kernel is special bc it (still) exists in Fix_CVE_Patchers.sh (they supported it a while ago)
# but as they removed the patcher script we need to set it to unsupported:
divest_unsupported_device: true
unsupported_device_kernel_patch: true

# this is a low-end device (optimize for performance)
axp_lowend_device: true
axp_auto_encrypt: false

dl_links: |-
  ***Download:*** [{{ ROMFILE.stdout | replace("-", "\-") | replace("_", "\_") | replace(".", "\.") }} ]({{ leech_server }}/axp/{{ sub_model }}/)

# CONFIG_STRICT_MEMORY_RWX=y breaks boot!
# no need to set this due to the new hardenDefconfig approach this gets not added at all
# axp_defconfig_device: "CONFIG_STRICT_MEMORY_RWX=n"

# removing IMS will break boot
# > "/vendor/bin/imscmservice": library "lib-imsrcscmservice.so" not found: needed by main executable
axp_deblobber_remove_ims: 'false'
axp_deblobber_remove_rcs: 'false'

# libcir is needed by consumerir
axp_deblobber_remove_ir: 'false'

# special testing area
extendrom_intercept_installsrc: 'true'

#################################################################################################################################
## Website info
#

# COMMON block
hugo_firmware: "manual"

# Is the device an A/B device (legacy or virtual)?
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'no'

hugo_xda_link: "https://xdaforums.com/t/rom-a11-official-microg-hardened-h815-axp-os-18-1.4708920/" # link to the AXP.OS XDA post for that device
hugo_kb_link: "g4"
hugo_custom_installguide_path: "content/devices/install_g4.guide"
hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=74" # "&labels=56" for enchilada

#### PRO block ####
android_version_pro: 11
hugo_relockable_pro: 'no'
hugo_encryption_pro: "FDE" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#hugo_supportlevel_pro: "team"  # i.e.: "team" | "community"
#hugo_first_releasedate_pro: "TBD" # first public stable release date (YYYY-MM-DD)
#hugo_state_pro: "stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
# hugo_patchlevel_pro: ""
