---
# yamllint disable rule:comments
#################################################################################################################################
# source: https://github.com/sfX-android/automation_scripts/blob/ansible/roles/axp/common_init_device/vars/copytemplate.yml
# v2.0
#################################################################################################################################
#:h:# all lines starting with '#:h:#' are special help lines to give some context for identifying what's requested
#:h:# if you have no idea about a setting, either ask in the support "bringup" channel or simply skip it
#################################################################################################################################

#################################################################################################################################
## Device info
#

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
# human readable model name
target_model_vendor: "" # e.g. OnePlus or Google
target_model_name: '' # e.g. '5T' or 'Pixel 4a'. always ensure single quotes here

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
# path to the kernel dir
# e.g. "kernel/oneplus/msm8998"
target_kernel_dir: ""

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
# git repo name of the device common tree
#:h:# e.g. "android_device_oneplus_msm8998-common"
#:h:# usually this can be found in https://github.com/LineageOS
#:h:# if you have no idea, leave empty
target_model_common_tree: ""

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
#:h:# does your device support eSIM's?
#:h:# If so just remove the "#" on the axp_euicc_capable: true line
#:h:# if you are unsure you can try:
#:h:# Settings > Network & Internet/Connections > SIM Manager/Add eSIM
#:h:# Alternatively, dial *#06# and check for an "EID" number.
# add OpenEUICC
#axp_euicc_capable: true

#:h:# OPTIONAL OVERWRITE ##############################################################################
#:h:# only if the kernel repo contains "drivers/net/wireguard", set this to true
# disable Wireguard patching (already part of the upstream kernel)
#skip_wireguard: true

#:h:# OPTIONAL OVERWRITE ##############################################################################
# AVB version. Can be: 1|2|0 (if unset this defaults to 2).
#:h:# Details: https://axpos.org/docs/knowledge/verifiedboot
#:h:# if the device was supported by DivestOS you can check "Verified Boot" at https://divestos-archive.codeberg.page/page/devices.html
#:h:# if device supports only AVB v1 and the target Android version is 11 or later AVB should be disabled (as v1 is deprecated)!
#:h:# (see also: https://axpos.org/docs/knowledge/verifiedboot/#details)
#:h:# to disable AVB, set it to 0.
#:h:# do not use any quotes here.
#axp_avb_version: 1

#:h:# OPTIONAL OVERWRITE ##############################################################################
#:h:# usually legacy devices like LG G4, klte and such while that always depends on the
#:h:# target Android version. This will have drawbacks, details can be found here: 
# https://axpos.org/docs/knowledge/techdetails/#what-changes-does-axp_lowend_device-make
#axp_lowend_device: true

#:h:# OPTIONAL OVERWRITE ##############################################################################
# set to False to skip force encryption,
# might be required when "axp_lowend_device: true" and the device supports FDE (https://axpos.org/docs/developer/encryption/) only
#axp_auto_encrypt: false

#:h:# OPTIONAL / DEFINE-IF-YOU-CAN: ###################################################################
# boot debugger mount point
#:h:# requires more deep knowledge in how to identify, so you will likely want to just skip it
#:h:# path for boot_debug, must be identified within the device / common tree fstab:
#:h:# - must be a writable partition
#:h:# - must be a mountable partition (ext2, ext4, f2fs, ..)
#:h:# usually one of: /mnt/vendor/persist, /metadata or /cache
extendrom_debug_path_default: ""

#:h:# NEVER TOUCH THIS ##############################################################################
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

#:h:# NEVER TOUCH THIS ##############################################################################
# Pixel devices: KLEAF based kernel build
#pixel_kernel_codename: raviole
# see https://android.googlesource.com/kernel/common/+refs
#git_pixel_kernel_manifest_branch: "android-gs-{{ pixel_kernel_codename }}-6.1-android15-qpr2"

#:h:# NEVER TOUCH THIS ##############################################################################
# construct specific model device tree automatically
target_model_device_tree: android_device_{{ target_model_vendor | lower() }}_{{ target_model | lower() }}

#:h:# NEVER TOUCH THIS ##############################################################################
# the common tree or if there is none the device main makefile,
# usually named device.mk or common.mk. used in e.g. switch_major_release role.
# defaults to "device.mk"
#target_model_device_tree_mk: common.mk

#:h:# NEVER TOUCH THIS ##############################################################################
# do NOT upload the recovery image
#axp_release_recovery: false

#:h:# NEVER TOUCH THIS ##############################################################################
# AVB v1 only (if axp_avb_version: 1)
# the partitions signed by boot_signer:
#axp_avb_bootparts: "boot|recovery"
#axp_avb_bootparts_count: 2
#axp_avb_dmparts_count: 2 # (e.g. system.img + vendor.img)

#:h:# NEVER TOUCH THIS ##############################################################################
# some devices might fail verifying the boot.img if the expire date is set to the default (30 years)
#KEYS_CERT_DAYS_VERITY: 3650

#:h:# NEVER TOUCH THIS ##############################################################################
#axp_avb_algorithm: "SHA512_RSA4096" # sets BOARD_AVB_ALGORITHM (warning: must match the created AVB key!)
#axp_avb_hashtree_algorithm: default # sets AXP_HASHTREE_ALGORITHM (can be one of: default,sha1,sha256,sha512. "default" depends on AXP_LOWEND_DEVICE)

#:h:# NEVER TOUCH THIS ##############################################################################
extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

#:h:# NEVER TOUCH THIS ##############################################################################
# git push project names related to this device. used for device init, reproducible builds, ci/cd
axp_git_push_device_include: "{{ target_model_device_tree }}|{{ target_model_common_tree }}"

#:h:# NEVER TOUCH THIS ##############################################################################
# all used VENDOR paths for this device
axp_git_push_vendor_include: "{{ target_model_device_tree | replace('android_device_', 'vendor_') }}|{{ target_model_common_tree | replace('android_device_', 'vendor_') }}"

#:h:# NEVER TOUCH THIS ##############################################################################
# Bootloader ID (first line) for validating build log
#axp_bootloader_id_pro: ''
#axp_bootloader_id_slim: ''

#################################################################################################################################
## Website info
#

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
# COMMON block
#:h:# do we include vendor firmware?
#:h:# 1. open https://code.binbash.rocks/AXP.OS/vendor_firmware
#:h:# 2. select the correct `branch` _(must match the AXP.OS Android version, e.g. "axp-a15")_
#:h:# 3. click the folder with the `codename` for your device
#:h:# 4. If there is a folder with the device's codename (e.g. `enchilada`):
#:h:#   - check the file `AndroidBoardVendor.mk`: It should contain several `$(call add-radio-file.....` lines
#:h:# If steps 1-4 were successful set "included" otherwise "manual"
hugo_firmware: ""

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
# Is the device an A/B device (legacy or virtual)?
#:h:# A/B? -> https://source.android.com/docs/core/ota/virtual_ab
#:h:# How to identify:
#:h:# - https://www.xda-developers.com/list-android-devices-seamless-updates/
#:h:# - General Rules:
#:h:#   Android 13+: (Virtual) A/B
#:h:#   Android 11+: A/B
#:h:#   Google Pixel: Every Google Pixel device ever released uses A/B partitions.
#:h:#   Samsung: not before 2024 and even then need to be verified
#:h:# - Manual Verification Method
#:h:#   adb shell getprop ro.boot.slot_suffix
#:h:#   -> if it returns _a or _b, it is an A/B device.
#:h:#   -> if it returns nothing, it is an A-only device.
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: ''

#:h:# NEVER TOUCH THIS ##############################################################################
#hugo_xda_link: "" # link to the AXP.OS XDA post for that device
#hugo_kb_link: "" # OPTIONAL: knownissues link, only if there is any
#hugo_custom_installguide_path: "" # OPTIONAL: custom installation guide
#hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=" # "&labels=56" for enchilada

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
#:h:# one block, either PRO / SLIM depending on your request

#### PRO block ####
#:h:# AXP.OS might not offer the latest available Android version for your device (by design):
#:h:# 1. check the current latest stable or planned Android version: https://axpos.org/docs/knowledge/requirements/#android-version
#:h:# 2. find your device in the LineageOS wiki: https://wiki.lineageos.org/
#:h:# 3. find "Current version" and "Previously supported versions" matching the AXP.OS one from step 1
#:h:# just the number, no quotes here. e.g. : 9,10,11,13,15
android_version_pro: 
#:h:# bootloader re-lock supported?
#:h:# if the device was supported by DivestOS you can check "Verified Boot" at https://divestos-archive.codeberg.page/page/devices.html
#:h:# can be: 'yes' or 'no', single quotes required
hugo_relockable_pro: ''

#:h:# NEVER TOUCH THIS ##############################################################################
#hugo_encryption_pro: "" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#hugo_axp_bootloader_id_pro: |- # if AVB: the bootloader id string (from build log)
#hugo_supportlevel_pro: "community"  # i.e.: "team" | "community"
#hugo_first_releasedate_pro: "TBD" # first public stable release date (YYYY-MM-DD)
#hugo_state_pro: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
#hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
#hugo_patchlevel_pro: ""

#### SLIM block ####
#:h:# AXP.OS might not offer the latest available Android version for your device (by design):
#:h:# 1. check the current latest stable or planned Android version: https://axpos.org/docs/knowledge/requirements/#android-version
#:h:# 2. find your device in the LineageOS wiki: https://wiki.lineageos.org/
#:h:# 3. find "Current version" and "Previously supported versions" matching the AXP.OS one from step 1
#:h:# just the number, no quotes here. e.g. : 9,10,11,13,15
android_version_slim: 
#:h:# bootloader re-lock supported?
#:h:# if the device was supported by DivestOS you can check "Verified Boot" at https://divestos-archive.codeberg.page/page/devices.html
#:h:# can be: 'yes' or 'no', single quotes required
hugo_relockable_slim: ''

#:h:# NEVER TOUCH THIS ##############################################################################
#hugo_encryption_slim: "" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#hugo_axp_bootloader_id_slim: |- # if AVB: the bootloader id string (from build log)
#hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
#hugo_first_releasedate_slim: "TBD" # first public stable release date (YYYY-MM-DD)
#hugo_state_slim: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
#hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of:
#   "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel"
#hugo_patchlevel_slim: ""

#:h:#################################################################################################################################
#:h:# OPTIONAL:
#:h:# The WHOLE following firmware info block depends on: "hugo_firmware" (see above).
#:h:# That means anything below is required ONLY if hugo_firmware: "included"

#################################################################################################################################
## FIRMWARE info
#
#:h:# DEFINE-IF-YOU-CAN and hugo_firmware: "included":
#:h:# you need to find a reliable source for downloading the vendor's OTA zip.
#:h:# you can find some examples in the porting guide: https://axpos.org/docs/developer/port/#extract-and-push-vendorfirmware
#:h:# (you do not need to follow that guide, just check out the examples there).
#:h:# this is NOT a direct download link but e.g. the download page of the vendor, an XDA post, ...
#:h:# so simply the page from where the actual download is linked
#:h:# e.g. https://developers.google.com/android/ota#cheetah
#:h:# just change the URL, leave the '#' at start as it is:
# source: https://the-website-where-the-OTAZIP-is-located

#:h:# OPTIONAL OVERWRITE ##############################################################################
#:h:# does the factory zip contain super image(s)? Can be eiher: true|false
#:h:# as it is optional it can be skipped, otherwise it requires extracting the factory zip
#:h:# e.g. using https://github.com/rhythmcache/payload-dumper-rust and checking if there are any "super" images inside
# do not use any quotes here:
#vendor_firmware_super_img: false

#:h:# NEVER TOUCH THIS ##############################################################################
vendor_firmware_version: "" # filename without zip

#:h:# DEFINE-IF-YOU-CAN ##############################################################################
# direct download link to the OTA zip of the vendor.
#:h:# Examples: 
#:h:# - https://github.com/sfX-android/automation_scripts/blob/284dc09e31e80282645d6d937d34496a860cc515/roles/axp/sargo/vars/main.yml#L80
#:h:# - https://github.com/sfX-android/automation_scripts/blob/284dc09e31e80282645d6d937d34496a860cc515/roles/axp/enchilada/vars/main.yml#L70
vendor_firmware_download_url: ""
#:h:# one of sha512 or sha256 is required (in that order) if there is none you have to download and generate it (sha512sum xxx.zip)
#:h:# e.g.: https://github.com/sfX-android/automation_scripts/blob/284dc09e31e80282645d6d937d34496a860cc515/roles/axp/sargo/vars/main.yml#L81
vendor_firmware_download_sha512: ""
#vendor_firmware_download_sha256: ""

#:h:# NEVER TOUCH THIS ##############################################################################
# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_firmware_version }}.zip"
#################################################################################################################################

#################################################################################################################################
## FACTORY info (only relevant for: Google Pixel, Fairphone)
#
#:h:# DEFINE-IF-YOU-CAN and hugo_firmware: "included" and Google pixel or Fairphone:
#:h:# you need to find a reliable source for downloading the vendor's FACTORY zip.
#:h:# you can find some examples in the porting guide: https://axpos.org/docs/developer/port/#extract-and-push-vendorfirmware
#:h:# (you do not need to follow that guide, just check out the examples there).
#:h:# this is NOT a direct download link but e.g. the download page of the vendor, an XDA post, ...
#:h:# so simply the page from where the actual download is linked.
#:h:# e.g. https://developers.google.com/android/images#cheetah
#:h:# just change the URL, leave the '#' at start as it is:
# source: https://the-website-where-the-FACTORYZIP-is-located

#:h:# DEFINE-IF-YOU-CAN and hugo_firmware: "included" and Google pixel or Fairphone ############################################
#:h:# direct download link to the FACTORY zip of the vendor.
#vendor_factory_download_url: ""
# one of sha512 or sha256 is required (in that order) if there is none you have to download and generate it (sha512sum xxx.zip)
#vendor_factory_download_sha512: ""
#vendor_factory_download_sha256: ""

#:h:# NEVER TOUCH THIS ##############################################################################
#vendor_factory_id: ""  # e.g. tq3a.230805.001.s1
#vendor_factory_hash: ""  # e.g. 82902ea9
#vendor_factory_version: "{{ target_model }}-{{ vendor_factory_id }}-factory-{{ vendor_factory_hash }}"
##ref## vendor_factory_download_url: "https://dl.google.com/dl/android/aosp/{{ vendor_factory_version }}.zip"

#:h:# NEVER TOUCH THIS ##############################################################################
# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
#vendor_factory_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_factory_version }}.zip"
#################################################################################################################################
