---

build_id: "init_device"
target_model: "{{ build_id }}"
telegram_notifications: False

init_device_website_repo: "ssh://git@code.binbash.rocks:22443/AXP.OS/axpos-org.git"
init_device_website_branch: "hugo"

init_device_vendorfirmware: "ssh://git@code.binbash.rocks:22443/AXP.OS/vendor_firmware.git"

init_device_otaverifier_repo: "git@github.com:sfX-android/update_verifier.git"

####### gitea action workflow triggering

git_axpos_actions_workflow_repo: actions
git_axpos_actions_workflow_id: activate_mirror.yaml
git_axpos_actions_workflow_repo_branch: main

git_axpos_website_workflow_repo: axpos-org
git_axpos_website_workflow_id: pages.yaml
git_axpos_website_workflow_force: False
git_axpos_website_workflow_repo_branch: hugo

######## defaults

skip_dl_cve_checker: True
skip_dl_git_cli_tools: True
skip_setup_otaverify: False
skip_setup_repos: False
skip_setup_firmware: False
skip_setup_manifest: False
skip_setup_ansible: False
skip_setup_website: False
skip_setup_semaphore: False
skip_mirror_activation: False

########### generate-4-ALL vars

parse_roles_subdir: axp  # roles/xxx to parse
generate_fairphone_factory_image: false
model_exclusions: "common|j5y17lte|klte|h815|g4"

############ semaphore

semaphore_api_uri: "http://127.0.0.1:8153/api"

# Variables used to create a new task template

semaphore_aos_template_project_id: 6                     # Project "AXP.OS"
semaphore_aos_template_inventory_id: 29                  # Inventory "axp_build_inventory"
semaphore_aos_template_repo_id: 9                        # Repository "sfX-android/automation_scripts"
semaphore_aos_template_vaultkey_id: 21                   # Key Store "vault_pw"
semaphore_aos_template_view_id: 37                       # View: "AOS WIP"
semaphore_aos_template_desc: "{{ template_desc | d('') }}" # Template Description
semaphore_aos_template_playbook: "plays/build.yml"        # playbook to attach to

# survey vars
semaphore_aos_template_survey_vars: >-
    [
      {
        "name": "override_clean_basic",
        "title": "clean ZIPs (true* | false)?",
        "required": false,
        "type": "",
        "description": "true | false"
      },
      {
        "name": "override_clean_out",
        "title": "clean build (true* | false)?",
        "required": false,
        "type": "",
        "description": "true | false"
      },
      {
        "name": "override_reset_git",
        "title": "reset all projects & resync (true* | false)?",
        "required": false,
        "type": "",
        "description": "true | false"
      },
      {
        "name": "override_release_build",
        "title": "release the build (true* | false)?",
        "required": false,
        "type": "",
        "description": "true | false"
      },
      {
        "name": "debug_build",
        "title": "private notify (true* | false)?",
        "required": false,
        "type": "",
        "description": "true | false"
      },
      {
        "name": "axp_build_eng",
        "title": "Engineering Build (true | false*)?",
        "description": "will create a debug eng build",
        "required": false,
        "type": ""
      },
      {
        "name": "unstable_build",
        "title": "unstable build (true* | false)?",
        "required": false,
        "type": "",
        "description": "true | false"
      },
      {
        "name": "download_fairphone_firmware",
        "title": "Download & Update firmware (yes|no*)?",
        "type": "enum",
        "description": "vendor/firmware/<device>/0SOURCE must be set",
        "values": [
          {
            "name": "yes",
            "value": "True"
          },
          {
            "name": "no",
            "value": "False"
          }
        ],
        "default_value": "False"
      },
      {
        "name": "generate_pixel_factory_image",
        "title": "Generate factory image (Pixel devices)?",
        "description": "vendor/firmware/<device>/0SOURCE must be set",
        "required": false,
        "type": ""
      },
      {
        "name": "commit_push",
        "title": "commit_push",
        "required": true,
        "type": "enum",
        "values": [
            {
                "name": "yes",
                "value": "True"
            },
            {
                "name": "no",
                "value": "False"
            }
        ],
        "default_value": "False"
    }
    ]

# vaults
semaphore_aos_template_vaults: >-
    [{
      "name": "main",
      "vault_key_id": {{ semaphore_aos_template_vaultkey_id }},
      "type": "password",
      "script": null
    }]
