---
# human readable model name
target_model_vendor: "OnePlus"
target_model_name: '7 Pro'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a13

# boot debugger path & config
extendrom_debug_path_default: /metadata
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/oneplus/sm8150

# upload the recovery image
axp_release_recovery: True

# disable Wireguard patching (already part of the upstream kernel)
# temp!!!!!!!!
skip_wireguard: True

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: '26B88EDA82ED966A'
axp_bootloader_id_slim: ''
