---

parent_model: g4
sub_model: h812_usu

#################################################################################################################################
## Website info
#

#### PRO block ####
hugo_supportlevel_pro: "community"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "TBD" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: "BETA" # "stable" | "!! ALPHA !!" | "BETA"
