---

parent_model: g4
sub_model: h812_usu

#################################################################################################################################
## Website info
#

#hugo_xda_link: "" # link to the AXP.OS XDA post for that device
#hugo_kb_link: "" # OPTIONAL: knownissues link, only if there is any, will be prefixed with "#"
#hugo_custom_installguide_path: "" # OPTIONAL: custom installation guide
#hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=" # "&labels=56" for enchilada

#### PRO block ####
#android_version_pro: 
#hugo_relockable_pro: ''
#hugo_encryption_pro: "" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
#axp_bootloader_id_pro: '' # if AVB: Bootloader ID (first line) for validating build log
#hugo_axp_bootloader_id_pro: |- # if AVB: the full bootloader id string (from build log)
hugo_supportlevel_pro: "community"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "TBD" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
#hugo_patchlevel_pro: ""
