---

- name: "Fix verity"
  ansible.builtin.lineinfile:
    path: "{{ item.f }}"
    line: '\\1'
    regexp: '^({{ item.s }})'
    backrefs: true
  loop:
      - f: {{ SRCPATH }}/device/fairphone/FP3/BoardConfig.mk
        s: 'BOARD_AVB_SYSTEM_KEY_PATH.*'
      - f: {{ SRCPATH }}/device/fairphone/FP3/BoardConfig.mk
        s: 'BOARD_AVB_SYSTEM_ALGORITHM.*'
