---

- name: "apply specific LG G4 fixes (general)"
  shell: |-
     sed -i 's/voldmanaged=sdcard1:auto,forceencrypt/voldmanaged=sdcard1:auto,encryptable/g' device/lge/g4-common/rootdir/etc/fstab.qcom  # do not forceencrypt ext. sdcard
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
 
- name: "apply specific LG G4 picks (A12 only)"
  shell: >-
      cd {{ item.path }} && git fetch {{ item.fetch }} && git cherry-pick {{ item.pick }}
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash
  loop:
    - { path: "external/perfetto", fetch: "https://github.com/LineageOS/android_external_perfetto refs/changes/06/287706/8", pick: "FETCH_HEAD" }
    - { path: "system/bpf", fetch: "https://github.com/LineageOS/android_system_bpf refs/changes/91/320591/2", pick: "FETCH_HEAD" }
    - { path: "system/netd", fetch: "https://github.com/LineageOS/android_system_netd refs/changes/92/320592/2", pick: "FETCH_HEAD" }
    - { path: "art", fetch: "https://github.com/LineageOS/android_art refs/changes/97/318097/1", pick: "FETCH_HEAD" }
    - { path: "packages/modules/adb", fetch: "https://github.com/LineageOS/android_packages_modules_adb refs/changes/85/326385/3", pick: "FETCH_HEAD" }
    - { path: "system/sepolicy", fetch: "https://github.com/LineageOS-OP2/android_system_sepolicy 23468e3d6afe8d88b5bd024c697d698704f9db47", pick: "23468e3d6afe8d88b5bd024c697d698704f9db47" }
  when: android_shortversion == "a12"
