---

- ansible.builtin.set_fact:
    build_temp_path: "{{ android_build_path }}/.tmp/freeze_apps"

- name: "Build apps: Start clean"
  ansible.builtin.file:
      path: "{{ build_temp_path }}"
      state: absent

- block:

        - name: "Build apps: fetch git repo"
          ansible.builtin.git:
            repo: "{{ freezeday_axp_git_org }}/{{ repo.name }}"
            dest: "{{ build_temp_path }}"
            version: "{{ repo.branch }}"
          timeout: 180
        
        - name: "Build apps: add/update trigger-build.txt"
          ansible.builtin.shell: |
            if [ ! -f trigger-build.txt ];then
              echo last_ansible_trigger_date="$(date +%F_%T)" > trigger-build.txt
            else
              sed -i 's/last_ansible_trigger_date=.*/last_ansible_trigger_date=$(date +%F_%T)/g' trigger-build.txt
            fi
          args:
              chdir: "{{ build_temp_path }}"
              executable: /bin/bash
        
        - name: "Build apps: add & push changes"
          ansible.builtin.shell: |
              set -e
              echo "[GIT][BUILDAPPS] starting git commit process" >> {{ BUILD_LOG }}
            
              CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
              if [ $CMTL -gt 0 ];then
                  git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
                  git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "ci: added/updated build trigger" >> {{ BUILD_LOG }} 2>&1
                  echo "[GIT][BUILDAPPS] git commit done" >> {{ BUILD_LOG }}
        
                  CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
                  REMHASH=$(git log --pretty=oneline --decorate | grep "origin/{{ repo.branch }}" |cut -d ' ' -f1)
                    
                  if [ "$CURHASH" != "$REMHASH" ]; then
                      echo "[GIT][BUILDAPPS] pushing required ($CURHASH != $REMHASH)!" >> {{ BUILD_LOG }}
                      git push origin {{ repo.branch }} >> {{ BUILD_LOG }} 2>&1
                  else
                      echo "[GIT][BUILDAPPS] pushing skipped ($CURHASH == $REMHASH)!" >> {{ BUILD_LOG }}
                  fi
              else
                   echo "[GIT][BUILDAPPS] git commit skipped (no changes)" >> {{ BUILD_LOG }}
              fi
          args:
              chdir: "{{ build_temp_path }}"
              executable: /bin/bash

  rescue:

        - name: "Build apps: End clean"
          ansible.builtin.file:
              path: "{{ build_temp_path }}"
              state: absent

        - name: "Build apps: failed"
          ansible.builtin.fail:
            msg: |
              ERROR OCCURED:
              
              {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
              
              See above for details.
