---

- name: "Build apps: get all trigger-build.txt sha values"
  ansible.builtin.uri:
    url: "{{ git_api_uri }}/repos/{{ item.name }}/contents/trigger-build.txt?ref={{ item.branch }}"
    method: GET
    headers:
        Content-Type: application/json
        Authorization: "token {{ vault_gitea_rw_token }}"
        accept: application/json
  loop: "{{ freezeday_app_repos }}"
  loop_control:
      label: info
  register: file
  ignore_errors: true
  no_log: "{{ debug_off | bool }}"
   
- name: "Build apps: create missing trigger"
  ansible.builtin.uri:
    url: "{{ git_api_uri }}/repos/{{ item.item.name }}/contents/trigger-build.txt"
    method: POST
    headers:
        Content-Type: application/json
        Authorization: "token {{ vault_gitea_rw_token }}"
        accept: application/json
    body_format: json
    body: >-
      {
        "branch": "{{ item.item.branch }}",
        "content": "{{ ansible_date_time.iso8601 | b64encode }}"
      }
    status_code: [ 201, 200 ]
  loop: "{{ file.results }}"
  when: item.json.sha is undefined

- name: "Build apps: trigger a build"
  ansible.builtin.uri:
    url: "{{ git_api_uri }}/repos/{{ item.item.name }}/contents/trigger-build.txt"
    method: PUT
    headers:
        Content-Type: application/json
        Authorization: "token {{ vault_gitea_rw_token }}"
        accept: application/json
    body_format: json
    body: >-
      {
        "branch": "{{ item.item.branch }}",
        "content": "{{ ansible_date_time.iso8601 | b64encode }}",
        "sha":"{{ item.json.sha }}"
      }
    status_code: [ 201, 200 ]
  register: triggered
  changed_when: triggered.status == 201
  loop: "{{ file.results }}"
  loop_control:
    pause: 5m
  no_log: "{{ debug_off | bool }}"

- name: Result
  ansible.builtin.debug:
    msg: |
      triggered: {{ item }}
  loop: "{{ triggered.results }}"
