---
# human readable model name
target_model_vendor: "Google"
target_model_name: "Pixel 6a"
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a13

# boot debugger path & config
extendrom_debug_path_default: /mnt/vendor/persist
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/google/gs201/private/gs-google

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_google_gs101

# allow creating factory image
custom_build_command: "{{ SH_COMMON_PIXEL_CREATE_FACTORY }}"

# add OpenEUICC
axp_euicc_capable: true

# git push
axp_git_push_device_include: "device_google_bluejay|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_google_bluejay"

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: true

#################################################################################################################################
## Website info
#

# COMMON block
hugo_firmware: "included"

# Is the device an A/B device (legacy or virtual)?
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'yes'

hugo_xda_link: "https://xdaforums.com/t/rom-a13-official-microg-hardened-bluejay-axp-os-20-0.4663844/"
hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=80" # "&labels=56" for enchilada

#### PRO block ####
android_version_pro: 13
hugo_relockable_pro: 'yes'
hugo_encryption_pro: "FBEv1" # https://github.com/LineageOS/android_device_google_gs101/blob/lineage-22.2/conf/fstab.gs101.in
axp_bootloader_id_pro: '27AA5BB1975D18B0' # if AVB: Bootloader ID (first line) for validating build log
hugo_axp_bootloader_id_pro: |-
  BOOTLOADER minimal ID
        27AA5BB1

  BOOTLOADER full ID: 
        27AA5BB1975D18B0
        402E0F17B0DC1C94
        13CA0F5ACF3C70AE
        0711C05CDE94AAFB
hugo_supportlevel_pro: "team"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "2024-03-26" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: "stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
# hugo_patchlevel_pro: ""

#################################################################################################################################
## FIRMWARE info
#
# source: https://developers.google.com/android/ota#bluejay

vendor_firmware_download_url: "https://archive.org/download/20250720_20250720_1751/OTA/13.0.0-TQ3A.230901.001-Sep%202023-1f1f0abe67a6f6f47287be6dafec2c12628de6a715b82ca7beddaf67ad22aca5/bluejay-ota-tq3a.230901.001-1f1f0abe.zip"
vendor_firmware_download_sha256: "1f1f0abe67a6f6f47287be6dafec2c12628de6a715b82ca7beddaf67ad22aca5"
# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though.
vendor_firmware_persistent_path: "{{ persistent_dir }}/bluejay-ota-tq3a.230901.001-1f1f0abe.zip"
####### A15 prep:
#vendor_firmware_download_url: "https://archive.org/download/20250720_20250720_1751/OTA/15.0.0-BP1A.250505.005-May%202025-728eab10ee8393a04503e2f79cfe441f7f287a6dda4ba207d0550632009f6904/bluejay-ota-bp1a.250505.005-728eab10.zip"
#vendor_firmware_download_sha256: "728eab10ee8393a04503e2f79cfe441f7f287a6dda4ba207d0550632009f6904"
# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though.
#vendor_firmware_persistent_path: "{{ persistent_dir }}/bluejay-ota-bp1a.250505.005-728eab10.zip"
