---
# human readable model name
target_model_vendor: "Samsung"
target_model_name: 'J5 - 2017'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a10

# temp pin asb level to august atm
sec_patch_date_last: level

# boot debugger path & config
extendrom_debug_path_default: /cache
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# extend extendrom_package_list
extendrom_package_list: "{{ extendrom_package_list_default }} opencamera_j5_latest"

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/samsung/exynos7870

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_samsung_universal7870-common

# enable kernel patching
divest_unsupported_device: true
unsupported_device_kernel_patch: true

# disable verified boot
vbmeta_verify: false

# set AVB v1.0 / Verity-only
axp_avb_version: 1

# this is a low-end device (optimize for performance)
axp_lowend_device: True

# A10 does not support allow call recording
extendrom_allow_any_call_recording: 'false'

# git push
axp_git_push_device_include: "device_samsung_j5y17lte|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_samsung_universal7870-common|vendor_samsung_j5y17lte"

# CONFIG_ARM64_SW_TTBR0_PAN breaks boot!
axp_defconfig_device: "CONFIG_ARM64_SW_TTBR0_PAN=n"

# deblobbing audiofx breaks video recording due to the removal of libLifevibes_lvverx.so + libLifevibes_lvvetx.so
axp_deblobber_remove_audiofx: 'false'

# disable hardened malloc. likely related to the increased key size of the AXP signature
# > I:comment is 3915 bytes; signature is 3897 bytes from end
# > libc: malloc(65536) failed: returning null pointer
# > terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
# > libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
axp_graphene_malloc: >-
  {% if axp_build_recovery_only is defined and axp_build_recovery_only %}'false'{% else %}'true'{% endif %}

# ASB patch date override, month+1:
# (latest avail backport is from August 2025)
sec_patch_date_last: 202509
# CVE Kernel patch tag override, exactly as it should be:
# (should be usually always current, regardless of sec_patch_date_last and HAS TO be set when sec_patch_date_last is set)
cve_tag: "{{ current_year }}{{ current_month }}"