---
# human readable model name
target_model_vendor: "Samsung"
target_model_name: 'J5 - 2017'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a10

# boot debugger path & config
extendrom_debug_path_default: /cache
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# extend extendrom_package_list
extendrom_package_list: "{{ extendrom_package_list_default }} opencamera_j5_latest"

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/samsung/exynos7870

# enable kernel patching
divest_unsupported_device: true
unsupported_device_kernel_patch: true

# disable verified boot
vbmeta_verify: false

# disable AVB + verity
axp_enable_avb: 'false'

# this is a low-end device (optimize for performance)
axp_lowend_device: True

# A10 does not support allow call recording
extendrom_allow_any_call_recording: 'false'
