---
# human readable model name
target_model_vendor: "Samsung"
target_model_name: 'J5 - 2017'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a10

# temp pin asb level to august atm
sec_patch_date_last: level

# boot debugger path & config
extendrom_debug_path_default: /cache
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# extend extendrom_package_list
extendrom_package_list: "{{ extendrom_package_list_default }} opencamera_j5_latest"

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/samsung/exynos7870

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_samsung_universal7870-common

# enable kernel patching
divest_unsupported_device: true
unsupported_device_kernel_patch: true

# set AVB v1.0 / Verity-only
axp_avb_version: 1

# no boot/recovery.img tests
# 1) we cannot re-lock this device
# 2) samsungs crappy boot.img handling conflicts with all standards, making verify tests fail anyways
skip_avb_boot_verify: True

# this is a low-end device (optimize for performance)
axp_lowend_device: True

# A10 does not support allow call recording
extendrom_allow_any_call_recording: 'false'

# git push
axp_git_push_device_include: "device_samsung_j5y17lte|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_samsung_universal7870-common|vendor_samsung_j5y17lte"

# CONFIG_ARM64_SW_TTBR0_PAN breaks boot!
# force-enable dm-verity
axp_defconfig_device: "CONFIG_ARM64_SW_TTBR0_PAN=n CONFIG_DM_VERITY=y CONFIG_DM_VERITY_FEC=y CONFIG_CRYPTO_AES_ARM64_NEON_BLK=y"

# deblobbing audiofx breaks video recording due to the removal of libLifevibes_lvverx.so + libLifevibes_lvvetx.so
axp_deblobber_remove_audiofx: 'false'

# disable hardened malloc. likely related to the increased key size of the AXP signature
# > I:comment is 3915 bytes; signature is 3897 bytes from end
# > libc: malloc(65536) failed: returning null pointer
# > terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
# > libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
axp_graphene_malloc: >-
  {% if axp_build_recovery_only is defined and axp_build_recovery_only %}'false'{% else %}'true'{% endif %}

# required for log parsing & website flavor info
axp_bootloader_id_pro: A87D42D8B66CA9CC
#axp_bootloader_id_slim:

# website info
hugo_encryption: "FBEv1"
hugo_firmware: "manual"
hugo_relockable: "no"
hugo_state: "stable"
hugo_supportlevel: "team"
hugo_isab: "no"
hugo_xda_link: "https://xdaforums.com/t/rom-a10-official-microg-hardened-j5y17lte-axp-os-17-1.4644557/"
hugo_first_releasedate: "2024-06-20"
hugo_kb_link: ""
hugo_custom_installguide_path: "content/devices/custom_${HUGO_CODENAME}.guide"
hugo_axp_bootloader_id_pro: |
  BOOTLOADER minimal ID (AVB 1)
        A87D42D8

  BOOTLOADER full ID:
        A87D42D8B66CA9CC
        0D509BADFECACC79
        521EED275F4677EA
        0F5DB3688EA16A0C
#hugo_axp_bootloader_id_slim: |


# ASB patch date override, month+1:
# (latest avail backport is from August 2025)
sec_patch_date_last: 202509
# CVE Kernel patch tag override, exactly as it should be:
# (should be usually always current, regardless of sec_patch_date_last and HAS TO be set when sec_patch_date_last is set)
cve_tag: "{{ current_year }}{{ current_month }}"