---

model_exclusions: "common|a52q|xz2c"
build_id: kernel_patches_tester
target_model: "{{ build_id }}"

# overwrite source path so we do not tamper around on our regular builds
DOSPATH: "/home/androidsource/do-not-touch/{{ build_id }}"
