---

- name: "Prepare incremental Kernel Patches (download.sh)"
  ansible.builtin.shell: |
    for i in $(ls -1 |sort -r | grep -v '.sh' | sed 's/^v//g');do
      echo "Starting $i"
      cd $i
      left=$(echo "${i}" | cut -d '.' -f 1)
      right=$(echo "${i}" | cut -d '.' -f 2)
      latest_full=$(git ls-remote --tags {{ git_kernel_org }} "refs/tags/v${i}.*" | cut -d '/' -f3 |grep -v '\{' | sort -Vr | head -n 1)
      latest=$(echo "${latest_full}" | cut -d '.' -f 3)
      echo "left: $left, right: $right, latest: $latest"
      java -jar {{ divest_cve_checker_jar }} linuxIncrDownload ${left}.x ${i}. $latest > download.sh
      cd ..
      echo "Ending $i"
    done
  args:
    chdir: "{{ cve_kernel_incrementals_path }}"

- name: "Prepare incremental Kernel Patches (downloadall.sh)"
  ansible.builtin.shell: |
      for i in $(find . -mindepth 1 -maxdepth 2 -type d); do 
          dlsh="$i/download.sh"
          for d in $(grep wget "$dlsh" | sed -E "s#(.*)\s?>\s?(.*\.patch)#$i/\2#g");do
              if [ ! -f "$d" ];then
                  grep "${d##.*\/}" "$dlsh" | sed "s%${d##.*\/}%$i/${d##.*\/}%g" >> downloadall.sh
                  echo ">${d##.*\/}< in >$dlsh<"
              fi
          done
      done
  args:
    chdir: "{{ cve_kernel_incrementals_path }}"

- name: "Download missing Kernel Patches (downloadall.sh)"
  ansible.builtin.shell: |
      bash downloadall.sh
  args:
    chdir: "{{ cve_kernel_incrementals_path }}"
