---

hypatia_base_path: /srv/packages_apps_hypatia
hypatia_signatures_path: /srv/sigdb

# database sources
hypatia_uri_avast: "https://github.com/avast/covid-19-ioc"
hypatia_path_clamav: "/var/lib/clamav"
hypatia_uri_eset: "https://github.com/eset/malware-ioc"
hypatia_uri_cybercure: "https://api.cybercure.ai/feed/get_hash?type=csv"
hypatia_uri_threatview_md5: "https://threatview.io/Downloads/MD5-HASH-ALL.txt"
hypatia_uri_threatview_sha: "https://threatview.io/Downloads/SHA-HASH-FEED.txt"
hypatia_uri_threatfox: "https://threatfox.abuse.ch/export/csv/sha256/full/"
hypatia_uri_malshare: "https://malshare.com/daily/$curr/malshare_fileList.$curr.txt"
hypatia_uri_sanesecurity: "rsync://rsync.sanesecurity.net/sanesecurity"
hypatia_uri_stalkerware: "https://github.com/AssoEchap/stalkerware-indicators"
hypatia_uri_targetedthreats: "https://github.com/botherder/targetedthreats"
