---
- name: "Get all available patches"
  find:
    paths: "{{ SRCPATH }}/external/patches"
    patterns: "*.diff"
  register: patch
  
- name: "Apply patches"
  shell: "bash external/patches/apply.sh"
  args:
    chdir: "{{ SRCPATH }}"
  register: patchres
  failed_when: patchres.rc == 2
  when: patch.examined > 0

- name: "Update ROM version"
  lineinfile:
    path: "{{ SRCPATH }}/build/make/core/build_id.mk"
    regexp: BUILD_ID=.*
    line: "BUILD_ID={{ ROM_NAME }}-v{{ ROM_VERSION }}"
    state: present

# this overwrites everything otherwise
- name: "Wipe Pixel board config"
  ansible.builtin.shell: echo > build/make/target/board/BoardConfigPixelCommon.mk
  args:
    chdir: "{{ SRCPATH }}"

- name: "Set Emergency Call threshold"
  ansible.builtin.lineinfile:
    path: "{{ SRCPATH }}/frameworks/base/services/core/java/com/android/server/GestureLauncherService.java"
    regexp: '(.* )(EMERGENCY_GESTURE_POWER_TAP_COUNT_THRESHOLD).*'
    line: '\1\2 = {{ emergency_gesture_power_tap_count_threshold }};'
    backrefs: true
  when: emergency_gesture_power_tap_count_threshold is defined

- name: "Set keys workaround for PRODUCT_DEFAULT_DEV_CERTIFICATE"
  ansible.builtin.shell: >
    for i in $(find keys/{{ target_model }} -type f -name '*.pem' -or -name '*.pk8');do ln -fs {{ target_model }}/${i##*/} keys/;done
  args:
    chdir: "{{ SRCPATH }}"

# if PRODUCT_DEFAULT_DEV_CERTIFICATE is set it will be used also for signing the OTA
# but if you want to use different certs for app signing and the OTA the following is required
- name: "Set releasekey workaround for OTA signing when PRODUCT_DEFAULT_DEV_CERTIFICATE is set"
  ansible.builtin.lineinfile:
    path: "{{ SRCPATH }}/build/make/tools/releasetools/ota_utils.py"
    regexp: 'package_key=OPTIONS.package_key'
    line: 'package_key="keys/releasekey"'
    state: present
