---
- name: "Get all available patches"
  find:
    paths: "{{ SRCPATH }}/external/patches"
    patterns: "*.diff"
  register: patch
  
- name: "Apply patches"
  shell: "bash external/patches/apply.sh"
  args:
    chdir: "{{ SRCPATH }}"
  register: patchres
  failed_when: patchres.rc == 2
  when: patch.examined > 0

- name: "Update ROM version"
  lineinfile:
    path: "{{ SRCPATH }}/build/make/core/build_id.mk"
    regexp: BUILD_ID=.*
    line: "BUILD_ID={{ ROM_NAME }}-v{{ ROM_VERSION }}"
    state: present

# this overwrites everything otherwise
- name: "Wipe Pixel board config"
  ansible.builtin.shell: echo > build/make/target/board/BoardConfigPixelCommon.mk
  args:
    chdir: "{{ SRCPATH }}"

- name: "Set Emergency Call threshold"
  ansible.builtin.lineinfile:
    path: "{{ SRCPATH }}/frameworks/base/services/core/java/com/android/server/GestureLauncherService.java"
    regexp: "EMERGENCY_GESTURE_POWER_TAP_COUNT_THRESHOLD\s+=\s+.*;"
    line: "EMERGENCY_GESTURE_POWER_TAP_COUNT_THRESHOLD = {{ emergency_gesture_power_tap_count_threshold }};"
  when: emergency_gesture_power_tap_count_threshold is defined
