---

hypatia_signatures_path: /srv/sigdb
hypatia_clam_tmp: /tmp/mss
hypatia_www_user: www-data
sigdb_bin_path: "{{ hypatia_signatures_path }}/production/"
hypatia_index_html: "{{ hypatia_signatures_path }}/index.html"
hypatia_extended_html: "{{ hypatia_signatures_path }}/extended.html"
lovelace_www_root_path: /var/www/html/db

# URI sources
hypatia_uri_amnestytech: "https://github.com/amnestytech/investigations"
hypatia_uri_avast: "https://github.com/avast/covid-19-ioc"
hypatia_path_clamav: "/var/lib/clamav"
hypatia_uri_eset: "https://github.com/eset/malware-ioc"
hypatia_uri_cybercure: "https://api.cybercure.ai/feed/get_hash?type=csv"
hypatia_uri_threatview_md5: "https://threatview.io/Downloads/MD5-HASH-ALL.txt"
hypatia_uri_threatview_sha: "https://threatview.io/Downloads/SHA-HASH-FEED.txt"
hypatia_uri_threatfox: "https://threatfox.abuse.ch/export/csv/sha256/full/"
hypatia_uri_sanesecurity: "rsync://rsync.sanesecurity.net/sanesecurity"
hypatia_uri_stalkerware: "https://github.com/AssoEchap/stalkerware-indicators"
hypatia_uri_targetedthreats: "https://github.com/botherder/targetedthreats"
hypatia_uri_blocklist_various: "https://github.com/scafroglia93/blocklists"
hypatia_uri_umair9747: "https://github.com/umair9747/datasets"
hypatia_uri_virusshare_base: "https://virusshare.com/hashfiles/VirusShare_00"
hypatia_uri_zimperium: "https://github.com/Zimperium/IOC"
hypatia_uri_malware_bazaar: "https://bazaar.abuse.ch/export/txt/sha256/full/" # "https://bazaar.abuse.ch/export/txt/sha256/recent/"
hypatia_uri_malware_hunter: "https://figshare.com/ndownloader/files/42804604"
hypatia_uri_malicioushash_base: "https://raw.githubusercontent.com/romainmarcoux/malicious-hash/main/full-hash-"
hypatia_uri_signaturebase: "https://raw.githubusercontent.com/Neo23x0/signature-base/refs/heads/master/iocs/hash-iocs.txt"
hypatia_uri_signaturebase_otx: "https://raw.githubusercontent.com/Neo23x0/signature-base/496acc5a1260bfaf58963e90d1c1325b24c10b10/iocs/otx-hash-iocs.txt"
hypatia_uri_malshare: "https://malshare.com/api.php?api_key=${APIKEY}&action=getlist"  # see {{ hypatia_signatures_path }}/malshare/download.sh to replace the APIKEY!
hypatia_uri_hagezi_threats: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt"
hypatia_uri_hagezi_fakes: "https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/wildcard/fake-onlydomains.txt"

# LOCAL sources
hypatia_malsharedb_path: "{{ hypatia_signatures_path }}/malshare/malshare.sha256"
hypatia_imported_path: "{{ hypatia_signatures_path }}/hypatia"
hypatia_testfiles_path: "{{ hypatia_signatures_path }}/selftest"

# malware-hunter (wget https://figshare.com/ndownloader/files/42804604 -O malware-hunter/MH-100K-dataset.zip)
#hypatia_path_malwarehunter: /srv/sigdb/malware-hunter

# extended signatures:
# wget -O VirusShare_0-475_MR4n6_Hash_Sets_RAW_2023_Q2.zip "<dl-link>" taken from:
# https://downloads.sourceforge.net/project/mantarayforensics/VirusShare_Hash_Sets/RAW/VirusShare_0-475_MR4n6_Hash_Sets_RAW_2023_Q2.zip

# converter to hypatia format
hypatia_path_converter: "/opt/dbconverter.jar"
hypatia_uri_converter: "https://codeberg.org/AXP-OS/tools_lovelaceav_convertdb/releases/download/latest/dbconverter.jar"
