---

- include_vars: "../../{{ target_model }}/vars/main.yml"
- include_vars: "../../common/tasks/axp-slim.vars.yml
  #no_log: true
  when: (axp_type | d(ROM_FLAVOR)) == "slim"

- name: Set combined device + kernel list
  set_fact:
    all_device_repos: >-
      {{ (
          axp_git_push_device_include.split('|') + 
          axp_git_push_vendor_include.split('|') + 
          [target_kernel_dir | regex_replace('/', '_')]
      )| unique }}

- name: DEBUG
  ansible.builtin.debug:
    msg: |
      target_model: {{ target_model }}
      axp_switchMR_upstream_branch: {{ los_version_gitbranch }}
      axp_switchMR_target_branch: {{ git_repo_local_manifests_branch }}
      all_device_repos: {{ all_device_repos }}

- include_tasks: setup_otaverify.yml
  when: not skip_setup_otaverify
  
- name: "Include device tasks for each push target"
  include_tasks: setup_repos.yml
  loop: "{{ all_device_repos }}"
  loop_control:
    loop_var: device_repo
  vars:
    target_model: "{{ target_model }}"
    axp_switchMR_upstream_branch: "{{ los_version_gitbranch }}"
    axp_switchMR_target_branch: "{{ git_repo_local_manifests_branch }}"
    device_tree: "{{ device_repo }}"
  when: not skip_setup_repos

- include_tasks: setup_vendor_firmware.yml
  when: not skip_setup_firmware
- include_tasks: setup_manifest.yml
  when: not skip_setup_manifest
- include_tasks: setup_ansible.yml
  when: not skip_setup_ansible
- include_tasks: setup_website.yml
  when: not skip_setup_website

- include_tasks: setup_semaphore.yml
  vars:
    semaphore_aos_template_name: "AOS {{ git_repo_local_manifests_branch | upper | regex_replace('AXP-','') }} {{ axp_type }}: {{ target_model_full }} ({{ target_model }})"
  when: not skip_setup_semaphore
