---

- include_vars: "../../{{ target_model }}/vars/main.yml"

- name: Set combined device + kernel list
  set_fact:
    all_device_repos: >-
      {{ (
          axp_git_push_device_include.split('|') + 
          axp_git_push_vendor_include.split('|') + 
          [target_kernel_dir | regex_replace('/', '_')]
      )| unique }}

- name: DEBUG
  ansible.builtin.debug:
    msg: |
      target_model: {{ target_model }}
      axp_switchMR_upstream_branch: {{ los_version_gitbranch }}
      axp_switchMR_target_branch: {{ git_repo_local_manifests_branch }}
      all_device_repos: {{ all_device_repos }}

- include_tasks: setup_manifest.yml

- name: "Include device tasks for each push target"
  include_tasks: setup_repos.yml
  loop: "{{ all_device_repos }}"
  loop_control:
    loop_var: device_repo
  vars:
    target_model: "{{ target_model }}"
    axp_switchMR_upstream_branch: "{{ los_version_gitbranch }}"
    axp_switchMR_target_branch: "{{ git_repo_local_manifests_branch }}"
    device_tree: "{{ device_repo }}"

- include_tasks: setup_semaphore.yml
  vars:
    semaphore_aos_template_name: "AOS {{ git_repo_local_manifests_branch | upper | regex_replace('AXP-','') }} {{ axp_type }}: {{ target_model_full }} ({{ target_model }})"
