---

- include_tasks: loop.yml
  when: axp_switchMR_all_devices is undefined
  
- block:
  
  - name: "Identify ALL models"
    connection: local
    ansible.builtin.shell: |
      ls -1 ../roles/{{ parse_roles_subdir }} | grep -vE "{{ model_exclusions }}"
    register: target_models
  
  - include_tasks: loop.yml
    vars:
      target_model: "{{ model }}"
    loop: "{{ target_models.stdout_lines }}"
    loop_control:
      loop_var: model

  when: axp_switchMR_all_devices is defined and axp_switchMR_all_devices | bool
