---

- ansible.builtin.set_fact:
    init_device_temp_path: "{{ android_build_path }}/.tmp/init_otaverify"

- name: "Setup OTA verifier: Start clean"
  ansible.builtin.file:
      path: "{{ init_device_temp_path }}"
      state: absent

- block:

        - name: "Setup OTA verifier: fetch git repo"
          ansible.builtin.git:
            repo: "{{ init_device_otaverifier_repo }}"
            dest: "{{ init_device_temp_path }}"
          timeout: 180
        
        - name: "Setup OTA verifier: add/update OTA key"
          ansible.builtin.shell: |
            cp {{ keysdir }}/releasekey_OTA.pub {{ os_name }}/{{ sub_model | d(target_model) }}_AXP.OS_pubkey
          args:
              chdir: "{{ init_device_temp_path }}"
              executable: /bin/bash
        
        - name: "Setup OTA verifier: add/update AVB key"
          ansible.builtin.shell: |
            cp {{ keysdir }}/avb_pkmd.bin {{ os_name }}/{{ sub_model | d(target_model) }}_AXP.OS_avb_pkmd.bin
          args:
              chdir: "{{ init_device_temp_path }}"
              executable: /bin/bash
          when: hugo_relockable == "yes"
        
        - name: "Setup OTA verifier: add & push changes"
          ansible.builtin.shell: |
              echo "[GIT][OTAVERIFY] starting git commit process" >> {{ BUILD_LOG }}
              source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}
            
              CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
              if [ $CMTL -gt 0 ];then
                  git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
                  git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "axp: {{ sub_model | d(target_model) }}: added/updated OTA/AVB key(s)" >> {{ BUILD_LOG }} 2>&1
                  echo "[GIT][OTAVERIFY] git commit done" >> {{ BUILD_LOG }}
        
                  CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
                  REMHASH=$(git log --pretty=oneline --decorate | grep "origin/{{ git_repo_local_manifests_branch }}" |cut -d ' ' -f1)
                    
                  if [ "$CURHASH" != "$REMHASH" ]; then
                      echo "[GIT][OTAVERIFY] pushing required ($CURHASH != $REMHASH)!" >> {{ BUILD_LOG }}
                      git push origin {{ init_device_website_branch }} >> {{ BUILD_LOG }} 2>&1
                  else
                      echo "[GIT][OTAVERIFY] pushing skipped ($CURHASH == $REMHASH)!" >> {{ BUILD_LOG }}
                  fi
              else
                   echo "[GIT][OTAVERIFY] git commit skipped (no changes)" >> {{ BUILD_LOG }}
              fi
          args:
              chdir: "{{ init_device_temp_path }}"
              executable: /bin/bash
        
        - name: "Setup OTA verifier: End clean"
          ansible.builtin.file:
              path: "{{ init_device_temp_path }}"
              state: absent

  rescue:

        - name: "Setup OTA verifier: End clean"
          ansible.builtin.file:
              path: "{{ init_device_temp_path }}"
              state: absent
