---
# https://semaphoreui.com/api-docs/#/

- name: "Setup semaphore: get current semaphore templates"
  connection: local
  ansible.builtin.uri:
    url: "{{ semaphore_api_uri }}/project/{{ semaphore_aos_template_project_id }}/templates?sort=name&order=asc"
    method: GET
    headers:
        Content-Type: application/json
        Authorization: "Bearer {{ vault_semaphore_api_aos_rw }}"
  register: sp_all_templates
  no_log: true

- name: "Setup semaphore: get current semaphore variable groups"
  connection: local
  ansible.builtin.uri:
    url: "{{ semaphore_api_uri }}/project/{{ semaphore_aos_template_project_id }}/environment?sort=name&order=desc"
    method: GET
    headers:
        Content-Type: application/json
        Authorization: "Bearer {{ vault_semaphore_api_aos_rw }}"
  register: sp_all_envs
  no_log: true

- name: "Extract environment ID for given name"
  ansible.builtin.set_fact:
    semaphore_aos_template_env_id: >-
      {{ sp_all_envs.json | selectattr('name', 'equalto', semaphore_aos_template_env_name) | map(attribute='id') | first }}

- name: "Setup semaphore: create semaphore template"
  connection: local
  ansible.builtin.uri:
    url: "{{ semaphore_api_uri }}/project/{{ semaphore_aos_template_project_id }}/templates"
    method: POST
    headers:
        Content-Type: application/json
        Authorization: "Bearer {{ vault_semaphore_api_aos_rw }}"
    body_format: json
    body: >-
        { "project_id": {{ semaphore_aos_template_project_id }},
        "inventory_id": {{ semaphore_aos_template_inventory_id }},
        "repository_id": {{ semaphore_aos_template_repo_id }},
        "environment_id": {{ semaphore_aos_template_env_id | int }},
        "view_id": {{ semaphore_aos_template_view_id }},
        "name": "{{ semaphore_aos_template_name }}",
        "app": "ansible",
        "playbook": "{{ semaphore_aos_template_playbook }}",
        "description": "{{ semaphore_aos_template_desc }}",
        "arguments": "[\"-vv\",\"-e axp_type=slim\"]",
        "survey_vars": {{ semaphore_aos_template_survey_vars }},
        "vaults": {{ semaphore_aos_template_vaults }},
        "type": "deploy",
        "allow_override_args_in_task": false }
    status_code: [ 201, 200 ]
  register: tmplc
  changed_when: tmplc.status == 201
  when: semaphore_aos_template_name not in sp_all_templates.json | map(attribute='name') | list
  no_log: true
