---

- ansible.builtin.set_fact:
    init_device_temp_path: "{{ android_build_path }}/.tmp/init_repo"

- name: "Setup repositories: Start clean"
  ansible.builtin.file:
      path: "{{ init_device_temp_path }}"
      state: absent

- block:

    - name: "Setup repositories: Create public/private repo"
      ansible.builtin.shell: |
        {{ DOS_INIT }}    
        upstream_branch="{{ axp_switchMR_upstream_branch }}"; axp_release="{{ axp_switchMR_target_branch }}"; push_req=0; create_req=0
    
        echo -e "\n###########################################################"  >> {{ BUILD_LOG }}
        echo -e "# STARTING: {{ device_tree }}"  >> {{ BUILD_LOG }}
        echo -e "###########################################################"  >> {{ BUILD_LOG }}
    
        if [[ "{{ device_tree }}" =~ vendor_.* ]]; then
            GHORG=TheMuppets; reponame=proprietary_{{ device_tree }}; private=1
        else
            GHORG=LineageOS; reponame=android_{{ device_tree }}; private=0
        fi
        echo "[GIT] GHORG = $GHORG" >> {{ BUILD_LOG }}
        
        git clone {{ git_axpos_org_private }}/$reponame {{ init_device_temp_path }} >> {{ BUILD_LOG }} 2>&1 || create_req=1
        if [ $create_req -eq 0 ];then echo "[GIT] cloned {{ git_axpos_org_private }}/$reponame -> {{ init_device_temp_path }}" >> {{ BUILD_LOG }}; fi
    
        if [ $create_req -eq 1 ];then
          echo "[GIT] repo {{ git_axpos_org_private }}/$reponame does not exist within the org yet! Creating $reponame ..." >> {{ BUILD_LOG }}
          echo "[GIT] Forking new repo: {{ git_axpos_org_private }}/$reponame from: github.com/$GHORG/$reponame" >> {{ BUILD_LOG }}
          tea repo migrate --login {{ git_axpos_org_private_login }} --owner {{ git_axpos_org_name }} --name $reponame --lfs true --service git --clone-url https://github.com/$GHORG/$reponame >> {{ BUILD_LOG }} 2>&1

          # set description & issues
          curl -sX 'PATCH' \
            "https://{{ git_axpos_org_private_host }}/api/v1/repos/{{ git_axpos_org_name }}/$reponame" \
            -H "Authorization: token {{ vault_axp_private_repo_token_rw }}" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d  '{
                  "description": "Mirror of: https://github.com/'$GHORG/$reponame'",
                  "has_issues": true,
                  "default_branch": "{{ axp_switchMR_upstream_branch }}",
                  "external_tracker": {
                    "external_tracker_format": "https://{{ git_axpos_org_private_host }}/AXP.OS-public/issue-tracker/issues/{index}",
                    "external_tracker_url": "https://{{ git_axpos_org_private_host }}/AXP.OS-public/issue-tracker/issues",
                    "external_tracker_style": "alphanumeric"
                    }
                }' >> {{ BUILD_LOG }} 2>&1       
          git clone {{ git_axpos_org_private }}/$reponame {{ init_device_temp_path }} >> {{ BUILD_LOG }} 2>&1
          echo "[GIT] {{ git_axpos_org_private }}/$reponame created..." >> {{ BUILD_LOG }}
        fi
      args:
        executable: /bin/bash
        
    - name: "Setup repositories for AXP.OS: Git branches & Upstream"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        upstream_branch="{{ axp_switchMR_upstream_branch }}"; axp_release="{{ axp_switchMR_target_branch }}"; push_req=0; create_req=0
        cd {{ init_device_temp_path }}
        
        if [[ "{{ device_tree }}" =~ vendor_.* ]]; then
            GHORG=TheMuppets; reponame=proprietary_{{ device_tree }}; private=1
        else
            GHORG=LineageOS; reponame=android_{{ device_tree }}; private=0
        fi
        echo "[GIT] GHORG = $GHORG" >> {{ BUILD_LOG }}
        
        echo "[GIT] checking out origin/$upstream_branch" >> {{ BUILD_LOG }}
        create_br=0
        git fetch origin $upstream_branch  >> {{ BUILD_LOG }} 2>&1 || true
        git checkout $upstream_branch  >> {{ BUILD_LOG }} 2>&1 || create_br=1
        git remote add up https://github.com/$GHORG/$reponame >> {{ BUILD_LOG }} 2>&1
        git fetch up $upstream_branch >> {{ BUILD_LOG }} 2>&1

        if [ $create_br -eq 1 ];then
            echo "[GIT] checking out up/$upstream_branch instead of origin (does not exist yet)" >> {{ BUILD_LOG }}
            git checkout -b "$upstream_branch" up/$upstream_branch  >> {{ BUILD_LOG }} 2>&1
        fi
        
        BROKENLFS=$(grep -c undocumented .lfsconfig || echo 0)
        if [ $BROKENLFS -eq 0 ]; then git lfs fetch --all;fi

        git checkout --track origin/$axp_release >> {{ BUILD_LOG }} 2>&1 || (git checkout $axp_release >> {{ BUILD_LOG }} 2>&1 || git checkout -b $axp_release >> {{ BUILD_LOG }} 2>&1)
        git remote -v >> {{ BUILD_LOG }} 2>&1
      args:
        executable: /bin/bash
        chdir: "{{ init_device_temp_path }}"
    
    - name: "Setup repositories: include AXP.OS (common tree)"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        upstream_branch="{{ axp_switchMR_upstream_branch }}"; axp_release="{{ axp_switchMR_target_branch }}"; push_req=0; create_req=0
        cd {{ init_device_temp_path }}
    
        if [[ "{{ device_tree }}" =~ vendor_.* ]]; then
            GHORG=TheMuppets; reponame=proprietary_{{ device_tree }}; private=1
        else
            GHORG=LineageOS; reponame=android_{{ device_tree }}; private=0
        fi
        echo "[GIT] private = $private" >> {{ BUILD_LOG }}
        
        if [ "{{ target_model_common_tree }}" == "{{ device_tree }}" ];then
          echo "[GIT] checking AXP.OS common tree include.." >> {{ BUILD_LOG }}
          
          grep -q "vendor/axp/config/common.mk" {{ target_model_device_tree_mk }} \
            || echo -e '\n# enable AXP.OS vendor\n$(call inherit-product, vendor/axp/config/common.mk)' >> {{ target_model_device_tree_mk }}    
          
          CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
          if [ $CMTL -gt 0 ];then
              git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
              git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "board/device: enable AXP.OS" >> {{ BUILD_LOG }} 2>&1
              echo "[GIT] git commit done" >> {{ BUILD_LOG }}
              push_req=$(( push_req + 1))
          fi
        fi
      args:
        executable: /bin/bash
        chdir: "{{ init_device_temp_path }}"
        
    - name: "Setup repositories: LFS"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        upstream_branch="{{ axp_switchMR_upstream_branch }}"; axp_release="{{ axp_switchMR_target_branch }}"; push_req=0; create_req=0
        cd {{ init_device_temp_path }}
        CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
        
        if [[ "{{ device_tree }}" =~ vendor_.* ]]; then
            GHORG=TheMuppets; reponame=proprietary_{{ device_tree }}; private=1
        else
            GHORG=LineageOS; reponame=android_{{ device_tree }}; private=0
        fi
        echo "[GIT] GHORG = $GHORG" >> {{ BUILD_LOG }}

        for work in $axp_release $upstream_branch; do
            git checkout $work >> {{ BUILD_LOG }}
            for lf in $(find . -type f -size +2M -name '*.*'| while read file; do f="${file##*.}"; [ ${{ "{" }}{{ "#" }}f} -ge 2 ] && echo "$f" ; done | sort -u);do
              git lfs track \"*.${lf}\" >> {{ BUILD_LOG }} 
            done
        
            CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
            if [ $CMTL -gt 0 ];then
              git add -A .  >> /dev/null 2>> {{ BUILD_LOG }} \
                && git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: track files bigger than 2M"  >> /dev/null 2>> {{ BUILD_LOG }}
            fi
        done
      args:
        executable: /bin/bash
        chdir: "{{ init_device_temp_path }}"
        
    - name: "Setup repositories: CI/CD"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        upstream_branch="{{ axp_switchMR_upstream_branch }}"; axp_release="{{ axp_switchMR_target_branch }}"; push_req=0; create_req=0
        cd {{ init_device_temp_path }}
        
        if [[ "{{ device_tree }}" =~ vendor_.* ]]; then
            GHORG=TheMuppets; reponame=proprietary_{{ device_tree }}; private=1
        else
            GHORG=LineageOS; reponame=android_{{ device_tree }}; private=0
        fi
        echo "[GIT] GHORG = $GHORG" >> {{ BUILD_LOG }}
              
        git checkout $axp_release

        workflowpath=".gitea"
        if [ ! -f $workflowpath/workflows/sync_upstream.yml ];then
              mkdir -p $workflowpath/workflows/ 2>/dev/null || true
              if [ -f $workflowpath/workflows/sync.yml ];then rm $workflowpath/workflows/sync.yml; fi
              
              echo "[GIT] adding CI/CD to repo (branch: $axp_release)" >> {{ BUILD_LOG }}
        {% raw %}
              cat > $workflowpath/workflows/sync_upstream.yml <<EOSYNC
        name: "Sync with upstream"
    
        on:
            workflow_dispatch:
            schedule:
              - cron: "$(( RANDOM % 60 )) $(( RANDOM % 24 )) * * *"
    
        jobs:
            sync-upstream:
              name: "Sync with upstream"
              runs-on: docker-node-latest
              uses: https://codeberg.org/AXP-OS/actions/.gitea/workflows/sync_upstream.yaml@main
              with:
                  remote-server: github.com
                  remote-repo: $GHORG/\${{ github.event.repository.name }}
                  remote-branch: $upstream_branch
                  local-repo: \${{ github.repository_owner }}/\${{ github.event.repository.name }}
                  local-branch: "$(git branch --no-color --show-current)"
                  dryrun: false
              secrets: inherit
        EOSYNC
        {% endraw %}
              git add -f $workflowpath/ >> {{ BUILD_LOG }} 2>&1 || CMT=1
              CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
              if [ $CMTL -gt 0 ];then
                  git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "ci: enable upstream sync" >> {{ BUILD_LOG }} 2>&1
                  push_req=$(( push_req + 1))
                  echo "[GIT] git commit added for ci/cd" >> {{ BUILD_LOG }}
                  git show >> {{ BUILD_LOG }}
              fi
        else
          echo "Skipped adding CI/CD sync to device tree (already configured)." >> {{ BUILD_LOG }} 2>&1
        fi
      args:
        executable: /bin/bash
        chdir: "{{ init_device_temp_path }}"
        
    - name: "Setup repositories: Git push"
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        upstream_branch="{{ axp_switchMR_upstream_branch }}"; axp_release="{{ axp_switchMR_target_branch }}"; push_req=0; create_req=0; reponame="{{ device_tree }}"
        cd {{ init_device_temp_path }}

        ####### UPSTREAM HANDLING #########
        git checkout $upstream_branch
        git config --file .lfsconfig lfs.pushurl {{ git_axpos_org_private }}/$reponame
        git add -A .  >> /dev/null 2>> {{ BUILD_LOG }} \
            && git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: set pushurl"  >> /dev/null 2>> {{ BUILD_LOG }}
        git lfs fetch up  >> {{ BUILD_LOG }} 2>&1
        
        CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
        REMHASH=$(git log --pretty=oneline --decorate | grep "origin/$upstream_branch" |cut -d ' ' -f1)
        
        if [ "$CURHASH" != "$REMHASH" ]; then
          echo "[GIT] pushing required ($CURHASH != $REMHASH)!" >> {{ BUILD_LOG }}
          git push --force origin $upstream_branch:refs/heads/upstream_{{ axp_switchMR_target_branch | regex_replace('axp-','') }} >> {{ BUILD_LOG }} 2>&1
          echo "[GIT] Pushed $reponame / $upstream_branch!" >> {{ BUILD_LOG }} 2>&1
        else
          echo "Skipped pushing $reponame / $upstream_branch (no changes were made)."  >> {{ BUILD_LOG }} 2>&1
        fi

        ####### AXP HANDLING #########
        git checkout $axp_release
        git config --file .lfsconfig lfs.pushurl {{ git_axpos_org_private }}/$reponame
        git add -A .  >> /dev/null 2>> {{ BUILD_LOG }} \
            && git commit {{ git_commit_args | d('') }} --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "lfs: set pushurl"  >> /dev/null 2>> {{ BUILD_LOG }}
        git lfs fetch origin  >> {{ BUILD_LOG }} 2>&1

        CURHASH=$(git log -1 --format=oneline | cut -d ' ' -f1)
        REMHASH=$(git log --pretty=oneline --decorate | grep "origin/$axp_release" |cut -d ' ' -f1)

        if [ "$CURHASH" != "$REMHASH" ]; then
          echo "[GIT] pushing required ($CURHASH != $REMHASH)!" >> {{ BUILD_LOG }}
          git push origin $axp_release >> {{ BUILD_LOG }} 2>&1
          echo "[GIT] Pushed $reponame / $axp_release!" >> {{ BUILD_LOG }} 2>&1
        else
          echo "Skipped pushing $reponame / $axp_release (no changes were made)."  >> {{ BUILD_LOG }} 2>&1
        fi
        
        sleep 10              
        curl -siX PATCH -H "Content-Type: application/json" \
              -H "Authorization: token {{ vault_axp_private_repo_token_rw }}" \
              -d '{"default_branch": "'$axp_release'"}'\
              "https://{{ git_axpos_org_private_host }}/api/v1/repos/{{ git_axpos_org_name }}/$reponame"
        echo "[GIT] default branch in $reponame set to $axp_release!" >> {{ BUILD_LOG }}
            
        echo -e "###########################################################"  >> {{ BUILD_LOG }}
        echo -e "# ENDED: $reponame"  >> {{ BUILD_LOG }}
        echo -e "###########################################################\n"  >> {{ BUILD_LOG }}
      args:
        executable: /bin/bash
        chdir: "{{ init_device_temp_path }}"
    
    - name: "Setup repositories: End clean"
      ansible.builtin.file:
          path: "{{ init_device_temp_path }}"
          state: absent

  rescue:

    #- name: "Setup repositories: End clean"
    #  ansible.builtin.file:
    #      path: "{{ init_device_temp_path }}"
    #      state: absent

    - name: "Setup repositories: failed"
      ansible.builtin.fail:
        msg: |
          ERROR OCCURED:
          
          {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
          
          See above for details.

  when:
      - not (git_pixel_kernel_manifest_branch is defined and target_model_vendor == "Google" and 'kernel' in device_tree)

