---

- name: "Setup repositories: run activate-mirror action"
  connection: local
  ansible.builtin.uri:
    url: "https://{{ git_axpos_org_private_host }}:{{ git_axpos_org_private_host_port | d('443') }}/api/v1/repos/{{ git_axpos_org_name }}/{{ git_axpos_actions_workflow_repo }}/actions/workflows/{{ git_axpos_actions_workflow_id }}/dispatches"
    method: POST
    headers:
        Content-Type: application/json
        Authorization: "Bearer {{ vault_axp_private_repo_token_rw }}"
    body_format: json
    body: >-
        { "inputs": {
            "repooverride": "{{ all_repos_filtered | join(' ') }}"
          },
          "ref": "{{ git_axpos_actions_workflow_repo_branch }}"
          }
    status_code: 204
