---

#################################################################################################################################
## Device info

# human readable model name
target_model_vendor: "Google"
target_model_name: 'Pixel 3'

target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# path to the kernel dir
# e.g. "kernel/oneplus/msm8998"
target_kernel_dir: "kernel/google/msm-4.9"

# DEPRECATED: patching boardconfig instead
# custom CLANG override, otherwise it would fallback to ccache
# see: vendor/lineage/build/tasks/kernel.mk
#axp_pre_build_cmd: |-
#    export KERNEL_CLANG_PATH=$PWD/prebuilts/clang/kernel/linux-x86/clang-r416183b
#    export PATH=$KERNEL_CLANG_PATH/bin:$PATH
# export KERNEL_CC="CC=\"$PWD/prebuilts/clang/host/linux-x86/${CLANG_VERSION}/bin/clang\""

# path to the common tree, if none exists then the device tree.
# used e.g. for git, vendor/axp, release handling etc
target_model_common_tree: "android_device_google_crosshatch" # e.g. device_oneplus_msm8998-common

target_model_device_tree: device_{{ target_model_vendor | lower() }}_{{ target_model | lower() }}

# add OpenEUICC
axp_euicc_capable: true

# boot debugger mount point
# path for boot_debug, must be identified within the device / common tree fstab:
# - must be a writable partition
# - must be a mountable partition (ext2, ext4, f2fs, ..)
# usually one of: /mnt/vendor/persist, /metadata or /cache
extendrom_debug_path_default: "/metadata"

extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# git push project names related to this device. used for device init, reproducible builds, ci/cd
axp_git_push_device_include: "{{ target_model_device_tree }}|{{ target_model_common_tree }}"

# all used VENDOR paths for this device, e.g. "vendor_google_crosshatch|vendor_google_blueline"
axp_git_push_vendor_include: >-
    {{ target_model_device_tree | replace('android_device_', 'proprietary_vendor_') }}
    |{{ target_model_common_tree | replace('android_device_', 'proprietary_vendor_') }}

# MIGHT be required for slim?!
# remove disk space reservation (e.g. on product partition)
#remove_space_reservation: true

#################################################################################################################################
## Website info

# COMMON block
# do we include vendor firmware?
# 1. open https://code.binbash.rocks/AXP.OS/vendor_firmware
# 2. select the correct `branch` _(must match the AXP.OS Android version, e.g. "axp-a15")_
# 3. click the folder with the `codename` for your device
# 4. If there is a folder with the device's codename (e.g. `enchilada`):
#   - check the file `AndroidBoardVendor.mk`: It should contain several `$(call add-radio-file.....` lines
# If steps 1-4 were successful set "included" otherwise "manual"
hugo_firmware: "included"

# Is the device an A/B device (legacy or virtual)?
# A/B? -> https://source.android.com/docs/core/ota/virtual_ab
# How to identify:
# - https://www.xda-developers.com/list-android-devices-seamless-updates/
# - General Rules:
#   Android 13+: (Virtual) A/B
#   Android 11+: A/B
#   Google Pixel: Every Google Pixel device ever released uses A/B partitions.
#   Samsung: not before 2024 and even then need to be verified
# - Manual Verification Method
#   adb shell getprop ro.boot.slot_suffix
#   -> if it returns _a or _b, it is an A/B device.
#   -> if it returns nothing, it is an A-only device.
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'yes'

hugo_xda_link: "TBD" # link to the AXP.OS XDA post for that device
hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=63"

# one block, either PRO / SLIM depending on your request

# PRO block
android_version_pro: 15
hugo_relockable_pro: 'yes'
hugo_encryption_pro: "ICE" # device encryption supported: no|FDE|FBEv1|FBEv2
hugo_axp_bootloader_id_pro: |
    BOOTLOADER minimal ID (AVB 2)
        D0AD4BDE

    BOOTLOADER full ID:
        D0AD4BDE794F5D82
        AABC3AA34C5450B9
        25E3B1F3025AFA4A
        CA5045A30B1C8338
hugo_supportlevel_pro: "community"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "WIP" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device

# SLIM block
android_version_slim: 15
hugo_relockable_slim: 'yes'
hugo_encryption_slim: "ICE" # device encryption supported: no|FDE|FBEv1|FBEv2
#hugo_axp_bootloader_id_slim: | # if AVB: the bootloader id string (from build log)
hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
hugo_first_releasedate_slim: "TBD" # first public stable release date (YYYY-MM-DD)
hugo_state_slim: "!! ALPHA !!" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device

#################################################################################################################################
## Firmware info
##
# source: https://developers.google.com/android/ota#blueline

vendor_firmware_version: "blueline-ota-sp1a.210812.016.c2-f7ebc6b3" # filename without zip

# direct download link to the OTA zip of the vendor.
vendor_firmware_download_url: "https://dl.google.com/dl/android/aosp/{{ vendor_firmware_version }}.zip"
vendor_firmware_download_sha256: "f7ebc6b326be1b40355d1e0b6d5e5e73204878f3419dec954eb35e1677bb12a1"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_firmware_version }}.zip"
#################################################################################################################################

#################################################################################################################################
## FACTORY info (only relevant for: Google Pixel, Fairphone)
##
#
# source: https://developers.google.com/android/images#blueline

vendor_factory_download_sha256: "fa981d87b6b28a1996161accbb147f46fe29663bb2ce6cc13dc9e500cbc59c93"

vendor_factory_id: "sp1a.210812.016.c2"   # e.g. tq3a.230805.001.s1
vendor_factory_hash: "fa981d87"  # e.g. 82902ea9
vendor_factory_version: "{{ target_model }}-{{ vendor_factory_id }}-factory-{{ vendor_factory_hash }}"
vendor_factory_download_url: "https://dl.google.com/dl/android/aosp/{{ vendor_factory_version }}.zip"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though. persistent_dir is always a device specific path.
vendor_factory_persistent_path: "{{ persistent_dir }}/{{ android_shortversion }}_{{ vendor_factory_version }}.zip"
#################################################################################################################################
