---

- name: "Build mAid"
  hosts: buildmaidserver
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/env python3

  pre_tasks:
    - set_fact:
        semaphore_runfile: "{{ semaphore_lock_dir }}/{{ ROM_FLAVOR }}_{{ semaphore_vars.task_details.target_version }}.ansible_running"
        
  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
      - include_vars: ../roles/build_mAid/vars/main.yml
        no_log: true

      - import_role:
          name: common

      - debug:
          var: vault_tg_group_id_failing

      - fail:
          msg: "boo.. vault_tg_group_id_failing is undefined"
        when: vault_tg_group_id_failing is undefined

      - name: "set semaphore running indicator"
        connection: local
        copy:
          dest: "{{ semaphore_runfile }}"
          content: |
            date="{{ ansible_date_time.iso8601 }}"
            play=build_mAid.yml
            role="{{ ROM_FLAVOR }}"

      - import_role:
          name: pre

      - include_role:
          name: build_mAid
          public: true

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_automation }}"
        when: 
          - debug_build is not defined or (debug_build is defined and debug_build == "false")
          - telegram_notifications | bool

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
        when: debug_build is defined and debug_build == "true"

      - include_role:
          name: notify

      - name: "remove semaphore running indicator"
        connection: local
        file:
          path: "{{ semaphore_runfile }}"
          state: absent

      - import_role:
          name: post

      # when any of the above fails notify always 
      rescue:
        - import_role:
            name: post
          ignore_errors: true

        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"

        - include_vars: ../roles/build_mAid/vars/main.yml
          no_log: true
          
        - include_role:
            name: notify

        - name: "remove semaphore running indicator"
          connection: local
          file:
            path: "{{ semaphore_runfile }}"
            state: absent

        - fail:
            msg: "build failure occured. check log."
