---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: true

  pre_tasks:
    - debug:
        msg: "{{ semaphore_vars }}"

    - name: ensure semaphore run dir
      connection: local
      file:
        path: "{{ semaphore_lock_dir }}"
        state: directory
          
    - set_fact:
        semaphore_runfile: "{{ semaphore_lock_dir }}/{{ ROM_FLAVOR }}_{{ target_model }}_{{ build_id }}.ansible_running"

    - name: "set semaphore running indicator"
      connection: local
      copy:
        dest: "{{ semaphore_runfile }}"
        content: |
          date="{{ ansible_date_time.iso8601 }}"
          play=build.yml
          target={{ target_model }}
          role="{{ ROM_FLAVOR }}/{{ target_model }}"

    - name: DEBUG-pre
      ansible.builtin.debug:
        var: axp_type

    - name: DEBUG-pre2
      ansible.builtin.debug:
        var: just_git_push

    - name: DEBUG-pre3
      ansible.builtin.debug:
        var: download_fairphone_firmware
          
    - import_role:
        name: pre        
          
  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
    
      - import_role:
          name: common

      - name: DEBUG
        ansible.builtin.debug:
          var: axp_type

      - include_role:
          name: "{{ ROM_FLAVOR }}/common"
          public: yes
        when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"

      - fail:
          msg: "boo.. vault_tg_group_id_failing is undefined"
        when: 
          - vault_tg_group_id_failing is undefined
          - telegram_notifications | bool

      - include_vars: "../roles/{{ ROM_FLAVOR }}/all/vars/{{ target_model }}.yml"
        when: 
          - ROM_FLAVOR == "SHRP" or ROM_FLAVOR == "TWRP"

      - include_role:
          name: "roles/{{ ROM_FLAVOR }}/{{ target_model }}"
          public: yes

      - include_vars: "{{ ROM_FLAVOR }}/common/tasks/axp_lowend_device.vars.yml
        when: axp_lowend_device

      - include_role:
          name: build
          public: yes

      - include_role:
          name: release
          public: yes
        when:
          - (override_release_build == "undef" and release_build | bool) or (override_release_build | bool)
          - not build_bootimage_only | d(False)

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_automation }}"
        when:
          - debug_build is not defined or (debug_build is defined and not debug_build | bool)
          - telegram_notifications | bool

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
        when:
          - debug_build is defined and debug_build | bool
          - telegram_notifications | bool

      - include_role:
          name: notify

      - name: "remove semaphore running indicator"
        connection: local
        file:
          path: "{{ semaphore_runfile }}"
          state: absent

      - include_role:
          name: post

      # when any of the above fails notify always 
      rescue:

        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
          when:
            - telegram_notifications | bool

        - include_role:
            name: notify

        - name: "remove semaphore running indicator"
          connection: local
          file:
            path: "{{ semaphore_runfile }}"
            state: absent

        - import_role:
            name: post
            
        - fail:
            msg: |
              ERROR OCCURED:
              
              {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
              
              See above for details.
