---

- name: "Build {{ target_model }}"
  hosts: buildserver
  gather_facts: true

  pre_tasks:
    - name: "Show Semaphore vars"
      ansible.builtin.debug:
        msg: "{{ semaphore_vars }}"

    - name: "Prep semaphore run dir"
      connection: local
      ansible.builtin.file:
        path: "{{ semaphore_lock_dir }}"
        state: directory
          
    - name: "Set Semaphore run file"
      ansible.builtin.set_fact:
        semaphore_runfile: "{{ semaphore_lock_dir }}/{{ ROM_FLAVOR }}_{{ target_model }}_{{ build_id }}.ansible_running"

    - name: "Setup semaphore running indicator"
      connection: local
      ansible.builtin.copy:
        dest: "{{ semaphore_runfile }}"
        content: |
          date="{{ ansible_date_time.iso8601 }}"
          play=build.yml
          target={{ target_model }}
          role="{{ ROM_FLAVOR }}/{{ target_model }}"

    - name: "DEBUG: axp_type"
      ansible.builtin.debug:
        var: axp_type

    - name: "DEBUG: just_git_push"
      ansible.builtin.debug:
        var: just_git_push

    # download_fairphone_firmware is DEPRECATED!
    - name: "DEBUG: download_fairphone_firmware"
      ansible.builtin.debug:
        var: download_fairphone_firmware

    - name: "DEBUG: update_vendor_firmware"
      ansible.builtin.debug:
        var: update_vendor_firmware

    - name: "Import pre common role"
      ansible.builtin.import_role:
        name: pre   
          
  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
    - block:
    
      - name: "Import global common role"
        ansible.builtin.import_role:
          name: common

      - name: "Get ROM_FLAVOR common - default vars"
        ansible.builtin.include_role:
          name: "{{ ROM_FLAVOR }}/common"
          public: yes
        when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"

      - name: "Check Telegram notification requirement"
        ansible.builtin.fail:
          msg: "boo.. vault_tg_group_id_failing is undefined"
        when: 
          - vault_tg_group_id_failing is undefined
          - telegram_notifications | bool

      - name: "Include custom recovery vars"
        ansible.builtin.include_vars: "../roles/{{ ROM_FLAVOR }}/all/vars/{{ target_model }}.yml"
        when: 
          - ROM_FLAVOR == "SHRP" or ROM_FLAVOR == "TWRP"

      - name: "Run ROM_FLAVOR device tasks"
        ansible.builtin.include_role:
          name: "roles/{{ ROM_FLAVOR }}/{{ target_model }}"
          public: yes

      - name: "Run build role"
        ansible.builtin.include_role:
          name: build
          public: yes

      - name: "Run release role"
        ansible.builtin.include_role:
          name: release
          public: yes
        when:
          - (override_release_build == "undef" and release_build | bool) or (override_release_build | bool)
          - not build_bootimage_only | d(False)

      - name: "Set notification var (no debug build)"
        ansible.builtin.set_fact:
          tg_group_id: "{{ vault_tg_group_id_automation }}"
        when:
          - debug_build is not defined or (debug_build is defined and not debug_build | bool)
          - telegram_notifications | bool

      - name: "Set notification var (debug build)"
        ansible.builtin.set_fact:
          tg_group_id: "{{ vault_tg_group_id_failing }}"
        when:
          - debug_build is defined and debug_build | bool
          - telegram_notifications | bool

      - name: "Run notification role"
        ansible.builtin.include_role:
          name: notify

      - name: "Remove semaphore running indicator"
        connection: local
        ansible.builtin.file:
          path: "{{ semaphore_runfile }}"
          state: absent

      - name: "Run Post tasks"
        ansible.builtin.include_role:
          name: post

      # when any of the above fails notify always 
      rescue:

        - ansible.builtin.set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
          when:
            - telegram_notifications | bool

        - ansible.builtin.include_role:
            name: notify

        - name: "Remove semaphore running indicator"
          connection: local
          ansible.builtin.file:
            path: "{{ semaphore_runfile }}"
            state: absent

        - ansible.builtin.import_role:
            name: post
            
        - name: "Fail Message"
          ansible.builtin.fail:
            msg: |
              ERROR OCCURED:
              
              {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
              
              See above for details.
