---

- name: "Switch from unstable to stable"
  hosts: "{{ groups.downloadserver[0] }}"
  gather_facts: false
  become: no

  vars:
    os_zip_filename_no_ext: "{{ os_zip_filename | regex_replace('.zip','') }}"
    recovery_filename_no_ext: >-
      {{ os_zip_filename_no_ext | regex_replace('(.+-[0-9]+\.[0-9]+-[0-9]{8}).*','\1') }}
    #tg_success: |
    #    {{ ICON_GOOD }} ***New build released\!***
    #    {{ target_model | regex_escape() }}: successfully switched {{ os_zip_filename_no_ext | regex_escape() }} to STABLE channel
    tg_failed: |
        {{ ICON_BAD }} ***ERROR***
        {{ target_model | regex_escape() }}: switching {{ os_zip_filename_no_ext | regex_escape() }} to STABLE failed\!
  
  tasks:
    - block:

      - import_role:
          name: common

      - include_role:
          name: "{{ ROM_FLAVOR }}/common"
          tasks_from: vars.yml
          public: yes
        when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"

      - include_vars: "../roles/{{ ROM_FLAVOR }}/common/tasks/axp-slim.vars.yml"
        when: axp_type | d('') == "slim"

      - include_vars: "../roles/{{ ROM_FLAVOR }}/{{ target_model }}/vars/main.yml"
      - include_vars: "../roles/{{ ROM_FLAVOR }}/{{ parent_model }}/vars/main.yml"
          #file: "../roles/{{ ROM_FLAVOR }}/{{ parent_model }}/vars/main.yml"
          #hash_behaviour: merge
        when: parent_model is defined
      
      - fail:
          msg: "boo.. vault_tg_group_id_failing is undefined"
        when: 
          - vault_tg_group_id_failing is undefined
          - telegram_notifications | bool

      - set_fact:
          tg_group_id: "{{ vault_tg_group_id_automation }}"
        when:
          - telegram_notifications | bool

      - name: "Parse OS prop"
        ansible.builtin.shell: >-
          grep ro.build.version.security_patch= {{ rempath_unstable }}/{{ os_zip_filename }}.prop | cut -d "=" -f 2
        register: pprop
       
      - name: "Setup ASB level var"
        ansible.builtin.set_fact:
            sec_level_date: "{{ pprop.stdout }}"

      - block:      
          - name: "RECOVERY: switch to stable"
            ansible.builtin.shell: >-
              cp {{ rempath_unstable }}/recovery/{{ recovery_filename_no_ext }}* {{ rempath }}/recovery/
            
          - name: "RECOVERY: verify IMG integrity"
            ansible.builtin.shell: >-
                sha256sum --check {{ recovery_filename_no_ext }}*.img.sha256
            args:
              chdir: "{{ rempath }}/recovery"
      
          - name: "RECOVERY: delete from unstable"
            ansible.builtin.shell: >-
              rm -v {{ rempath_unstable }}/recovery/{{ recovery_filename_no_ext }}*.{{ item }}
            loop:
              - img
              - img.sha256
        when: axp_release_recovery

      # must have .stdout, so do not set_fact or vars it!
      - name: "Set ROMFILE"
        ansible.builtin.shell: >-
            echo "{{ os_zip_filename }}"
        register: ROMFILE
        
      - name: "OS: Get HASH (for notification)"
        ansible.builtin.shell: >-
            cat "{{ rempath_unstable }}/{{ os_zip_filename }}.sha256sum" | cut -d ' ' -f1
        register: hashfile
        
      - name: "OS: switch to stable"
        ansible.builtin.copy:
          remote_src: yes
          src: "{{ rempath_unstable }}/{{ os_zip_filename_no_ext }}.{{ item }}"
          dest: "{{ rempath }}/"
        loop:
          - zip
          - zip.sha512sum
          - zip.sha256sum
          - zip.prop

      - name: "OS: verify ZIP integrity"
        ansible.builtin.shell: "sha512sum --check {{ os_zip_filename_no_ext }}.zip.sha512sum"
        args:
          chdir: "{{ rempath }}"
  
      - name: "OS: delete from unstable"
        ansible.builtin.file:
          path: "{{ rempath_unstable }}/{{ os_zip_filename_no_ext }}.{{ item }}"
          state: absent
        loop:
          - zip
          - zip.sha512sum
          - zip.sha256sum
          - zip.prop
  
      - name: "Identify unstable build date"
        ansible.builtin.shell: |
          grep ro.build.date.utc {{ rempath }}/{{ os_zip_filename }}.prop | cut -d "=" -f2
        register: build_date_utc
  
      - name: "Correct ZIP timestamp for stable to fix recurring OTA offering"
        ansible.builtin.file:
          path: "{{ rempath }}/{{ os_zip_filename }}"
          modification_time: "{{ '%Y%m%d%H%M.%S' | strftime(build_date_utc.stdout) }}"
          access_time: "{{ '%Y%m%d%H%M.%S' | strftime(build_date_utc.stdout) }}"
          state: touch

      - name: "Set result (compat fix for release role)"
        ansible.builtin.shell: 'true'
        register: buildresult
  
      - name: "Post commands"
        ansible.builtin.shell: |
          {{ postcmd_switch_to_stable }}
        args:
          executable: /bin/bash
        when: 
          - postcmd_switch_to_stable is defined
          - buildresult.rc == 0

      - include_role:
          name: notify

      # when any of the above fails notify always 
      rescue:

        - set_fact:
            tg_group_id: "{{ vault_tg_group_id_failing }}"
          when:
            - telegram_notifications | bool

        - include_role:
            name: notify
           
        - fail:
            msg: |
              ERROR OCCURED:
              
              {{ ansible_failed_result.msg | replace('"','') |replace("'","") | regex_replace('[}{]','') }}
              
              See above for details.
