---

- name: "Testing stuff"
  hosts: buildserver
  gather_facts: false
      
  tasks:

    - ansible.builtin.setup:
        filter:
          - ansible_date_time
      
    - debug:
        var: ansible_date_time
  
    - debug:
        var: semaphore_vars
        
    #- debug:
    #    var: ansible_facts

    - import_role:
        name: common

    #- include_role:
    #    name: "{{ ROM_FLAVOR }}/common"
    #    public: yes
    #  when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"
    
    - include_vars: "../roles/{{ ROM_FLAVOR }}/common/defaults/main.yml"
      when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"    
      
    - name: "Set topics based on Android version"
      ansible.builtin.set_fact:
          sec_patch_topics: "{{ lookup('vars', 'sec_patch_topics_' + android_shortversion) }}"
      
    - name: "Telegram TEST notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: |
            DEBUG playbook ended successfully

            sec_patch_topics: {{ sec_patch_topics }}
            
            ***Platform security patch level:*** [{{ sec_level_date.stdout | regex_escape() }}](https://source.android.com/docs/security/bulletin/{{ sec_level_date.stdout | regex_replace('([0-9]+-[0-9]+)(-05)','\1-01' ) }})
          disable_web_page_preview: True
      when: telegram_notifications | bool
