---

- name: "Testing stuff"
  hosts: buildserver
  gather_facts: false
      
  tasks:

    - ansible.builtin.setup:
        filter:
          - ansible_date_time
      
    - debug:
        var: ansible_date_time
  
    - debug:
        var: semaphore_vars
        
    #- debug:
    #    var: ansible_facts

    - name: "Building"
      raw: |
         export BDEVICE=sunfish
         export DEVICE=$BDEVICE; source build/envsetup.sh; source ../../Scripts/init.sh ; lunch lineage_${DEVICE}-bp1a-user; export AXP_ADVANCED_DEBLOB=true
         source /home/droidme/build_sunfish_a15_axp.sh >> ~/LOG 2>&1
      args:
        executable: /bin/bash
        chdir: "/usr/src/android/axp/Build/LineageOS-22.2"

    - import_role:
        name: common

    #- include_role:
    #    name: "{{ ROM_FLAVOR }}/common"
    #    public: yes
    #  when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"
    
    - include_vars: "../roles/{{ ROM_FLAVOR }}/common/defaults/main.yml"
      when: ROM_FLAVOR == "axp" or ROM_FLAVOR == "graphene" or ROM_FLAVOR == "eos"    
      
    - name: "Set topics based on Android version"
      ansible.builtin.set_fact:
          sec_patch_topics: "{{ lookup('vars', 'sec_patch_topics_' + android_shortversion) }}"
      
    - name: "Telegram TEST notify"
      connection: local
      community.general.telegram:
        token: "{{ vault_tg_token }}"
        api_args:
          chat_id: "{{ vault_tg_group_id_failing }}"
          parse_mode: "MarkdownV2"
          text: |
            DEBUG playbook ended successfully

            sec_patch_topics: {{ sec_patch_topics }}
            
          disable_web_page_preview: True
      when: telegram_notifications | bool
