---
# human readable model name
target_model_vendor: "Fairphone"
target_model_name: '3'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a13

# boot debugger path & config
extendrom_debug_path_default: /mnt/vendor/persist
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/fairphone/sdm632

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_fairphone_FP3

# disable Wireguard patching (already part of the upstream kernel)
# part of the A14 and later kernel though
#skip_wireguard: True

# upload the recovery image
axp_release_recovery: True

# allow creating factory image
#custom_build_command: "{{ SH_COMMON_FAIRPHONE_CREATE_FACTORY }}"

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: ''
axp_bootloader_id_slim: '2F554EFA46B4B4A9'

# git push
axp_git_push_device_include: "{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_fairphone_FP3"

# override common log err catcher
parselogerr:
    - search: 'key .*/testkey.*.pem' # ALWAYS COPY THIS! we NEVER EVER want something signed with a testkey
      expect: ''
    - search: '{{ android_signing_testkey }}' # ALWAYS COPY THIS! sha1 of testkey we NEVER EVER want something signed with a testkey
      expect: ''
    - search: 'Algorithm:.*SHA(1|256)_RSA(1024|2048)' # ALWAYS COPY THIS! AVB (if enabled) should never use a weak key (at least "SHA512_4096")
      expect: ''
    - search: "{{ axp_bootloader_id }}" # ALWAYS COPY THIS! Check the device's bootloader ID (if AVB / vbmeta_verify is on)
      expect_cnt: 1
    - search: 'Successfully verified sha512 hashtree of.*system.img' # system should be on sha512
      expect_cnt: 1
    - search: 'Successfully verified sha256 hash of.*(boot|dtbo).img' # FP3 fails to boot when increasing
      expect_cnt: 2
    - search: 'Successfully verified sha1 hashtree of.*vendor' # FP3 fails to boot when touching this
      expect_cnt: 1

# website info
hugo_encryption: "FBEv1"
hugo_firmware: "included"
hugo_relockable: "yes"
hugo_state: "stable"
hugo_supportlevel: "community"
hugo_isab: "yes"
hugo_xda_link: "https://xdaforums.com/TBD"
hugo_first_releasedate: "2025-04-06"
hugo_kb_link: "fp3"
#hugo_custom_installguide_path: 
#hugo_axp_bootloader_id_pro: |
hugo_axp_bootloader_id_slim: |
    BOOTLOADER minimal ID
        2F554EFA

    BOOTLOADER full ID:
        2F554EFA46B4B4A9
        E2F86CD9D695018B
        667B67D29F9B5EBC
        4D09EC6750C3AEEC

hugo_patchlevel_slim: "Platform + Kernel + Firmware"

# vendor/firmware info
# source: https://support.fairphone.com/hc/en-us/articles/18896094650513-How-to-manually-install-Android-on-your-Fairphone#01HB8ZZ1BMMQNSNMFT3YXDBXA0
#
vendor_firmware_super_img: true   # factory contains super image
vendor_fairphone_factory_version: "FP3-6.A.039.7-gms-44ba459b"

vendor_firmware_download_url: "https://android-builds.fairphone.com/FP3/A13/{{ vendor_fairphone_factory_version }}-user-fastbootimage.zip"
vendor_firmware_download_sha256: "615b58bdc9eeeb0e67e20b0a24547b773cc90c6b9aac2af866677dfd0f1fc9e6"

# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though.
vendor_firmware_persistent_path: "{{ persistent_dir }}/{{ vendor_fairphone_factory_version }}.zip"