---

# git user for committing changes
git_kernel_patcher_author: "sfX-bot <sfX-bot@binbash.local>"

# base path for all required repos
cve_kernel_base_path: "/home/androidsource/do-not-touch/CVE"

# CVE checker & downloader
git_cve_checker: "ssh://git@code.binbash.rocks:22443/AXP.OS/cve_checker.git"
cve_kernel_cve_checker_path: "{{ cve_kernel_base_path }}/cve_checker"

# Kernel patch repo and path
git_kernel_patches: "ssh://git@code.binbash.rocks:22443/AXP.OS/kernel_patches.git"
cve_kernel_patches_path: "{{ cve_kernel_base_path }}/kernel_patches"
cve_kernel_incrementals_path: "{{ cve_kernel_patches_path }}/0001-LinuxIncrementals"

# Upstream repos
git_kernel_org: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
git_cip_project: "https://gitlab.com/cip-project/cip-kernel/cip-kernel-sec"
