---

# overwrite default divest_cve_checker_jar location
# fetched from: https://code.binbash.rocks/AXP.OS/cve_checker/actions/runs/22
#divest_cve_checker_jar: "/home/jenkins/cve_checker_static.jar"

# git user for committing changes
git_kernel_patcher_author: "sfX-bot <sfx-bot@binbash.rocks>"

# base path for all required repos
cve_kernel_base_path: "/home/aosp/CVE"

# CVE checker & downloader
git_cve_checker: "ssh://git@code.binbash.rocks:22443/AXP.OS/cve_checker.git"
git_cve_checker_branch: main
cve_kernel_cve_checker_path: "{{ cve_kernel_base_path }}/cve_checker"

# Kernel patch repo and path
git_kernel_patches: "ssh://git@code.binbash.rocks:22443/AXP.OS/kernel_patches.git"
cve_kernel_patches_path: "{{ cve_kernel_base_path }}/kernel_patches"
git_kernel_patches_branch: main
cve_kernel_incrementals_path: "{{ cve_kernel_patches_path }}/0001-LinuxIncrementals"

# CIP repo and path
git_cip_project: "https://gitlab.com/cip-project/cip-kernel/cip-kernel-sec.git"
git_cip_project_branch: master
cve_kernel_cip_path: "{{ cve_kernel_base_path }}/cip_kernel"

# Mainline upstream kernel
git_kernel_org: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
git_kernel_org_branch: master
kernel_stable_path: "{{ cve_kernel_base_path }}/stable_kernel"

# Android Security Bulletin Harvester
git_asb_harvester: "ssh://git@code.binbash.rocks:22443/AXP.OS/tools_android_bulletin_harvester.git"
asb_harvester_path:  "{{ cve_kernel_base_path }}/bulletin_harvester"

# set dynamic sec_patch_date_last which handles edge cases
# (days 1-4 of a month still use previous month ASB as its not released yet)
sec_month: >-
  {% if current_day | int < 5 %}{{ '%02d' | format((current_month | int)) }}{% else %}{{ '%02d' | format((current_month | int) + 1) }}{% endif %}
sec_patch_date_last: "{{ current_year }}{{ sec_month }}"

# set start and end ranges.
# we start at 2024-12 as that was the last update by DivestOS so we assume that
# all patches up to then are set properly already
sec_patch_topics_kernel:
  - "{{ range(202412, 202413) }}"
  - "{{ range(202501, 202513) }}"
  - "{{ range(202601, sec_patch_date_last | int) }}"

# set the max allowed commit date for the downloader (CVE_PATCHER_NOT_OLDER_THAN_DATE)
# mainly to avoid false positives
# if set to low it might try to download 20 years old patches.
# if set to high it might miss downloading patches which were picked up in an ASB very late
#cve_max_oldest_commit_date: "2024-10-01"
cve_max_oldest_commit_date: "1970-01-01"
