---
# human readable model name
target_model_vendor: "Samsung"
target_model_name: 'S5'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# boot debugger path & config
extendrom_debug_path_default: /cache
extendrom_debug_path_size_full_default: 500
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# ensure we get the 32bit webview
extendrom_package_list: "{{ extendrom_package_list_default | map('regex_replace', 'AOSmium_webview64', 'AOSmium_webview32') | list }}"

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/samsung/msm8974

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_samsung_klte-common

# disable Wireguard patching (unsupported, bc kernel = v3.4)
skip_wireguard: true

# disable AVB
axp_avb_version: 0

# no boot/recovery.img tests
# 1) we cannot re-lock this device
# 2) samsungs crappy boot.img handling conflicts with all standards, making verify tests fail anyways
skip_avb_boot_verify: true

# this is a low-end device (optimize for performance)
axp_lowend_device: true
axp_auto_encrypt: false

# git push
axp_git_push_device_include: "device_samsung_klte|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_samsung"

# disable Wireguard patching (unsupported, bc kernel = v3.4)
axp_defconfig_globals: ''

# special testing area
extendrom_intercept_installsrc: 'true'

#################################################################################################################################
## Website info
#

# COMMON block
hugo_firmware: "manual"

# Is the device an A/B device (legacy or virtual)?
# Can be either 'yes' or 'no'. use single quotes here:
hugo_isab: 'no'

hugo_xda_link: "https://xdaforums.com/t/rom-a11-official-microg-hardened-klte-axp-os-18-1.4703947/" # link to the AXP.OS XDA post for that device
hugo_kb_link: "klte-and-maybe-hlte" # OPTIONAL: knownissues link, only if there is any, will be prefixed with "#"
hugo_custom_installguide_path: "content/devices/custom_klte.guide" # OPTIONAL: custom installation guide
hugo_tracker_link: "{{ axp_issue_tracker_queryall }}&labels=83" # "&labels=56" for enchilada


#### PRO block ####
android_version_pro: 11
hugo_relockable_pro: 'no'
hugo_encryption_pro: "FBEv1" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
hugo_supportlevel_pro: "community"  # i.e.: "team" | "community"
hugo_first_releasedate_pro: "2024-11-20" # first public stable release date (YYYY-MM-DD)
hugo_state_pro: "stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_pro: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of: "Platform + Kernel + Firmware" | "Platform + Kernel" | "Kernel"
# "Platform + Kernel" = DEFAULT if unset
# hugo_patchlevel_pro: ""

#### SLIM block ####
android_version_slim: 11
hugo_relockable_slim: 'no'
hugo_encryption_slim: "FBEv1" # device encryption type: no|FDE|ICE|FBEv1|FBEv2
hugo_supportlevel_slim: "community" # i.e.: "team" | "community"
hugo_first_releasedate_slim: "2025-02-04" # first public stable release date (YYYY-MM-DD)
hugo_state_slim: "stable" # "stable" | "!! ALPHA !!" | "BETA"
hugo_avb_slim: "{{ axp_avb_version }}" # AVB version - if different from the global one for this device
# can be one of:
#   "Platform + Kernel + Firmware" | "Platform + Kernel" (DEFAULT if unset) | "Kernel"
# hugo_patchlevel_slim: ""
