---
# human readable model name
target_model_vendor: "Samsung"
target_model_name: 'S5'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a11

# boot debugger path & config
extendrom_debug_path_default: /cache
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# ensure we get the 32bit webview
extendrom_package_list: "{{ extendrom_package_list_default | map('regex_replace', 'AOSmium_webview64', 'AOSmium_webview32') | list }}"

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/samsung/msm8974

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_samsung_klte-common

# disable Wireguard patching (unsupported, bc kernel = v3.4)
skip_wireguard: True

# disable AVB
axp_avb_version: 0

# required for parselogerr: if axp_avb_version=1
# the partitions signed by boot_signer:
#axp_avb_bootparts: "boot|recovery"
#axp_avb_bootparts_count: 2
#axp_avb_dmparts_count: 1 # (system.img)

# no boot/recovery.img tests
# 1) we cannot re-lock this device
# 2) samsungs crappy boot.img handling conflicts with all standards, making verify tests fail anyways
skip_avb_boot_verify: True

# this is a low-end device (optimize for performance)
axp_lowend_device: True
axp_auto_encrypt: False

# git push
axp_git_push_device_include: "device_samsung_klte|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_samsung"

# disable Wireguard patching (unsupported, bc kernel = v3.4)
axp_defconfig_globals: ''

# special testing area
extendrom_intercept_installsrc: 'true'

# required for log parsing & website flavor info
axp_bootloader_id_pro: TBD
axp_bootloader_id_slim: TBD

# website info
hugo_encryption: "FBEv1"
hugo_firmware: "manual"
hugo_relockable: "no"
hugo_state: "stable"
hugo_supportlevel: "community"
hugo_isab: "no"
hugo_xda_link: "https://xdaforums.com/t/rom-a11-official-microg-hardened-klte-axp-os-18-1.4703947/"
hugo_first_releasedate: "2024-11-20"
hugo_kb_link: "klte-and-maybe-hlte"
hugo_custom_installguide_path: "content/devices/custom_${HUGO_CODENAME}.guide"
#hugo_axp_bootloader_id_pro: |
#hugo_axp_bootloader_id_slim: |
