---
# human readable model name
target_model_vendor: "OnePlus"
target_model_name: '7T Pro'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a15

# boot debugger path & config
extendrom_debug_path_default: /metadata
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/oneplus/sm8150

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_oneplus_sm8150-common

# the common tree or if there is none the device main makefile,
# usually named device.mk or common.mk. used in e.g. switch_major_release role.
# defaults to "device.mk"
target_model_device_tree_mk: common.mk

# upload the recovery image
axp_release_recovery: True

# disable Wireguard patching (already part of the upstream kernel (>= A15)
skip_wireguard: True

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: 'B9C105F3CB6FAFD3'
axp_bootloader_id_slim: ''

# git push
axp_git_push_device_include: "device_oneplus_hotdog|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_oneplus_sm8150-common|vendor_oneplus_hotdog"

 # re-testing effect of hibernation on bat life
axp_defconfig_device: "CONFIG_HIBERNATION=y CONFIG_DEBUG_FS=n"

# website info
hugo_encryption: "FBEv2"
hugo_firmware: "included"
hugo_relockable: "no"
hugo_state: "stable"
hugo_supportlevel: "team"
hugo_isab: "yes"
hugo_xda_link: "https://xdaforums.com/t/rom-a13-official-microg-hardened-hotdog-axp-os-20-0.4625525/"
hugo_first_releasedate: "2023-07-23"
hugo_kb_link: "guacamolehotdog"
#hugo_custom_installguide_path: 
#hugo_axp_bootloader_id_pro: |
#   ```
#   xxxxx
#   ```
#hugo_axp_bootloader_id_slim: |

# vendor/firmware info
# download source: https://xdaforums.com/t/oneplus-7t-pro-rom-ota-oxygen-os-repo-of-oxygen-os-builds.4003455/
vendor_firmware_download_url: "https://gauss-otacostmanual-sg.allawnofs.com/remove-d88a4d0d4f8644d2e5deaa0bfcd57816/ota/23/03/29/43440ec0-4d18-4657-a6ff-8a203bdc939a.zip"
vendor_firmware_download_sha512: "0910df09c475d04ef8fa3b0b52cc24ad24c0bd10b8433bae550663e84f6ca9d830e204e8420d42771a832dad403a353362f1cfacedfd32b17b8b5cec6ef79ee3"
# if specified: when file does not exist it will be stored there, if it does download will be skipped and the given one is used
# in any case the hash sum will be verified though.
vendor_firmware_persistent_path: "{{ persistent_dir }}/HD1913_11.F.22.zip"
