---

#- name: "ensure .ansible dir is where we expect it"
#  ansible.builtin.file:
#    src: "{{ BUILDHOME }}/.ansible"
#    dest: "{{ semaphore_work_dir }}"
#    state: link

- block:

      - name: "Ensure no compat bin links exist"
        ansible.builtin.file:
          path: "{{ item }}"
          state: absent
        loop:
          - "~/.local/bin/python"
          - "~/.local/bin/gcc"
        when: android_shortversion != "a9"
    
      - name: "Ensure compat bin links exist"
        ansible.builtin.file:
          src: "{{ item.target }}"
          path: "{{ item.lname }}"
          state: link
        loop:
          - { lname: "~/.local/bin/gcc", target: "/usr/bin/gcc-9"  }
          - { lname: "~/.local/bin/python", target: "/usr/bin/python2" }
        when: android_shortversion == "a9"

      - name: "Remove any previous log file"
        ansible.builtin.shell: >-
            find {{ BUILDHOME }} -maxdepth 1 -name '{{ build_log_name_noid }}*' -delete
        when: not keep_build_logs

      - name: "Setup logging symlink for 'latest'"
        ansible.builtin.file:
          src: "{{ BUILD_LOG }}"
          dest: "{{ BUILD_LOG_LATEST }}"
          force: true
          state: link

  when: android_shortversion is defined
