---

- name: "Set topics based on Android version"
  ansible.builtin.set_fact:
      sec_patch_topics: "{{ lookup('vars', 'sec_patch_topics_' + android_shortversion) }}"
      sec_patch_date_last: "{{ lookup('vars', 'sec_patch_date_last_' + android_shortversion) }}"
      sec_patch_topicname: "topic:{{ android_version_letter }}_asb_"

- name: "Normalize patch date"  # also ensure we do not set a later ASB month than the current one
  ansible.builtin.set_fact:
      sec_patch_date_real: "{{ sec_patch_date_last | int - 1 }}"

- name: "Set version as YYYY-MM"
  ansible.builtin.set_fact:
      sec_patch_date_last_human: >-
          {{ sec_patch_date_real | regex_replace('(^.{4})(.{2})','\1-\2') }}-{{ sec_patch_level }}

- name: "Construct exclusions (LOS, AOS, ...)"
  ansible.builtin.set_fact:
    secpatch_exclusionlist_los: "{{ secpatch_los_exclusions }}"
  when: ROM_FLAVOR != "eos"

- name: "Construct exclusions (eOS)"
  ansible.builtin.set_fact:
    secpatch_exclusionlist_eos: "{{ secpatch_los_exclusions }}|{{ secpatch_eos_exclusions }}"
  when: ROM_FLAVOR == "eos"

- name: "Check required variables"
  ansible.builtin.fail: |
    msg: 
      Missing a required variable!!
      
      Current definitions:
      {{ sec_patch_pick_branch | d('MISSING!!') }}
      {{ sec_patch_topics | d('MISSING!!') }}
      {{ sec_patch_date_last | d('MISSING!!') }}
      {{ SRCPATH | d('MISSING!!') }}
      {{ sec_patch_topicname | d('MISSING!!') }}
      
  when:
    - sec_patch_pick_branch is undefined
      or sec_patch_topics is undefined
      or sec_patch_date_last is undefined
      or SRCPATH is undefined
      or sec_patch_topicname is undefined

#- name: "Define Query"
#  ansible.builtin.set_fact:
#    pick_query: >-
#      {{ sec_patch_topics | flatten | map('regex_replace', '(^.{4})(.{2})', sec_patch_topicname + '\1-\2 ' + secpatch_common_exclusions) | join(' OR ') }}

- name: "Flatten sec_patch_topics"
  ansible.builtin.set_fact:
    flattened_sec_patch_topics: "{{ sec_patch_topics | flatten }}"
    
- name: "Extract years from sec_patch_topics"
  ansible.builtin.set_fact:
    sec_patch_years: >-
      {{ flattened_sec_patch_topics | map('regex_search', '(^.{4})') | list | unique }}

- name: "Define Queries by Year"
  ansible.builtin.set_fact:
    pick_queries: >-
     {% set queries = {} %}
      {% for year in sec_patch_years %}
        {% set topics = flattened_sec_patch_topics | select('search', '^' + '2023') | map('regex_replace', '(^.{4})(.{2})', sec_patch_topicname + '\\1-\\2 ' + secpatch_common_exclusions) | join(' OR ') %}
        {% set queries = queries | combine({year: topics}) %}
      {% endfor %}
      {{ queries }}

- name: fail
  fail:
    msg: boo
    

- block:

    - name: "SECURITY PATCH MERGE: create repopick lists by year (required to find path names)"
      # "yes y" is required to continue when the changes are > 200
      ansible.builtin.shell: >
        yes y | /usr/bin/env python3 external/cherrypicker/scripts/cherrypicker.py -R los -B {{ sec_patch_pick_branch }} -Q '{{ item.value }}'
        | grep --color=never https | col | dos2unix
        | sed 's/\*Manifest Change\*/.repo/'
        | grep -iEv '{{ secpatch_exclusionlist_eos | d(secpatch_exclusionlist_los) }}'
      args:
        chdir: "{{ SRCPATH }}"
      register: picklist
      loop: "{{ pick_queries | dict2items }}"
      loop_control:
        label: "{{ item.key }}"  # Using year as the label for the loop
      changed_when: picklist.changed
      until: picklist.changed

    - name: "SECURITY PATCH MERGE: apply security patches up to: {{ sec_patch_date_last_human }}"
      ansible.builtin.shell: |
        source build/envsetup.sh > /dev/null
        echo "patch cmd: {{ item | regex_replace('-f ',' ') }}"
        {{ item | regex_replace('-f ',' ') }} -v >> {{ BUILD_LOG }} 2>&1 || {{ item }} -fv >> {{ BUILD_LOG }} || exit 123
      args:
        executable: /bin/bash
        chdir: "{{ SRCPATH }}"
      register: spres
      loop: "{{ picklist.results | selectattr('changed', 'eq', True) | map(attribute='stdout_lines') | flatten }}"
      when: picklist.changed
    
    - name: "SECURITY PATCH MERGE: bump security patch version string to: {{ sec_patch_date_last_human }}"
      ansible.builtin.lineinfile:
        path: "{{ SRCPATH }}/build/core/version_defaults.mk"
        regexp: "PLATFORM_SECURITY_PATCH := .*"
        line: "PLATFORM_SECURITY_PATCH := {{ sec_patch_date_last_human }}"
      when: spres.changed

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
    - pick_queries | length > 3
