---

- name: "Set topics based on Android version"
  ansible.builtin.set_fact:
      sec_patch_topics: "{{ lookup('vars', 'sec_patch_topics_' + android_shortversion) }}"
      sec_patch_date_last: "{{ lookup('vars', 'sec_patch_date_last_' + android_shortversion) }}"
      sec_patch_topicname: "topic:{{ android_version_letter }}_asb_"

- name: "Normalize patch date"  # also ensure we do not set a later ASB month than the current one
  ansible.builtin.set_fact:
      sec_patch_date_real: "{{ sec_patch_date_last | int - 1 }}"

- name: "Set version as YYYY-MM"
  ansible.builtin.set_fact:
      sec_patch_date_last_human: >-
          {{ sec_patch_date_real | regex_replace('(^.{4})(.{2})','\1-\2') }}-{{ sec_patch_level }}

- name: "Construct exclusions (LOS, AOS, ...)"
  ansible.builtin.set_fact:
    secpatch_exclusionlist_los: "{{ secpatch_los_exclusions }}"
  when: ROM_FLAVOR != "eos"

- name: "Construct exclusions (eOS)"
  ansible.builtin.set_fact:
    secpatch_exclusionlist_eos: "{{ secpatch_los_exclusions }}|{{ secpatch_eos_exclusions }}"
  when: ROM_FLAVOR == "eos"

- name: "Check required variables"
  ansible.builtin.fail: |
    msg: 
      Missing a required variable!!
      
      Current definitions:
      {{ sec_patch_pick_branch | d('MISSING!!') }}
      {{ sec_patch_topics | d('MISSING!!') }}
      {{ sec_patch_date_last | d('MISSING!!') }}
      {{ SRCPATH | d('MISSING!!') }}
      {{ sec_patch_topicname | d('MISSING!!') }}
      
  when:
    - sec_patch_pick_branch is undefined
      or sec_patch_topics is undefined
      or sec_patch_date_last is undefined
      or SRCPATH is undefined
      or sec_patch_topicname is undefined

- name: "Flatten sec_patch_topics"
  ansible.builtin.set_fact:
    flattened_sec_patch_topics: "{{ sec_patch_topics | flatten }}"
 
- name: "Define Queries by ASB"
  ansible.builtin.set_fact:
    pick_queries: >-
      {{ pick_queries | d({}) | combine({
        item: (sec_patch_topicname ~ (item|string)|regex_replace('(^.{4})(.{2})', '\1-\2') ~ ' ' ~ secpatch_common_exclusions)
      }) }}
  loop: "{{ flattened_sec_patch_topics }}"
  
- block:
   
    - name: "SECURITY PATCH MERGE: create repopick lists by year (required to find path names)"
      # "yes y" is required to continue when the changes are > 200
      ansible.builtin.shell: >
        yes y | /usr/bin/env python3 external/buildtools/cherrypicker.py -R los -B {{ sec_patch_pick_branch }} -Q '{{ item.value }}'
        | grep --color=never https | col | dos2unix
        | sed 's/\*Manifest Change\*/.repo/'
        {% if secpatch_exclusionlist_eos is defined and secpatch_exclusionlist_eos != '' %}| grep -iEv '{{ secpatch_exclusionlist_eos }}'{% endif %}
        {% if secpatch_exclusionlist_los is defined and secpatch_exclusionlist_los != '' %}| grep -iEv '{{ secpatch_exclusionlist_los }}'{% endif %}
      args:
        chdir: "{{ SRCPATH }}"
      register: picklist
      loop: "{{ pick_queries | dict2items }}"
      loop_control:
        label: "{{ item.key }}"  # Using ASB as the label for the loop
      changed_when: picklist.changed
      until: picklist.changed

    - name: "SECURITY PATCH MERGE: apply security patches in ASB order"
      ansible.builtin.shell: |
        source build/envsetup.sh > /dev/null
        echo "patch cmd: {{ cherry | regex_replace('-f ',' ') }}"
        {{ cherry | regex_replace('-f ',' ') | regex_replace('external/dng/sdk','external/dng_sdk') }} -v >> {{ BUILD_LOG }} 2>&1 || {{ cherry }} -fv >> {{ BUILD_LOG }} || exit 123
      args:
        executable: /bin/bash
        chdir: "{{ SRCPATH }}"
      register: spres
      loop: "{{ picklist.results | selectattr('changed', 'eq', True) 
               | sort(attribute='item.key') 
               | map(attribute='stdout_lines') 
               | flatten }}"
      when: picklist.changed
      loop_control:
        loop_var: cherry

    - name: "DEBUG FAIL"
      fail:
        msg: DEBUG FAIL
    
    - name: "SECURITY PATCH MERGE: bump security patch version string to: {{ sec_patch_date_last_human }}"
      ansible.builtin.lineinfile:
        path: "{{ SRCPATH }}/build/core/version_defaults.mk"
        regexp: "PLATFORM_SECURITY_PATCH := .*"
        line: "PLATFORM_SECURITY_PATCH := {{ sec_patch_date_last_human }}"
      when: spres.changed

    - name: "Git commit version bump"
      ansible.builtin.shell: |
          export LC_ALL=C
          {{ DOS_INIT }}
          CMT=0
          git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1
          CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
          if [ $CMT -eq 1 -o $CMTL -gt 0 ];then 
              git commit --author="${AXP_GIT_AUTHOR} <${AXP_GIT_MAIL}>" -m "bump security patch date: {{ sec_patch_date_last_human }}"
              echo "[GIT] bumped security patch date: {{ sec_patch_date_last_human }}" >> {{ BUILD_LOG }}
          fi
      args:
        executable: /bin/bash
        chdir: "{{ SRCPATH }}/build/core"
      when: spres.changed

  when:
    - (override_reset_git == "undef" and reset_git == "true") or (override_reset_git == "true") or (override_sync == "true")
    - pick_queries is defined and (pick_queries | length > 0)
