---

- name: "Apply AXP.OS adjustments"
  block:

    - name: Set AXP facts
      ansible.builtin.set_fact:
        cpwd: "{{ SRCPATH }}"
        axp_kernel_path: "{{ target_kernel_dir }}"
        axp_device: "{{ common_target_model | d(target_model) }}"
        axp_devicevendor: "{{ target_model_vendor | lower }}"
        axp_low_storage: >-
          {{ remove_space_reservation | d(false) }}
        axp_target_version: "{{ android_version_int }}"

    - name: Derive low storage for non-SLIM builds
      ansible.builtin.set_fact:
        axp_low_storage: true
      when:
        - remove_space_reservation is undefined
        - RELEASE_TYPE != "SLIM"

    - name: Show AXP variables
      ansible.builtin.debug:
        msg:
          - "AXP_TARGET_VERSION: {{ axp_target_version }}"
          - "AXP_KERNEL_PATH: {{ axp_kernel_path }}"
          - "AOS_BRANDING_BUILDTYPE: {{ RELEASE_TYPE }}"
          - "AXP_LOW_STORAGE: {{ axp_low_storage }}"
          - "device/{{ axp_devicevendor }}/{{ axp_device }}"

    - name: Fail if kernel path is empty
      ansible.builtin.fail:
        msg: "[AXP] ERROR: kernel path could not be detected"
      when: axp_kernel_path | length == 0

    - name: Set OTA server URI
      ansible.builtin.set_fact:
        AXP_OTA_SERVER_URI: >-
          https://{{ axp_ota_server_primary }}/axp{{ '-slim' if RELEASE_TYPE == 'SLIM' else '' }}/a{{ axp_target_version }}/api/v1/{device}/{incr}

    - name: Restore strings.xml from git
      ansible.builtin.shell: git checkout strings.xml
      args:
        chdir: "{{ SRCPATH }}/vendor/axp/overlays/packages/apps/Updater/app/src/main/res/values/"

    - name: Update OTA placeholders in strings.xml
      ansible.builtin.replace:
        path: "{{ SRCPATH }}/vendor/axp/overlays/packages/apps/Updater/app/src/main/res/values/strings.xml"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: '%%AXP_OTA_SERVER_URI%%', replace: "{{ AXP_OTA_SERVER_URI }}" }
        - { regexp: '%%DOS_OTA_SERVER_PRIMARY_NAME%%', replace: "{{ axp_ota_server_primary_name }}" }
        - { regexp: '%%DOS_OTA_SERVER_SECONDARY_NAME%%', replace: "{{ axp_ota_server_secondary_name }}" }
        - { regexp: '%%DOS_OTA_SERVER_ONION_PRIMARY_NAME%%', replace: "{{ axp_ota_server_onion_primary_name }}" }
        - { regexp: '%%DOS_OTA_SERVER_ONION_SECONDARY_NAME%%', replace: "{{ axp_ota_server_onion_secondary_name }}" }

    - name: Comment OpenEUICC package
      ansible.builtin.replace:
        path: "{{ SRCPATH }}/vendor/divested/packages.mk"
        regexp: '^PRODUCT_PACKAGES.*OpenEUICC'
        replace: '# OpenEUICC disabled by AXP.OS in favor of extendrom handling'

    - name: Remove legacy OpenEUICC directory
      ansible.builtin.file:
        path: "{{ SRCPATH }}/packages/apps/OpenEUICC"
        state: absent

    - name: Find BoardConfig files
      ansible.builtin.find:
        paths:
          - "{{ SRCPATH }}/device/{{ axp_devicevendor }}/"
          - "{{ SRCPATH }}/vendor/lineage"
        patterns: "Board*.mk"
        recurse: true
        depth: 10
      register: boardconfigs
      no_log: true
      when: axp_low_storage | bool

    - name: Comment reservation flags
      ansible.builtin.replace:
        path: "{{ item.0.path }}"
        regexp: '^({{ item.1 }})'
        replace: '#\\1'
      loop: "{{ boardconfigs.files | product([
        'BOARD_PRODUCTIMAGE_EXTFS_INODE_COUNT',
        'BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE',
        'BOARD_SYSTEMIMAGE_EXTFS_INODE_COUNT',
        'BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE',
        'BOARD_SYSTEM_EXTIMAGE_EXTFS_INODE_COUNT',
        'BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE',
        '.*vendor/lineage/config/BoardConfigReservedSize.mk'
        ]) | list }}"
      when: axp_low_storage | bool

    - name: "Commit reservation removals"
      ansible.builtin.include_tasks: git_commit.yml
      vars:
        custom_commit_message: "AXP.OS: reservation removals"
        git_commit_path: "{{ item.path | dirname }}"
      loop: "{{ boardconfigs.files }}"
      when: axp_low_storage | bool

    - name: Dump TARGET_ARCH
      ansible.builtin.shell: |-
        {{ DOS_INIT }}
        {% if sub_model is defined %}
        lunch lineage_{{ sub_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1
        {% else %}
        lunch lineage_{{ target_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1
        {% endif %}
        echo "lunch success" >> {{ BUILD_LOG }}

        build/soong/soong_ui.bash --dumpvar-mode TARGET_ARCH 2>> "{{ BUILD_LOG }}"
      register: target_arch
      changed_when: false
      failed_when: false
      when: not kleaf_kernel_build | bool
      args:
        executable: /bin/bash
        chdir: "{{ SRCPATH }}"

    - name: Dump TARGET_KERNEL_CONFIG
      ansible.builtin.shell: |
        {{ DOS_INIT }}
        {% if sub_model is defined %}
        lunch lineage_{{ sub_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1
        {% else %}
        lunch lineage_{{ target_model }}${brf_suffix}-user >> {{ BUILD_LOG }} 2>&1
        {% endif %}
        echo "lunch success" >> {{ BUILD_LOG }}

        build/soong/soong_ui.bash --dumpvar-mode TARGET_KERNEL_CONFIG 2>> "{{ BUILD_LOG }}" | cut -d " " -f 1
      register: kernel_conf_file
      changed_when: false
      failed_when: false
      when: not kleaf_kernel_build | bool
      args:
        executable: /bin/bash
        chdir: "{{ SRCPATH }}"

    - name: Set kernel facts
      ansible.builtin.set_fact:
        axp_kernel_conf: >-
          {% if kleaf_kernel_build | bool %}
          {{ pixel_kernel_defconfig }}
          {% else %}
          {{ SRCPATH }}/{{ target_kernel_dir }}/arch/{{ target_arch.stdout }}/configs/{{ kernel_conf_file.stdout }}
          {% endif %}

    - name: Check patch marker
      ansible.builtin.stat:
        path: "{{ target_kernel_dir }}/.defconf.patched"
      register: defconf_marker

    - name: Patch kernel defconfig (globals)
      ansible.builtin.lineinfile:
        path: "{{ axp_kernel_conf | trim }}"
        line: "{{ item }}=y"
        state: present
      loop: "{{ axp_defconfig_globals }}"
      when: not defconf_marker.stat.exists # and not (kleaf_kernel_build | bool)

    - name: Patch kernel defconfig (device)
      ansible.builtin.lineinfile:
        path: "{{ axp_kernel_conf | trim }}"
        line: "{{ item }}"
        state: present
      loop: "{{ axp_defconfig_device | default([]) }}"
      when:
        - not defconf_marker.stat.exists
        - axp_defconfig_device is defined
        #- not (kleaf_kernel_build | bool)

    - name: Create patch marker
      ansible.builtin.file:
        path: "{{ SRCPATH }}/{{ target_kernel_dir }}/.defconf.patched"
        state: touch
      when: not defconf_marker.stat.exists and not (kleaf_kernel_build | bool)

    - name: Copy defconfig to common tree (if KLEAF)
      ansible.builtin.copy:
        src: "{{ axp_kernel_conf | trim }}"
        dest: "{{ SRCPATH }}/{{ target_model_common_tree_path }}/"
        remote_src: true
      when:
        - pixel_kernel_defconfig is defined
        - kleaf_kernel_build | bool

    - name: Commit kernel defconfig changes
      ansible.builtin.shell: |
        {% if kleaf_kernel_build | bool %}
        cd {{ SRCPATH }}/{{ target_model_common_tree_path | trim }}
        {% else %}
        cd {{ SRCPATH }}/{{ target_kernel_dir | trim }}
        {% endif %}
        
        source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}-{{ android_shortversion }}-{{ axp_type | upper() }}

        CMT=0
        git add -A || CMT=1
        # check for uncommitted changes
        CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
        # commit if required
        if [ $CMT -eq 1 -o $CMTL -gt 0 ];then
            git add -A && git commit --author="$AXP_GIT_AUTHOR <$AXP_GIT_MAIL>" -m "defconfig: applied:

        {{ axp_defconfig_globals | join(' ') }} {{ axp_defconfig_device | default('') | join(' ') }}"
        fi
      args:
        executable: /bin/bash
      when: not (kleaf_kernel_build | bool)

    - name: Set AXP.OS build id
      ansible.builtin.shell: |
        source {{ BUILDHOME }}/.divested.vars.{{ sub_model | d(target_model) }}-{{ android_shortversion }}-{{ axp_type | upper() }}
        find vendor/lineage -type f -name '*.mk' -exec sed -i "s/ro\.lineage\.version=\$(LINEAGE_VERSION)/ro.lineage.version={{ axp_os_build_id }}/g" {} \;
        find vendor/lineage -type f -name '*.mk' -exec sed -i "s/ro\.lineage\.display\.version=\$(LINEAGE_DISPLAY_VERSION)/ro.lineage.display.version={{ axp_os_build_id }}/g" {} \;
        echo "LineageOS version set to: {{ axp_os_build_id }}" | tee -a {{ BUILD_LOG }}
        cd vendor/lineage

        CMT=0
        git add -A || CMT=1
        # check for uncommitted changes
        CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)
        # commit if required
        if [ $CMT -eq 1 -o $CMTL -gt 0 ];then
            git add -A && git commit --author="$AXP_GIT_AUTHOR <$AXP_GIT_MAIL>" -m "AXP.OS: set build id ({{ axp_os_build_id }})"
        fi
      args:
        chdir: "{{ SRCPATH }}"
        executable: /bin/bash
