---

- name: "apply specific gs201 common fixup"
  ansible.builtin.shell: |-
    # the divest deblobber removes the clearkey entry AND PRODUCT_PACKAGES += so we need to re-add it
    sed -i -E 's/\s+android.hardware.drm-service.widevine/PRODUCT_PACKAGES += android.hardware.drm-service.widevine/g' device/google/gs201/widevine/device.mk
  args:
    chdir: "{{ SRCPATH }}"
    executable: /bin/bash

- name: "Commit kernel changes"
  ansible.builtin.include_tasks: git_commit.yml
  vars:
    custom_commit_message: "AXP.OS: fixup deblob leftovers"
    git_commit_kernel: true

- name: "Check gs201"
  ansible.builtin.stat:
    path: "{{ SRCPATH }}/device/google/gs201/widevine/device.mk"
  register: p201wv

- name: "Fix gs201 widevine leftovers"
  when: p201wv.stat.exists
  block:

    - name: Ensure PRODUCT_PACKAGES header exists
      ansible.builtin.lineinfile:
        path: "{{ SRCPATH }}/device/google/gs201/widevine/device.mk"
        line: "PRODUCT_PACKAGES += \\"
        insertbefore: BOF

    - name: "Commit gs201 changes"
      ansible.builtin.include_tasks: git_commit.yml
      vars:
        custom_commit_message: "AXP.OS: gs201: fix divest deblob leftovers"
        git_commit_path: "{{ SRCPATH }}/device/google/gs201"
