---

- name: klte specific adjustments
  ansible.builtin.lineinfile:
    path: "{{ SRCPATH }}/{{ target_model_common_tree_path | d(target_model_device_tree_path) }}/sepolicy/rild.te"
    line: "allow rild radio_data_file:lnk_file getattr;"
    state: present
    create: true

- name: "Commit klte changes"
  ansible.builtin.include_tasks: git_commit.yml
  vars:
    custom_commit_message: "AXP.OS: set rild policy"
    git_commit_path: "{{ SRCPATH }}/{{ target_model_common_tree_path | d(target_model_device_tree_path) }}"
