- base_ver: '4.19'
  git_name: linux-4.19.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/4.19
  tag_regexp: (^v4\.19$|^v4\.19\.\d+$)
- short_name: openela/4.14
  base_ver: "4.14"
  git_remote: openela
  git_name: linux-4.14.y
- base_ver: '4.14'
  git_name: linux-4.14.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/4.14
  tag_regexp: (^v4\.14$|^v4\.14\.\d+$)
- base_ver: '4.9'
  git_name: linux-4.9.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/4.9
  tag_regexp: (^v4\.9$|^v4\.9\.\d+$)
- base_ver: '4.4'
  git_name: linux-4.4.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/4.4
  tag_regexp: (^v4\.4$|^v4\.4\.\d+$)
- short_name: aosp/3.18
  base_ver: "3.18"
  git_remote: aosp
  git_name: deprecated/android-3.18
- short_name: aosp/3.10
  base_ver: "3.10"
  git_remote: aosp
  git_name: deprecated/android-3.10
- short_name: aosp/3.4
  base_ver: "3.4"
  git_remote: aosp
  git_name: deprecated/android-3.4
- short_name: aosp/3.0
  base_ver: "3.0"
  git_remote: aosp
  git_name: deprecated/android-3.0
- base_ver: '3.18'
  git_name: linux-3.18.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/3.18
  tag_regexp: (^v3\.18$|^v3\.18\.\d+$)
- base_ver: '3.10'
  git_name: linux-3.10.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/3.10
  tag_regexp: (^v3\.10$|^v3\.10\.\d+$)
- base_ver: '3.4'
  git_name: linux-3.4.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/3.4
  tag_regexp: (^v3\.4$|^v3\.4\.\d+$)
- base_ver: '3.0'
  git_name: linux-3.0.y
  git_remote: stable
  patch_queue: stable-queue
  short_name: stable/3.0
  tag_regexp: (^v3\.0$|^v3\.0\.\d+$)
