---

- name: "Get ansible log path"
  become: false
  connection: local
  ansible.builtin.shell: >-
    grep -E '^log_path\s+=' "{{ ansible_config_file }}" | cut -d '=' -f 2
  register: ansible_log

- name: "Flatten log path"
  become: false
  ansible.builtin.set_fact:
    ansible_log_flatten: "{{ ansible_log.stdout | regex_replace('\\$HOME', ansible_home_dir) }}"

- name: "Rotate ANSIBLE log"
  become: false
  connection: local
  ansible.builtin.shell: "mv {{ ansible_log.stdout }} {{ ansible_home_dir }}/ansible-log.{{ build_no }} || true"

- block:

  - name: "Register buildlogfile"
    connection: local
    ansible.builtin.stat:
      path: "/tmp/{{ inventory_hostname }}/{{ build_log_name }}"
    register: buildlogfile
  
  - name: "Rotate BUILD log"
    connection: local
    ansible.builtin.shell: "mv /tmp/{{ inventory_hostname }}/{{ build_log_name }} /tmp/{{ inventory_hostname }}/build_{{ target_model }}_{{ android_shortversion }}_{{ ROM_FLAVOR }}.log.{{ build_no }}"
    when: buildlogfile.stat.isreg is defined

  become: false
  when: ROM_FLAVOR != "MAID"
