---

- name: "Grab DOS CVE Checker"
  ansible.builtin.get_url:
    url: "{{ divest_cve_checker_download }}"
    dest: "{{ divest_cve_checker_jar }}"
    mode: 0640

- name: "Run CIP update/fetch"
  ansible.builtin.shell: |
    git checkout {{ git_kernel_org_branch }}
    git fetch origin
    git rebase origin/{{ git_kernel_org_branch }}
    git checkout -b $(date -uI) || true
    if [ -f ../cip-personal-tweaks.patch ];then git am ../cip-personal-tweaks.patch;fi

    # prepare & sync remotes
    ./scripts/prepare_remotes.py --git-repo "{{ kernel_stable_path }}" >> {{ BUILD_LOG }} 2>&1

    # import
    ./scripts/import_stable.py --git-repo "{{ kernel_stable_path }}" >> {{ BUILD_LOG }} 2>&1
    git add -A && git commit -a -m 'Import data from stable branches' >> {{ BUILD_LOG }} 2>&1
    ./scripts/import_debian.py --git-repo "{{ kernel_stable_path }}" >> {{ BUILD_LOG }} 2>&1
    git add -A && git commit -a -m 'Import data from Debian' >> {{ BUILD_LOG }} 2>&1
    ./scripts/import_stable.py --git-repo "{{ kernel_stable_path }}" >> {{ BUILD_LOG }} 2>&1
    git add -A && git commit -a -m 'Import data from stable branches' >> {{ BUILD_LOG }} 2>&1
    ./scripts/import_ubuntu.py --git-repo "{{ kernel_stable_path }}" >> {{ BUILD_LOG }} 2>&1
    git add -A && git commit -a -m 'Import data from Ubuntu' >> {{ BUILD_LOG }} 2>&1
    ./scripts/import_stable.py --git-repo "{{ kernel_stable_path }}" >> {{ BUILD_LOG }} 2>&1
    git add -A && git commit -a -m 'Import data from stable branches' >> {{ BUILD_LOG }} 2>&1
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_cip_path }}"

- name: "Run CIP tool"
  ansible.builtin.shell: |
      # create CIP.txt
      ./CIP.sh {{ cve_kernel_cip_path }} >> {{ BUILD_LOG }} 2>&1
  register: buildresult
  environment:
    DOS_BINARY_PATCHER: "{{ divest_cve_checker_jar }}"
    DOS_PATCHES_LINUX_CVES: "{{ cve_kernel_patches_path }}"
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_patches_path }}"

- name: "Clean-up"
  ansible.builtin.shell: |
      # remove unwanted (i.e. non LTS) patches
      ./rm-nonlts.sh  >> {{ BUILD_LOG }} 2>&1
  register: buildresult
  environment:
    DOS_BINARY_PATCHER: "{{ divest_cve_checker_jar }}"
    DOS_PATCHES_LINUX_CVES: "{{ cve_kernel_patches_path }}"
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_patches_path }}"

# next:
# merge CIP.txt with Kernel_CVE_Patch_List.txt
# java -jar $DOS_BINARY_PATCHER download $DOS_PATCHES_LINUX_CVES/Kernel_CVE_Patch_List.txt
