---

- name: "Grab DOS CVE Checker"
  ansible.builtin.get_url:
    url: "{{ divest_cve_checker_download }}"
    dest: "{{ divest_cve_checker_jar }}"
    mode: 0640

- name: "Run CIP update/fetch"
  ansible.builtin.shell: |
    git checkout master
    git fetch orig
    git rebase orig/master
    git checkout -b $(date -uI)
    git am ../cip-personal-tweaks.patch
    ./scripts/import_stable.py --git-repo "{{ kernel_stable_path }}"
    git add -A && git commit -a -m 'Import data from stable branches'
    ./scripts/import_debian.py --git-repo "{{ kernel_stable_path }}"
    git add -A && git commit -a -m 'Import data from Debian'
    ./scripts/import_stable.py --git-repo "{{ kernel_stable_path }}"
    git add -A && git commit -a -m 'Import data from stable branches'
    ./scripts/import_ubuntu.py --git-repo "{{ kernel_stable_path }}"
    git add -A && git commit -a -m 'Import data from Ubuntu'
    ./scripts/import_stable.py --git-repo "{{ kernel_stable_path }}"
    git add -A && git commit -a -m 'Import data from stable branches'
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_cip_path }}"

- name: "Run CIP tool"
  ansible.builtin.shell: |
      ./CIP.sh {{ cve_kernel_cip_path }} >> {{ BUILD_LOG }} 2>&1

      # next:
      # merge CIP.txt with Kernel_CVE_Patch_List.txt
      # java -jar $DOS_BINARY_PATCHER download $DOS_PATCHES_LINUX_CVES/Kernel_CVE_Patch_List.txt
  register: buildresult
  environment:
    DOS_BINARY_PATCHER: "{{ divest_cve_checker_jar }}"
    DOS_PATCHES_LINUX_CVES: "{{ cve_kernel_patches_path }}"
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_patches_path }}"
