---

- name: "Get ASB harvester"
  ansible.builtin.git:
    repo: "{{ git_asb_harvester }}"
    dest: "{{ asb_harvester_path }}"
    force: true
  timeout: 180

- name: "Fetch ASB Kernel patches"
  ansible.builtin.shell: |
    go get github.com/dukebarman/android-bulletins-harvester >> {{ BUILD_LOG }} 2>&1
    go build . >> {{ BUILD_LOG }} 2>&1
    {% for t in bull_range | split(' ') %}
        ./android-bulletins-harvester -kernel -quiet -jsonk -url https://source.android.com/docs/security/bulletin/{{ t }} #2>> {{ BUILD_LOG }}
    {% endfor %}
  args:
    chdir: "{{ asb_harvester_path }}"
  register: asbk

- block:

    - name: "Parse the output and store it in a list"
      ansible.builtin.set_fact:
        cve_list: "{{ asbk.stdout_lines | map('from_json') | list }}"

    - name: "Check if patch exists already"
      ansible.builtin.shell: "grep -q '{{ item.link }}' {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt"
      register: patch_exists
      ignore_errors: yes
      changed_when: false
      loop: "{{ cve_list }}"
      loop_control:
        loop_var: item

    - name: test
      debug:
        var: patch_exists.results
        
    - name: "Check if the CVE exists already"
      ansible.builtin.shell: "grep -q '^{{ item.id }}-aosp$' {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt"
      register: id_exists
      ignore_errors: yes
      changed_when: false
      loop: "{{ cve_list }}"
      loop_control:
        loop_var: item
      when: patch_exists is defined and patch_exists.results | map(attribute='item.rc') != 0

    - name: "Append link if CVE exists"
      ansible.builtin.lineinfile:
        path: "{{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt"
        line: "        Link - 6.x - {{ item.1.link }}"
        insertafter: "^{{ item.1.id }}-aosp$"
        create: yes
      when: item.0.rc == 0
      loop: "{{ id_exists.results | zip(cve_list) | list }}"
      loop_control:
        loop_var: item
      when:
        - item.0.rc != 0
        - patch_exists is defined and patch_exists.results | map(attribute='item.rc') != 0

    - name: "Add both CVE and link if both do not exist"
      ansible.builtin.blockinfile:
        path: "{{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt"
        block: |
          {{ item.1.id }}-aosp
                  Link - 6.x - {{ item.1.link }}
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.1.id }}"
      loop: "{{ id_exists.results | zip(cve_list) | list }}"
      loop_control:
        loop_var: item
      when:
        - item.0.rc != 0
        - patch_exists is defined and patch_exists.results | map(attribute='item.rc') != 0

  when: asbk.stdout != ""
