---

- name: "Get ASB harvester"
  ansible.builtin.git:
    repo: "{{ git_asb_harvester }}"
    dest: "{{ asb_harvester_path }}"
    force: true
  timeout: 180

- name: "Fetch ASB Kernel patches"
  ansible.builtin.shell: |
    go get github.com/dukebarman/android-bulletins-harvester >> {{ BUILD_LOG }} 2>&1
    go build . >> {{ BUILD_LOG }} 2>&1
    {% for t in bull_range | split(' ') %}
        ./android-bulletins-harvester -kernel -quiet -jsonk -url https://source.android.com/docs/security/bulletin/{{ t }} 2>> {{ BUILD_LOG }}
    {% endfor %}
  args:
    chdir: "{{ asb_harvester_path }}"
  register: asbk

- block:

    - name: "Parse the output and store it in a list"
      ansible.builtin.set_fact:
        cve_list: "{{ asbk.stdout_lines | map('from_json') | list }}"

    - name: "Update Kernel patch list"
      ansible.builtin.shell: |
        PATCHED=0
        haslink=$(grep -c '{{ item.link }}' {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt)
        if [ $haslink -eq 0 ];then
          hasid=$(grep -c '{{ item.id }}-aosp' {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt)
          if [ $hasid -eq 0 ];then
            echo "{{ item.id }}-aosp" >> {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt
            echo "        Link - {{ item.link }}" >> {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt && PATCHED=$((PATCHED +1))
          else
            awk '{if ($0 ~ /{{ item.id }}-aosp/) { $0 = $0 "         Link - " {{ item.link }}; } print}' {{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt >> {{ BUILD_LOG }} 2>&1 && PATCHED=$((PATCHED +1))
          fi
        fi
        echo $PATCHED
      register: patchlist
      changed_when: patchlist.stdout != "0"
      loop: "{{ cve_list }}"

  when: asbk.stdout != ""
