---

- name: "Check cve checker init state"
  ansible.builtin.stat:
    path: "{{ cve_kernel_cve_checker_path }}/.git"
  register: cvedir

- name: "Check kernel patches init state"
  ansible.builtin.stat:
    path: "{{ cve_kernel_patches_path }}/.git"
  register: patchesdir

- name: "Check kernel cip init state"
  ansible.builtin.stat:
    path: "{{ cve_kernel_cip_path }}/.git"
  register: cipdir

- name: "Init kernel CIP project: initial Sync!"
  ansible.builtin.shell: |
    git init
    git remote add origin {{ git_cip_project }}
    git pull origin {{ git_cip_project_branch }}
    git log -1
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_cip_path }}"
  when: cipdir.stat.isdir is undefined

- name: "Init kernel cve checker: initial Sync!"
  ansible.builtin.shell: |
    git init
    git remote add origin {{ git_cve_checker }}
    git pull origin main
    git log -1
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_cve_checker_path }}"
  when: cvedir.stat.isdir is undefined

- name: "Init kernel patches: initial Sync!"
  ansible.builtin.shell: |
    git init
    git remote add origin {{ git_kernel_patches }}
    git pull origin main
    git log -1
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_patches_path }}"
  when: patchesdir.stat.isdir is undefined
