---

- include_tasks: prep.yml
- include_tasks: init.yml
- include_tasks: reset.yml
- include_tasks: sync.yml

- include_tasks: cip.yml
- include_tasks: incremental.yml

- include_tasks: push.yml
  when:
    - commit_push | d(False)
