---

- name: "Download patches"
  ansible.builtin.shell: |
      java -jar $DOS_BINARY_PATCHER download $DOS_PATCHES_LINUX_CVES/Kernel_CVE_Patch_List.txt >> {{ BUILD_LOG }} 2>&1
  environment:
    DOS_BINARY_PATCHER: "{{ divest_cve_checker_jar }}"
    DOS_PATCHES_LINUX_CVES: "{{ cve_kernel_patches_path }}"
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_patches_path }}"
