---

- name: "Check/Create required dirs"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ cve_kernel_cve_checker_path }}"
    - "{{ cve_kernel_patches_path }}"
    - "{{ cve_kernel_cip_path }}"
    - "{{ kernel_stable_path }}"

- name: "Configure remotes"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - { "src": "tweak.patch", "dst": "~/.config/kernel-sec/tweak.patch" }
    - { "src": "remotes.yml", "dst": "~/.config/kernel-sec/remotes.yml" }
    - { "src": "branches.yml", "dst": "~/.config/kernel-sec/branches.yml" }

- name: "Set topics based on Android version"
  ansible.builtin.set_fact:
      sec_patch_topics: "{{ lookup('vars', 'sec_patch_topics_' + android_shortversion) }}"
