---

- name: "Prep Kernel_CVE_Patch_List.txt"
  ansible.builtin.lineinfile:
    path: "{{ cve_kernel_patches_path }}/Kernel_CVE_Patch_List.txt"
    regexp: "{{ item }}"
    state: absent
  loop: 
    - "#The above line must be the last line"
    - "^CVE-0000-0000"
