---

- name: "Check/Create required dirs"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ cve_kernel_cve_checker_path }}"
    - "{{ cve_kernel_patches_path }}"
    - "{{ cve_kernel_cip_path }}"
    - "{{ kernel_stable_path }}"
