---

- name: "Push detected changes"
  ansible.builtin.shell: |      
      export LC_ALL=C
      CMT=0
      echo "processing: {{ item }}" >> {{ BUILD_LOG }}
      
      # add unstaged changes
      git add -A >> {{ BUILD_LOG }} 2>&1 || CMT=1

      dbr=$(git symbolic-ref refs/remotes/origin/HEAD --short)
      git checkout $dbr
       
      # check for uncommitted changes
      CMTL=$(git status --porcelain=v1 | wc -l 2>/dev/null)

      # commit if any of the above require it
      if [ $CMT -eq 1 -o $CMTL -gt 0 ];then 
          git commit --author="{{ git_kernel_patcher_author }}" -m "automated kernel patcher run" >> {{ BUILD_LOG }} 2>&1 \
            && echo "committed changes $(git log -1 --format=oneline)" >> {{ BUILD_LOG }} \
            && git pull --rebase origin main >> {{ BUILD_LOG }} 2>&1 \
            && git push --set-upstream origin >> {{ BUILD_LOG }} 2>&1 && echo "pushed changes!" >> {{ BUILD_LOG }}
      fi
  args:
    executable: /bin/bash
    chdir: "{{ item }}"
  loop:
    - "{{ cve_kernel_cve_checker_path }}"
    - "{{ cve_kernel_patches_path }}"
