---

- name: "Reset kernel patcher dirs"
  ansible.builtin.shell: |
       echo "BEFORE reset:" >> {{ BUILD_LOG }}
       git log -1 >> {{ BUILD_LOG }} 2>&1
       git status >> {{ BUILD_LOG }} 2>&1
       if [ $? -eq 128 ];then
         echo "No local changes in kernel patcher repo found!"  >> {{ BUILD_LOG }}
       else
         git am --abort >> {{ BUILD_LOG }} 2>&1 || true
         git rebase --abort >> {{ BUILD_LOG }} 2>&1 || true
         git add -A . && git stash save befreset-$(date +%F_%T) >> {{ BUILD_LOG }} 2>&1 || true
       fi
       git reset --hard origin/{{ item.branch | d("main") }} >> {{ BUILD_LOG }} 2>&1
       git checkout {{ item.branch | d("main") }}
  args:
    chdir: "{{ item.path }}"
  loop:
    - path: "{{ cve_kernel_cve_checker_path }}"
      branch: "{{ git_cve_checker_branch }}"
    - path: "{{ cve_kernel_patches_path }}"
      branch: "{{ git_kernel_patches_branch }}"
    - path: "{{ cve_kernel_cip_path }}"
      branch: "{{ git_cip_project_branch }}"
    - path: "{{ kernel_stable_path }}"
      branch: "{{ git_kernel_org_branch }}"
