---

- name: "Sync kernel patcher"
  ansible.builtin.shell: |
    git pull
    git checkout HEAD -f
    git pull
    git log -1
  args:
    executable: /bin/bash
    chdir: "{{ cve_kernel_patches_path }}"
