---

- name: "Sync kernel patcher repos"
  ansible.builtin.shell: |
    git fetch --all
    dbr=$(git symbolic-ref refs/remotes/origin/HEAD --short)
    git checkout $dbr -f
    git pull --rebase
    git log -1
  args:
    executable: /bin/bash
    chdir: "{{ item }}"
  loop:
    - "{{ cve_kernel_cve_checker_path }}"
    - "{{ cve_kernel_patches_path }}"
    - "{{ cve_kernel_cip_path }}"
    - "{{ kernel_stable_path }}"
