---

- name: "Sync kernel patcher repos"
  ansible.builtin.shell: |
    git fetch --all --tags --prune --force >> {{ BUILD_LOG }} 2>&1
    git reset --hard origin/{{ item.branch | d("main") }} >> {{ BUILD_LOG }} 2>&1
    git checkout {{ item.branch | d("main") }} >> {{ BUILD_LOG }} 2>&1
    git pull --rebase >> {{ BUILD_LOG }} 2>&1
    git log -1 >> {{ BUILD_LOG }} 2>&1
  args:
    chdir: "{{ item.path }}"
    executable: /bin/bash
  loop:
    - path: "{{ cve_kernel_cve_checker_path }}"
      branch: "{{ git_cve_checker_branch }}"
    - path: "{{ cve_kernel_patches_path }}"
      branch: "{{ git_kernel_patches_branch }}"
    - path: "{{ cve_kernel_cip_path }}"
      branch: "{{ git_cip_project_branch }}"
    - path: "{{ kernel_stable_path }}"
      branch: "{{ git_kernel_org_branch }}"
