---
# human readable model name
target_model_vendor: "OnePlus"
target_model_name: '5T'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a13

# boot debugger path & config
extendrom_debug_path_default: /mnt/vendor/persist
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/oneplus/msm8998

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_oneplus_msm8998-common

# the common tree or if there is none the device main makefile,
# usually named device.mk or common.mk. used in e.g. switch_major_release role.
# defaults to "device.mk"
target_model_device_tree_mk: common.mk

# upload the recovery image
axp_release_recovery: True

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: True

# set AVB v1.0
axp_avb_version: 1

# set expected results accordingly to the AVB setup
parselogerr:
  - search: 'key .*/testkey.*.pem' # ALWAYS COPY THIS! we NEVER EVER want something signed with a testkey
    expect: ''
  - search: '{{ android_signing_testkey }}' # ALWAYS COPY THIS! we NEVER EVER want something signed with a testkey
    expect: ''
  - search: 'Algorithm:.*{{ axp_avb_algorithm }}' # AVB only: the AVB key algo should be axp_avb_algorithm
    expect_cnt: 1
  - search: "{{ axp_bootloader_id }}" # AVB only: Check the device's bootloader ID (if AVB / vbmeta_verify is on)
    expect_cnt: 1
  - search: 'Hash Algorithm:.*sha(1|512)' # AVB only: fail if vbmeta hash algo found (info_image) but not the expected KEYS_HASHTYPE
    expect: ''
  - search: 'Successfully verified sha(256|512) hash of' # AVB only: fail if vbmeta verify found (verify_image) but not the expected axp_avb_hashtree_algorithm
    expect: ''

# this is a low-end device (optimize for performance, increase storage, lower avb hashsums)
axp_lowend_device: True

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: '88F1461CFC869B86'
axp_bootloader_id_slim: ''

# git push
axp_git_push_device_include: "device_oneplus_dumpling|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_oneplus_msm8998-common|vendor_oneplus_dumpling"
