---
# human readable model name
target_model_vendor: "OnePlus"
target_model_name: '5T'
target_model_full: "{{ target_model_vendor }} {{ target_model_name }}"

# android version
android_shortversion: a13

# boot debugger path & config
extendrom_debug_path_default: /mnt/vendor/persist
extendrom_debug_path_size_full_default: 500 
extendrom_debug_path_size_kernel_default: 100
extendrom_debug_path_size_selinux_default: 200
extendrom_debug_path_size_crash_default: 200

# path to the kernel dir (req for e.g. wireguard)
target_kernel_dir: kernel/oneplus/msm8998

# path to the common tree, if none exists the device tree
# required e.g. for git, vendor/axp, release handling etc
target_model_common_tree: device_oneplus_msm8998-common

# the common tree or if there is none the device main makefile,
# usually named device.mk or common.mk. used in e.g. switch_major_release role.
# defaults to "device.mk"
target_model_device_tree_mk: common.mk

# upload the recovery image
axp_release_recovery: True

# disable Wireguard patching (already part of the upstream kernel)
skip_wireguard: True

# set AVB v1.0
axp_avb_version: 1

# required for parselogerr: if axp_avb_version=1
# the partitions signed by boot_signer:
axp_avb_bootparts: "boot|recovery"
axp_avb_bootparts_count: 2
axp_avb_dmparts_count: 2 # (system.img + vendor.img)

# dumpling will always fail verifying the boot.img if the expire date is set to the default (30 years)
KEYS_CERT_DAYS_VERITY: 3650

# this is a low-end device (optimize for performance, increase storage, lower avb hashsums)
axp_lowend_device: True

# Bootloader ID (first line) for verifying build log
axp_bootloader_id_pro: '8BBD5CAAEEF07AAD'
axp_bootloader_id_slim: ''

# git push
axp_git_push_device_include: "device_oneplus_dumpling|{{ target_model_common_tree }}"
axp_git_push_vendor_include: "vendor_oneplus_msm8998-common|vendor_oneplus_dumpling"

# website info
hugo_encryption: "ICE"
hugo_firmware: "included"
hugo_relockable: "yes (since 2025-12-03)"
hugo_state: "stable"
hugo_supportlevel: "community"
hugo_isab: "no"
hugo_xda_link: ""
hugo_first_releasedate: "2025-08-05 (A13)"
hugo_kb_link: "cheeseburgerdumpling"
#hugo_custom_installguide_path: 
hugo_axp_bootloader_id_pro: |
  BOOTLOADER minimal ID (AVB 1)
        8BBD5CAA

  BOOTLOADER full ID:
        8BBD5CAAEEF07AAD
        285D20F4B0AC87ED
        9F7F0F4C5D11A4E2
        4F9DDF445E69828D
#hugo_axp_bootloader_id_slim: |
